!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqw in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FQW_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-703 (DEC 1989).
!
!     Radix two Hermitian to real Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:1), b(0:p-1, 0:1, 0:r-1), cosine&
& (0:r-1), sine(0:r-1)
  DOUBLE PRECISION :: ab(0:p-1, 0:r-1, 0:1), bb(0:p-1, 0:1, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: ck, sk, x1hat, y1hat
  DOUBLE PRECISION :: x1hatb, y1hatb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!
!     Code for general K --
!
  IF (p .LT. (r-1)/2) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        y1hatb = cosine(k)*bb(i, 1, r-k)
        x1hatb = sine(k)*bb(i, 1, r-k)
        bb(i, 1, r-k) = 0.D0
        x1hatb = x1hatb + cosine(k)*bb(i, 1, k)
        y1hatb = y1hatb - sine(k)*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        ab(i, r-k, 1) = ab(i, r-k, 1) + bb(i, 0, r-k)
        ab(i, k, 1) = ab(i, k, 1) - bb(i, 0, r-k)
        bb(i, 0, r-k) = 0.D0
        ab(i, k, 0) = ab(i, k, 0) + bb(i, 0, k)
        ab(i, r-k, 0) = ab(i, r-k, 0) + bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        ab(i, r-k, 1) = ab(i, r-k, 1) + y1hatb
        ab(i, k, 1) = ab(i, k, 1) + y1hatb
        ab(i, k, 0) = ab(i, k, 0) + x1hatb
        ab(i, r-k, 0) = ab(i, r-k, 0) - x1hatb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      kp = r - k
      sk = sine(k)
      ck = cosine(k)
      DO i=p-1,0,-1
        y1hatb = ck*bb(i, 1, kp)
        x1hatb = sk*bb(i, 1, kp)
        bb(i, 1, kp) = 0.D0
        x1hatb = x1hatb + ck*bb(i, 1, k)
        y1hatb = y1hatb - sk*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        ab(i, kp, 1) = ab(i, kp, 1) + bb(i, 0, kp)
        ab(i, k, 1) = ab(i, k, 1) - bb(i, 0, kp)
        bb(i, 0, kp) = 0.D0
        ab(i, k, 0) = ab(i, k, 0) + bb(i, 0, k)
        ab(i, kp, 0) = ab(i, kp, 0) + bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        ab(i, kp, 1) = ab(i, kp, 1) + y1hatb
        ab(i, k, 1) = ab(i, k, 1) + y1hatb
        ab(i, k, 0) = ab(i, k, 0) + x1hatb
        ab(i, kp, 0) = ab(i, kp, 0) - x1hatb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 1, 0)
    ab(i, 0, 1) = ab(i, 0, 1) - bb(i, 1, 0)
    bb(i, 1, 0) = 0.D0
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
    ab(i, 0, 1) = ab(i, 0, 1) + bb(i, 0, 0)
    bb(i, 0, 0) = 0.D0
  END DO
END SUBROUTINE C06FQW_B
