!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqf in reverse (adjoint) mode:
!   gradient     of useful results: x work
!   with respect to varying inputs: x work
SUBROUTINE C06FQF_B(m, n, x, xb, init, trig, work, workb, ifail)
  IMPLICIT NONE
!VD$R NOVECTOR
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     .. Parameters ..
  CHARACTER(len=6) :: srname
  PARAMETER (srname='C06FQF')
!     .. Scalar Arguments ..
  INTEGER :: ifail, m, n
  CHARACTER(len=1) :: init
!     .. Array Arguments ..
  DOUBLE PRECISION :: trig(2*n), work(m*n), x(m*n)
  DOUBLE PRECISION :: workb(m*n), xb(m*n)
!     .. Local Scalars ..
  INTEGER :: ierror, nq, nrec
!     .. Local Arrays ..
  INTEGER :: q(30)
  CHARACTER(len=80) :: rec(1)
  EXTERNAL P01ABF
!     .. External Functions ..
  INTEGER :: P01ABF
!     .. External Subroutines ..
  EXTERNAL C06FPQ, C06FQX
  EXTERNAL C06FQX_B
!     .. Executable Statements ..
  CALL C06FPQ(m, n, init, trig, q, nq, ierror)
  IF (ierror .EQ. 0) CALL C06FQX_B(x, xb, work, workb, m, n, q, nq, trig&
&                           )
!
99999 FORMAT(' ** M must be at least 1: M = ',i16)
99998 FORMAT(' ** N must be at least 1: N = ',i16)
99997 FORMAT(' ** ',a1,' is an invalid value of INIT')
99996 FORMAT(' ** INIT = ',a1,', but TRIG array never initialized')
99995 FORMAT(' ** INIT = ',a1,', but N and TRIG array incompatible')
END SUBROUTINE C06FQF_B
