!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpw in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FPW_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-698 (DEC 1989).
!
!     Radix two Real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:1, 0:r-1), b(0:p-1, 0:r-1, 0:1), cosine&
& (0:r-1), sine(0:r-1)
  DOUBLE PRECISION :: ab(0:p-1, 0:1, 0:r-1), bb(0:p-1, 0:r-1, 0:1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: ck, sk, x1, y1
  DOUBLE PRECISION :: x1b, y1b
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!
!     Code for general K
!
  IF (p .LT. (r-1)/2) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        ab(i, 0, r-k) = ab(i, 0, r-k) + bb(i, r-k, 1)
        y1b = bb(i, r-k, 1)
        bb(i, r-k, 1) = 0.D0
        y1b = y1b + bb(i, k, 1)
        ab(i, 0, r-k) = ab(i, 0, r-k) - bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, r-k, 0)
        x1b = -bb(i, r-k, 0)
        bb(i, r-k, 0) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        x1b = x1b + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
        ab(i, 1, r-k) = ab(i, 1, r-k) + cosine(k)*y1b
        ab(i, 1, k) = ab(i, 1, k) + cosine(k)*x1b + sine(k)*y1b
        ab(i, 1, r-k) = ab(i, 1, r-k) - sine(k)*x1b
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      kp = r - k
      sk = sine(k)
      ck = cosine(k)
      DO i=p-1,0,-1
        ab(i, 0, kp) = ab(i, 0, kp) + bb(i, kp, 1)
        y1b = bb(i, kp, 1)
        bb(i, kp, 1) = 0.D0
        y1b = y1b + bb(i, k, 1)
        ab(i, 0, kp) = ab(i, 0, kp) - bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, kp, 0)
        x1b = -bb(i, kp, 0)
        bb(i, kp, 0) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        x1b = x1b + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
        ab(i, 1, kp) = ab(i, 1, kp) + ck*y1b
        ab(i, 1, k) = ab(i, 1, k) + ck*x1b + sk*y1b
        ab(i, 1, kp) = ab(i, 1, kp) - sk*x1b
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 1)
    ab(i, 1, 0) = ab(i, 1, 0) - bb(i, 0, 1)
    bb(i, 0, 1) = 0.D0
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
    ab(i, 1, 0) = ab(i, 1, 0) + bb(i, 0, 0)
    bb(i, 0, 0) = 0.D0
  END DO
END SUBROUTINE C06FPW_B
