!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqr in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FQR_B(a, ab, b, bb, p, q, r, cosine, sine)
  IMPLICIT NONE
!     MARK 15 RE-ISSUE. NAG COPYRIGHT 1991.
!
!     Hermitian to real fast Fourier transform kernel
!     Odd factors greater than 6
!
!     Self-sorting, decimation in frequency
!
!     .. Scalar Arguments ..
  INTEGER :: p, q, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:q-1), b(0:p-1, 0:q-1, 0:r-1), &
& cosine(0:r-1, q-1), sine(0:r-1, q-1)
  DOUBLE PRECISION :: ab(0:p-1, 0:r-1, 0:q-1), bb(0:p-1, 0:q-1, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: bi, br, temp, temp1, tempi, tempr
  DOUBLE PRECISION :: bib, brb, tempb, temp1b, tempib, temprb
  INTEGER :: i, indx, j, k, kp, l, q2, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
  DOUBLE PRECISION :: tmp
  DOUBLE PRECISION :: tmpb
  DOUBLE PRECISION :: tmp0
  DOUBLE PRECISION :: tmp1
  DOUBLE PRECISION :: tmp2
  DOUBLE PRECISION :: tmpb0
  DOUBLE PRECISION :: tmpb1
  DOUBLE PRECISION :: tmpb2
  DOUBLE PRECISION :: tmp3
  DOUBLE PRECISION :: tmpb3
  DOUBLE PRECISION :: tmp4
  DOUBLE PRECISION :: tmp5
  DOUBLE PRECISION :: tmp6
  DOUBLE PRECISION :: tmpb4
  DOUBLE PRECISION :: tmpb5
  DOUBLE PRECISION :: tmpb6
  INTEGER :: branch
!     .. Executable Statements ..
!
  q2 = (q-1)/2
  IF (p .GE. r/2) THEN
!
!        Code for K=0 --
!
    DO l=1,q2
      DO j=1,q2
        CALL PUSHINTEGER4(indx)
        indx = MOD(j*l, q)
      END DO
    END DO
!
!        Code for general K --
!
    DO k=1,(r-1)/2
      DO l=1,q2
        DO j=1,q2
          CALL PUSHINTEGER4(indx)
          indx = MOD(j*l, q)
        END DO
      END DO
    END DO
!
!        Code for K=R/2 when R is even --
!
    IF (MOD(r, 2) .EQ. 0) THEN
      r2 = r/2
      DO l=1,q2
        DO j=0,q2-1
          CALL PUSHINTEGER4(indx)
          indx = MOD(l*(j+q2+1), q)
        END DO
      END DO
      IF (MOD(q2, 2) .EQ. 1) THEN
        DO i=p-1,0,-1
          temprb = bb(i, q2+1, r2)
          tempib = bb(i, q2+1, r2)
          bb(i, q2+1, r2) = 0.D0
          tempib = tempib + bb(i, q2, r2)
          temprb = temprb - bb(i, q2, r2)
          bb(i, q2, r2) = 0.D0
          bb(i, q2+1, r2) = bb(i, q2+1, r2) + tempib
          bb(i, q2, r2) = bb(i, q2, r2) + temprb
        END DO
      END IF
      DO j=q2-MOD(q2-2, 2)-1,1,-2
        DO i=p-1,0,-1
          temprb = -bb(i, q-j-1, r2)
          tempib = -bb(i, q-j-1, r2)
          bb(i, q-j-1, r2) = 0.D0
          temprb = temprb + bb(i, j+1, r2)
          tempib = tempib - bb(i, j+1, r2)
          bb(i, j+1, r2) = 0.D0
          bb(i, q-j-1, r2) = bb(i, q-j-1, r2) + tempib
          bb(i, j+1, r2) = bb(i, j+1, r2) + temprb
          temprb = bb(i, q-j, r2)
          tempib = bb(i, q-j, r2)
          bb(i, q-j, r2) = 0.D0
          tempib = tempib + bb(i, j, r2)
          temprb = temprb - bb(i, j, r2)
          bb(i, j, r2) = 0.D0
          bb(i, q-j, r2) = bb(i, q-j, r2) + tempib
          bb(i, j, r2) = bb(i, j, r2) + temprb
        END DO
      END DO
      DO j=q2-1,0,-1
        DO i=p-1,0,-1
          ab(i, r2, j) = ab(i, r2, j) + bb(i, 0, r2)
        END DO
      END DO
      DO i=p-1,0,-1
        ab(i, r2, q2) = ab(i, r2, q2) + bb(i, 0, r2)
        bb(i, 0, r2) = 0.D0
      END DO
      DO l=q2,1,-1
        DO j=q2-1,0,-1
          DO i=p-1,0,-1
            ab(i, r2, q-j-1) = ab(i, r2, q-j-1) + sine(0, indx)*bb(i, q-&
&             l, r2)
            ab(i, r2, j) = ab(i, r2, j) + cosine(0, indx)*bb(i, l, r2)
          END DO
          CALL POPINTEGER4(indx)
        END DO
      END DO
      DO l=q2,1,-1
        DO i=p-1,0,-1
          bb(i, q-l, r2) = 0.D0
          ab(i, r2, q2) = ab(i, r2, q2) + bb(i, l, r2)
          bb(i, l, r2) = 0.D0
        END DO
      END DO
    END IF
    DO k=(r-1)/2,1,-1
      kp = r - k
      DO j=q-1,1,-1
        DO i=p-1,0,-1
          bib = cosine(k, j)*bb(i, j, kp)
          brb = sine(k, j)*bb(i, j, kp)
          bb(i, j, kp) = 0.D0
          brb = brb + cosine(k, j)*bb(i, j, k)
          bib = bib - sine(k, j)*bb(i, j, k)
          bb(i, j, k) = 0.D0
          bb(i, j, kp) = bb(i, j, kp) + bib
          bb(i, j, k) = bb(i, j, k) + brb
        END DO
      END DO
      DO j=q2,1,-1
        DO i=p-1,0,-1
          tempib = bb(i, q-j, kp)
          temp1b = -bb(i, q-j, kp)
          bb(i, q-j, kp) = 0.D0
          tmpb0 = bb(i, q-j, k)
          bb(i, q-j, k) = 0.D0
          bb(i, q-j, kp) = bb(i, q-j, kp) + tmpb0
          bb(i, q-j, k) = bb(i, q-j, k) + temp1b
          tmpb2 = bb(i, j, kp)
          bb(i, j, kp) = 0.D0
          tempib = tempib + tmpb2
          bb(i, q-j, k) = bb(i, q-j, k) + tmpb2
          tmpb1 = bb(i, j, k)
          temprb = tmpb1 + tmpb0
          bb(i, j, k) = 0.D0
          bb(i, q-j, kp) = bb(i, q-j, kp) - tmpb1
          bb(i, j, kp) = bb(i, j, kp) + tempib
          bb(i, j, k) = bb(i, j, k) + temprb
        END DO
      END DO
      DO j=q2,1,-1
        DO i=p-1,0,-1
          ab(i, kp, q-j-1) = ab(i, kp, q-j-1) + bb(i, 0, kp)
          ab(i, k, j) = ab(i, k, j) + bb(i, 0, k)
        END DO
      END DO
      DO i=p-1,0,-1
        ab(i, kp, q-1) = ab(i, kp, q-1) + bb(i, 0, kp)
        bb(i, 0, kp) = 0.D0
        ab(i, k, 0) = ab(i, k, 0) + bb(i, 0, k)
        bb(i, 0, k) = 0.D0
      END DO
      DO l=q2,1,-1
        DO j=q2,1,-1
          DO i=p-1,0,-1
            ab(i, k, q-j) = ab(i, k, q-j) - sine(0, indx)*bb(i, q-l, kp)
            ab(i, kp, j-1) = ab(i, kp, j-1) + sine(0, indx)*bb(i, q-l, k&
&             )
            ab(i, kp, q-j-1) = ab(i, kp, q-j-1) + cosine(0, indx)*bb(i, &
&             l, kp)
            ab(i, k, j) = ab(i, k, j) + cosine(0, indx)*bb(i, l, k)
          END DO
          CALL POPINTEGER4(indx)
        END DO
        DO i=p-1,0,-1
          bb(i, q-l, kp) = 0.D0
          bb(i, q-l, k) = 0.D0
          ab(i, kp, q-1) = ab(i, kp, q-1) + bb(i, l, kp)
          bb(i, l, kp) = 0.D0
          ab(i, k, 0) = ab(i, k, 0) + bb(i, l, k)
          bb(i, l, k) = 0.D0
        END DO
      END DO
      DO j=q2,1,-1
        DO i=p-1,0,-1
          tempib = -ab(i, k, q-j)
          ab(i, k, q-j) = -ab(i, k, q-j)
          temprb = ab(i, kp, j-1)
          ab(i, kp, j-1) = -ab(i, kp, j-1)
          tempib = tempib + ab(i, kp, q-j-1)
          ab(i, k, q-j) = ab(i, k, q-j) - ab(i, kp, q-j-1)
          ab(i, kp, q-j-1) = 0.D0
          temprb = temprb + ab(i, k, j)
          ab(i, kp, j-1) = ab(i, kp, j-1) + ab(i, k, j)
          ab(i, k, j) = 0.D0
          ab(i, kp, q-j-1) = ab(i, kp, q-j-1) + tempib
          ab(i, k, j) = ab(i, k, j) + temprb
        END DO
      END DO
    END DO
    DO j=q2,1,-1
      DO i=p-1,0,-1
        tempb = bb(i, q-j, 0)
        bb(i, q-j, 0) = -bb(i, q-j, 0)
        tmpb = bb(i, j, 0)
        bb(i, j, 0) = tmpb
        bb(i, q-j, 0) = bb(i, q-j, 0) + tmpb
        bb(i, j, 0) = bb(i, j, 0) + tempb
      END DO
    END DO
    DO j=q2,1,-1
      DO i=p-1,0,-1
        ab(i, 0, j) = ab(i, 0, j) + bb(i, 0, 0)
      END DO
    END DO
    DO i=p-1,0,-1
      ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
      bb(i, 0, 0) = 0.D0
    END DO
    DO l=q2,1,-1
      DO j=q2,1,-1
        DO i=p-1,0,-1
          ab(i, 0, q-j) = ab(i, 0, q-j) - sine(0, indx)*bb(i, q-l, 0)
          ab(i, 0, j) = ab(i, 0, j) + cosine(0, indx)*bb(i, l, 0)
        END DO
        CALL POPINTEGER4(indx)
      END DO
      DO i=p-1,0,-1
        bb(i, q-l, 0) = 0.D0
        ab(i, 0, 0) = ab(i, 0, 0) + bb(i, l, 0)
        bb(i, l, 0) = 0.D0
      END DO
    END DO
  ELSE
!
!
    DO i=0,p-1
!
!           Code for K=0 --
!
      DO l=1,q2
        DO j=1,q2
          CALL PUSHINTEGER4(indx)
          indx = MOD(j*l, q)
        END DO
      END DO
      DO l=1,q2
        DO j=1,q2
          CALL PUSHINTEGER4(indx)
          indx = MOD(j*l, q)
        END DO
      END DO
!
!           Code for K=R/2 when R is even --
!
      IF (MOD(r, 2) .EQ. 0) THEN
        CALL PUSHINTEGER4(r2)
        r2 = r/2
        DO l=1,q2
          DO j=0,q2-1
            CALL PUSHINTEGER4(indx)
            indx = MOD(l*(j+q2+1), q)
          END DO
        END DO
        IF (MOD(q2, 2) .EQ. 1) THEN
          CALL PUSHCONTROL2B(0)
        ELSE
          CALL PUSHCONTROL2B(1)
        END IF
      ELSE
        CALL PUSHCONTROL2B(2)
      END IF
    END DO
    DO i=p-1,0,-1
      CALL POPCONTROL2B(branch)
      IF (branch .EQ. 0) THEN
        r2 = r/2
        temprb = bb(i, q2+1, r2)
        tempib = bb(i, q2+1, r2)
        bb(i, q2+1, r2) = 0.D0
        tempib = tempib + bb(i, q2, r2)
        temprb = temprb - bb(i, q2, r2)
        bb(i, q2, r2) = 0.D0
        bb(i, q2+1, r2) = bb(i, q2+1, r2) + tempib
        bb(i, q2, r2) = bb(i, q2, r2) + temprb
      ELSE IF (branch .NE. 1) THEN
        GOTO 100
      END IF
      DO j=q2-MOD(q2-2, 2)-1,1,-2
        temprb = -bb(i, q-j-1, r2)
        tempib = -bb(i, q-j-1, r2)
        bb(i, q-j-1, r2) = 0.D0
        temprb = temprb + bb(i, j+1, r2)
        tempib = tempib - bb(i, j+1, r2)
        bb(i, j+1, r2) = 0.D0
        bb(i, q-j-1, r2) = bb(i, q-j-1, r2) + tempib
        bb(i, j+1, r2) = bb(i, j+1, r2) + temprb
        temprb = bb(i, q-j, r2)
        tempib = bb(i, q-j, r2)
        bb(i, q-j, r2) = 0.D0
        tempib = tempib + bb(i, j, r2)
        temprb = temprb - bb(i, j, r2)
        bb(i, j, r2) = 0.D0
        bb(i, q-j, r2) = bb(i, q-j, r2) + tempib
        bb(i, j, r2) = bb(i, j, r2) + temprb
      END DO
      DO j=q2-1,0,-1
        ab(i, r2, j) = ab(i, r2, j) + bb(i, 0, r2)
      END DO
      ab(i, r2, q2) = ab(i, r2, q2) + bb(i, 0, r2)
      bb(i, 0, r2) = 0.D0
      DO l=q2,1,-1
        DO j=q2-1,0,-1
          ab(i, r2, q-j-1) = ab(i, r2, q-j-1) + sine(0, indx)*bb(i, q-l&
&           , r2)
          ab(i, r2, j) = ab(i, r2, j) + cosine(0, indx)*bb(i, l, r2)
          CALL POPINTEGER4(indx)
        END DO
      END DO
      DO l=q2,1,-1
        bb(i, q-l, r2) = 0.D0
        ab(i, r2, q2) = ab(i, r2, q2) + bb(i, l, r2)
        bb(i, l, r2) = 0.D0
      END DO
      CALL POPINTEGER4(r2)
 100  DO j=q-1,1,-1
        DO k=(r-1)/2,1,-1
          bib = cosine(k, j)*bb(i, j, r-k)
          brb = sine(k, j)*bb(i, j, r-k)
          bb(i, j, r-k) = 0.D0
          brb = brb + cosine(k, j)*bb(i, j, k)
          bib = bib - sine(k, j)*bb(i, j, k)
          bb(i, j, k) = 0.D0
          bb(i, j, r-k) = bb(i, j, r-k) + bib
          bb(i, j, k) = bb(i, j, k) + brb
        END DO
      END DO
      DO j=q2,1,-1
        DO k=(r-1)/2,1,-1
          tempib = bb(i, q-j, r-k)
          temp1b = -bb(i, q-j, r-k)
          bb(i, q-j, r-k) = 0.D0
          tmpb4 = bb(i, q-j, k)
          bb(i, q-j, k) = 0.D0
          bb(i, q-j, r-k) = bb(i, q-j, r-k) + tmpb4
          bb(i, q-j, k) = bb(i, q-j, k) + temp1b
          tmpb6 = bb(i, j, r-k)
          bb(i, j, r-k) = 0.D0
          tempib = tempib + tmpb6
          bb(i, q-j, k) = bb(i, q-j, k) + tmpb6
          tmpb5 = bb(i, j, k)
          temprb = tmpb5 + tmpb4
          bb(i, j, k) = 0.D0
          bb(i, q-j, r-k) = bb(i, q-j, r-k) - tmpb5
          bb(i, j, r-k) = bb(i, j, r-k) + tempib
          bb(i, j, k) = bb(i, j, k) + temprb
        END DO
      END DO
      DO j=q2,1,-1
        DO k=(r-1)/2,1,-1
          ab(i, r-k, q-j-1) = ab(i, r-k, q-j-1) + bb(i, 0, r-k)
          ab(i, k, j) = ab(i, k, j) + bb(i, 0, k)
        END DO
      END DO
      DO k=(r-1)/2,1,-1
        ab(i, r-k, q-1) = ab(i, r-k, q-1) + bb(i, 0, r-k)
        bb(i, 0, r-k) = 0.D0
        ab(i, k, 0) = ab(i, k, 0) + bb(i, 0, k)
        bb(i, 0, k) = 0.D0
      END DO
      DO l=q2,1,-1
        DO j=q2,1,-1
          DO k=(r-1)/2,1,-1
            ab(i, k, q-j) = ab(i, k, q-j) - sine(0, indx)*bb(i, q-l, r-k&
&             )
            ab(i, r-k, j-1) = ab(i, r-k, j-1) + sine(0, indx)*bb(i, q-l&
&             , k)
            ab(i, r-k, q-j-1) = ab(i, r-k, q-j-1) + cosine(0, indx)*bb(i&
&             , l, r-k)
            ab(i, k, j) = ab(i, k, j) + cosine(0, indx)*bb(i, l, k)
          END DO
          CALL POPINTEGER4(indx)
        END DO
        DO k=(r-1)/2,1,-1
          bb(i, q-l, r-k) = 0.D0
          bb(i, q-l, k) = 0.D0
          ab(i, r-k, q-1) = ab(i, r-k, q-1) + bb(i, l, r-k)
          bb(i, l, r-k) = 0.D0
          ab(i, k, 0) = ab(i, k, 0) + bb(i, l, k)
          bb(i, l, k) = 0.D0
        END DO
      END DO
      DO j=q2,1,-1
        DO k=(r-1)/2,1,-1
          tempib = -ab(i, k, q-j)
          ab(i, k, q-j) = -ab(i, k, q-j)
          temprb = ab(i, r-k, j-1)
          ab(i, r-k, j-1) = -ab(i, r-k, j-1)
          tempib = tempib + ab(i, r-k, q-j-1)
          ab(i, k, q-j) = ab(i, k, q-j) - ab(i, r-k, q-j-1)
          ab(i, r-k, q-j-1) = 0.D0
          temprb = temprb + ab(i, k, j)
          ab(i, r-k, j-1) = ab(i, r-k, j-1) + ab(i, k, j)
          ab(i, k, j) = 0.D0
          ab(i, r-k, q-j-1) = ab(i, r-k, q-j-1) + tempib
          ab(i, k, j) = ab(i, k, j) + temprb
        END DO
      END DO
      DO j=q2,1,-1
        tempb = bb(i, q-j, 0)
        bb(i, q-j, 0) = -bb(i, q-j, 0)
        tmpb3 = bb(i, j, 0)
        bb(i, j, 0) = tmpb3
        bb(i, q-j, 0) = bb(i, q-j, 0) + tmpb3
        bb(i, j, 0) = bb(i, j, 0) + tempb
      END DO
      DO j=q2,1,-1
        ab(i, 0, j) = ab(i, 0, j) + bb(i, 0, 0)
      END DO
      ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
      bb(i, 0, 0) = 0.D0
      DO l=q2,1,-1
        DO j=q2,1,-1
          ab(i, 0, q-j) = ab(i, 0, q-j) - sine(0, indx)*bb(i, q-l, 0)
          ab(i, 0, j) = ab(i, 0, j) + cosine(0, indx)*bb(i, l, 0)
          CALL POPINTEGER4(indx)
        END DO
        bb(i, q-l, 0) = 0.D0
        ab(i, 0, 0) = ab(i, 0, 0) + bb(i, l, 0)
        bb(i, l, 0) = 0.D0
      END DO
    END DO
  END IF
END SUBROUTINE C06FQR_B
