!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fps in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FPS_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-694 (DEC 1989).
!
!     Radix six real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:5, 0:r-1), b(0:p-1, 0:r-1, 0:5), cosine&
& (0:r-1, 5), sine(0:r-1, 5)
  DOUBLE PRECISION :: ab(0:p-1, 0:5, 0:r-1), bb(0:p-1, 0:r-1, 0:5)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, c4k, c5k, ck, s2k, s3k, s4k, s5k, sk, t1&
& , t1i, t1r, t2, t2i, t2r, t3, t3i, t3r, t4, t5, t6, u0, u0i, u0r, u1i&
& , u1r, u2i, u2r, ui, ur, v0, v0i, v0r, v1i, v1r, v2i, v2r, vi, vr, x1p&
& , x2p, x3p, x4p, x5p, y1p, y2p, y3p, y4p, y5p
  DOUBLE PRECISION :: t1b, t1ib, t1rb, t2b, t2ib, t2rb, t3b, t3ib, t3rb&
& , t4b, t5b, t6b, u0b, u0ib, u0rb, u1ib, u1rb, u2ib, u2rb, uib, urb, &
& v0b, v0ib, v0rb, v1ib, v1rb, v2ib, v2rb, vib, vrb, x1pb, x2pb, x3pb, &
& x4pb, x5pb, y1pb, y2pb, y3pb, y4pb, y5pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
  INTEGER :: branch
!
!     Code for general K --
!
  IF (p .LE. (r-1)/2) THEN
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=p-1,0,-1
      t5b = bb(i, r2, 5)
      t3b = -bb(i, r2, 5)
      bb(i, r2, 5) = 0.D0
      ab(i, 3, r2) = ab(i, 3, r2) + bb(i, r2, 4)
      t4b = -bb(i, r2, 4)
      bb(i, r2, 4) = 0.D0
      t5b = t5b + bb(i, r2, 3)
      t3b = t3b + bb(i, r2, 3)
      bb(i, r2, 3) = 0.D0
      t2b = bb(i, r2, 2)
      t6b = -bb(i, r2, 2)
      bb(i, r2, 2) = 0.D0
      ab(i, 0, r2) = ab(i, 0, r2) + bb(i, r2, 1)
      t1b = -bb(i, r2, 1)
      bb(i, r2, 1) = 0.D0
      t2b = t2b + bb(i, r2, 0)
      t6b = t6b + bb(i, r2, 0)
      bb(i, r2, 0) = 0.D0
      ab(i, 1, r2) = ab(i, 1, r2) + sin60*t6b
      ab(i, 5, r2) = ab(i, 5, r2) - sin60*t6b
      ab(i, 3, r2) = ab(i, 3, r2) - t5b
      t4b = t4b - 0.5d0*t5b
      ab(i, 1, r2) = ab(i, 1, r2) + t4b
      ab(i, 5, r2) = ab(i, 5, r2) + t4b
      ab(i, 2, r2) = ab(i, 2, r2) + sin60*t3b
      ab(i, 4, r2) = ab(i, 4, r2) + sin60*t3b
      ab(i, 0, r2) = ab(i, 0, r2) + t2b
      t1b = t1b + 0.5d0*t2b
      ab(i, 2, r2) = ab(i, 2, r2) + t1b
      ab(i, 4, r2) = ab(i, 4, r2) - t1b
    END DO
  END IF
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        u0ib = bb(i, r-k, 5)
        v0ib = bb(i, r-k, 5)
        bb(i, r-k, 5) = 0.D0
        v2ib = bb(i, k, 5)
        u2ib = -bb(i, k, 5)
        bb(i, k, 5) = 0.D0
        u1ib = bb(i, r-k, 4)
        v1ib = -bb(i, r-k, 4)
        bb(i, r-k, 4) = 0.D0
        u1ib = u1ib - bb(i, k, 4)
        v1ib = v1ib - bb(i, k, 4)
        bb(i, k, 4) = 0.D0
        u2ib = u2ib + bb(i, r-k, 3)
        v2ib = v2ib + bb(i, r-k, 3)
        bb(i, r-k, 3) = 0.D0
        v0ib = v0ib + bb(i, k, 3)
        u0ib = u0ib - bb(i, k, 3)
        bb(i, k, 3) = 0.D0
        u0rb = bb(i, r-k, 2)
        v0rb = -bb(i, r-k, 2)
        bb(i, r-k, 2) = 0.D0
        u2rb = bb(i, k, 2)
        v2rb = bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        u1rb = bb(i, r-k, 1)
        v1rb = bb(i, r-k, 1)
        bb(i, r-k, 1) = 0.D0
        u1rb = u1rb + bb(i, k, 1)
        v1rb = v1rb - bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        u2rb = u2rb + bb(i, r-k, 0)
        v2rb = v2rb - bb(i, r-k, 0)
        bb(i, r-k, 0) = 0.D0
        u0rb = u0rb + bb(i, k, 0)
        v0rb = v0rb + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
        t2ib = v1ib + v2ib
        t3rb = v2ib - v1ib
        t2rb = v1rb + v2rb
        t3ib = v1rb - v2rb
        y3pb = t2ib + v0ib
        t1ib = v0ib - 0.5d0*t2ib
        x3pb = t2rb + v0rb
        t1rb = v0rb - 0.5d0*t2rb
        y5pb = t1ib + sin60*t3ib
        y1pb = t1ib - sin60*t3ib
        x5pb = t1rb + sin60*t3rb
        x1pb = t1rb - sin60*t3rb
        t2ib = u1ib + u2ib
        t3rb = u2ib - u1ib
        t2rb = u1rb + u2rb
        t3ib = u1rb - u2rb
        ab(i, 0, r-k) = ab(i, 0, r-k) + u0ib
        t1ib = u0ib - 0.5d0*t2ib
        ab(i, 0, k) = ab(i, 0, k) + u0rb
        t1rb = u0rb - 0.5d0*t2rb
        y2pb = t1ib + sin60*t3ib
        y4pb = t1ib - sin60*t3ib
        x2pb = t1rb + sin60*t3rb
        x4pb = t1rb - sin60*t3rb
        ab(i, 0, r-k) = ab(i, 0, r-k) + t2ib
        ab(i, 0, k) = ab(i, 0, k) + t2rb
        ab(i, 5, r-k) = ab(i, 5, r-k) + cosine(k, 5)*y5pb
        ab(i, 5, k) = ab(i, 5, k) + cosine(k, 5)*x5pb + sine(k, 5)*y5pb
        ab(i, 5, r-k) = ab(i, 5, r-k) - sine(k, 5)*x5pb
        ab(i, 4, r-k) = ab(i, 4, r-k) + cosine(k, 4)*y4pb
        ab(i, 4, k) = ab(i, 4, k) + cosine(k, 4)*x4pb + sine(k, 4)*y4pb
        ab(i, 4, r-k) = ab(i, 4, r-k) - sine(k, 4)*x4pb
        ab(i, 3, r-k) = ab(i, 3, r-k) + cosine(k, 3)*y3pb
        ab(i, 3, k) = ab(i, 3, k) + cosine(k, 3)*x3pb + sine(k, 3)*y3pb
        ab(i, 3, r-k) = ab(i, 3, r-k) - sine(k, 3)*x3pb
        ab(i, 2, r-k) = ab(i, 2, r-k) + cosine(k, 2)*y2pb
        ab(i, 2, k) = ab(i, 2, k) + cosine(k, 2)*x2pb + sine(k, 2)*y2pb
        ab(i, 2, r-k) = ab(i, 2, r-k) - sine(k, 2)*x2pb
        ab(i, 1, r-k) = ab(i, 1, r-k) + cosine(k, 1)*y1pb
        ab(i, 1, k) = ab(i, 1, k) + cosine(k, 1)*x1pb + sine(k, 1)*y1pb
        ab(i, 1, r-k) = ab(i, 1, r-k) - sine(k, 1)*x1pb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      s3k = sine(k, 3)
      c3k = cosine(k, 3)
      kp = r - k
      s4k = sine(k, 4)
      c4k = cosine(k, 4)
      s5k = sine(k, 5)
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c5k = cosine(k, 5)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        u0ib = bb(i, kp, 5)
        v0ib = bb(i, kp, 5)
        bb(i, kp, 5) = 0.D0
        v2ib = bb(i, k, 5)
        u2ib = -bb(i, k, 5)
        bb(i, k, 5) = 0.D0
        u1ib = bb(i, kp, 4)
        v1ib = -bb(i, kp, 4)
        bb(i, kp, 4) = 0.D0
        u1ib = u1ib - bb(i, k, 4)
        v1ib = v1ib - bb(i, k, 4)
        bb(i, k, 4) = 0.D0
        u2ib = u2ib + bb(i, kp, 3)
        v2ib = v2ib + bb(i, kp, 3)
        bb(i, kp, 3) = 0.D0
        v0ib = v0ib + bb(i, k, 3)
        u0ib = u0ib - bb(i, k, 3)
        bb(i, k, 3) = 0.D0
        u0rb = bb(i, kp, 2)
        v0rb = -bb(i, kp, 2)
        bb(i, kp, 2) = 0.D0
        u2rb = bb(i, k, 2)
        v2rb = bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        u1rb = bb(i, kp, 1)
        v1rb = bb(i, kp, 1)
        bb(i, kp, 1) = 0.D0
        u1rb = u1rb + bb(i, k, 1)
        v1rb = v1rb - bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        u2rb = u2rb + bb(i, kp, 0)
        v2rb = v2rb - bb(i, kp, 0)
        bb(i, kp, 0) = 0.D0
        u0rb = u0rb + bb(i, k, 0)
        v0rb = v0rb + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
        t2ib = v1ib + v2ib
        t3rb = v2ib - v1ib
        t2rb = v1rb + v2rb
        t3ib = v1rb - v2rb
        y3pb = t2ib + v0ib
        t1ib = v0ib - 0.5d0*t2ib
        x3pb = t2rb + v0rb
        t1rb = v0rb - 0.5d0*t2rb
        y5pb = t1ib + sin60*t3ib
        y1pb = t1ib - sin60*t3ib
        x5pb = t1rb + sin60*t3rb
        x1pb = t1rb - sin60*t3rb
        t2ib = u1ib + u2ib
        t3rb = u2ib - u1ib
        t2rb = u1rb + u2rb
        t3ib = u1rb - u2rb
        ab(i, 0, kp) = ab(i, 0, kp) + u0ib
        t1ib = u0ib - 0.5d0*t2ib
        ab(i, 0, k) = ab(i, 0, k) + u0rb
        t1rb = u0rb - 0.5d0*t2rb
        y2pb = t1ib + sin60*t3ib
        y4pb = t1ib - sin60*t3ib
        x2pb = t1rb + sin60*t3rb
        x4pb = t1rb - sin60*t3rb
        ab(i, 0, kp) = ab(i, 0, kp) + t2ib
        ab(i, 0, k) = ab(i, 0, k) + t2rb
        ab(i, 5, kp) = ab(i, 5, kp) + c5k*y5pb
        ab(i, 5, k) = ab(i, 5, k) + c5k*x5pb + s5k*y5pb
        ab(i, 5, kp) = ab(i, 5, kp) - s5k*x5pb
        ab(i, 4, kp) = ab(i, 4, kp) + c4k*y4pb
        ab(i, 4, k) = ab(i, 4, k) + c4k*x4pb + s4k*y4pb
        ab(i, 4, kp) = ab(i, 4, kp) - s4k*x4pb
        ab(i, 3, kp) = ab(i, 3, kp) + c3k*y3pb
        ab(i, 3, k) = ab(i, 3, k) + c3k*x3pb + s3k*y3pb
        ab(i, 3, kp) = ab(i, 3, kp) - s3k*x3pb
        ab(i, 2, kp) = ab(i, 2, kp) + c2k*y2pb
        ab(i, 2, k) = ab(i, 2, k) + c2k*x2pb + s2k*y2pb
        ab(i, 2, kp) = ab(i, 2, kp) - s2k*x2pb
        ab(i, 1, kp) = ab(i, 1, kp) + ck*y1pb
        ab(i, 1, k) = ab(i, 1, k) + ck*x1pb + sk*y1pb
        ab(i, 1, kp) = ab(i, 1, kp) - sk*x1pb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    uib = bb(i, 0, 5)
    vib = -bb(i, 0, 5)
    bb(i, 0, 5) = 0.D0
    uib = uib - bb(i, 0, 4)
    vib = vib - bb(i, 0, 4)
    bb(i, 0, 4) = 0.D0
    u0b = bb(i, 0, 3)
    v0b = -bb(i, 0, 3)
    bb(i, 0, 3) = 0.D0
    urb = bb(i, 0, 2)
    vrb = bb(i, 0, 2)
    bb(i, 0, 2) = 0.D0
    urb = urb + bb(i, 0, 1)
    vrb = vrb - bb(i, 0, 1)
    bb(i, 0, 1) = 0.D0
    u0b = u0b + bb(i, 0, 0)
    v0b = v0b + bb(i, 0, 0)
    bb(i, 0, 0) = 0.D0
    ab(i, 3, 0) = ab(i, 3, 0) + v0b
    t1b = v0b - 0.5d0*vrb
    ab(i, 5, 0) = ab(i, 5, 0) - sin60*vib
    ab(i, 1, 0) = ab(i, 1, 0) + sin60*vib
    ab(i, 3, 0) = ab(i, 3, 0) + vrb
    ab(i, 5, 0) = ab(i, 5, 0) + t1b
    ab(i, 1, 0) = ab(i, 1, 0) + t1b
    ab(i, 0, 0) = ab(i, 0, 0) + u0b
    t1b = u0b - 0.5d0*urb
    ab(i, 2, 0) = ab(i, 2, 0) - sin60*uib
    ab(i, 4, 0) = ab(i, 4, 0) + sin60*uib
    ab(i, 0, 0) = ab(i, 0, 0) + urb
    ab(i, 2, 0) = ab(i, 2, 0) + t1b
    ab(i, 4, 0) = ab(i, 4, 0) + t1b
  END DO
END SUBROUTINE C06FPS_B
