!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqv in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FQV_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-702 (DEC 1989).
!
!     Radix three Hermitian to real Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:2), b(0:p-1, 0:2, 0:r-1), cosine&
& (0:r-1, 2), sine(0:r-1, 2)
  DOUBLE PRECISION :: ab(0:p-1, 0:r-1, 0:2), bb(0:p-1, 0:2, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, ck, s2k, sk, t1, t1i, t1r, t2, t2i, t2r, t3, &
& t3i, t3r, x0p, x1p, x2p, y0p, y1p, y2p
  DOUBLE PRECISION :: t1b, t1ib, t1rb, t2b, t2ib, t2rb, t3b, t3ib, t3rb&
& , x0pb, x1pb, x2pb, y0pb, y1pb, y2pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!
!     Code for general K
!
  IF (p .LE. (r-1)/2) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        x2pb = sine(k, 2)*bb(i, 2, r-k)
        y2pb = cosine(k, 2)*bb(i, 2, r-k)
        bb(i, 2, r-k) = 0.D0
        x2pb = x2pb + cosine(k, 2)*bb(i, 2, k)
        y2pb = y2pb - sine(k, 2)*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        x1pb = sine(k, 1)*bb(i, 1, r-k)
        y1pb = cosine(k, 1)*bb(i, 1, r-k)
        bb(i, 1, r-k) = 0.D0
        x1pb = x1pb + cosine(k, 1)*bb(i, 1, k)
        y1pb = y1pb - sine(k, 1)*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, r-k)
        bb(i, 0, r-k) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        t2ib = y1pb + y2pb
        t3rb = y2pb - y1pb
        t2rb = x1pb + x2pb
        t3ib = x1pb - x2pb
        ab(i, r-k, 2) = ab(i, r-k, 2) + y0pb
        t1ib = y0pb - 0.5d0*t2ib
        ab(i, k, 0) = ab(i, k, 0) + x0pb
        t1rb = x0pb - 0.5d0*t2rb
        ab(i, r-k, 1) = ab(i, r-k, 1) + sin60*t3ib
        ab(i, k, 2) = ab(i, k, 2) + sin60*t3ib
        ab(i, k, 1) = ab(i, k, 1) + sin60*t3rb
        ab(i, r-k, 0) = ab(i, r-k, 0) - sin60*t3rb
        ab(i, r-k, 2) = ab(i, r-k, 2) + t2ib
        ab(i, k, 0) = ab(i, k, 0) + t2rb
        ab(i, r-k, 1) = ab(i, r-k, 1) + t1ib
        ab(i, k, 2) = ab(i, k, 2) - t1ib
        ab(i, k, 1) = ab(i, k, 1) + t1rb
        ab(i, r-k, 0) = ab(i, r-k, 0) + t1rb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      kp = r - k
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        x2pb = s2k*bb(i, 2, kp)
        y2pb = c2k*bb(i, 2, kp)
        bb(i, 2, kp) = 0.D0
        x2pb = x2pb + c2k*bb(i, 2, k)
        y2pb = y2pb - s2k*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        x1pb = sk*bb(i, 1, kp)
        y1pb = ck*bb(i, 1, kp)
        bb(i, 1, kp) = 0.D0
        x1pb = x1pb + ck*bb(i, 1, k)
        y1pb = y1pb - sk*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, kp)
        bb(i, 0, kp) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        t2ib = y1pb + y2pb
        t3rb = y2pb - y1pb
        t2rb = x1pb + x2pb
        t3ib = x1pb - x2pb
        ab(i, kp, 2) = ab(i, kp, 2) + y0pb
        t1ib = y0pb - 0.5d0*t2ib
        ab(i, k, 0) = ab(i, k, 0) + x0pb
        t1rb = x0pb - 0.5d0*t2rb
        ab(i, kp, 1) = ab(i, kp, 1) + sin60*t3ib
        ab(i, k, 2) = ab(i, k, 2) + sin60*t3ib
        ab(i, k, 1) = ab(i, k, 1) + sin60*t3rb
        ab(i, kp, 0) = ab(i, kp, 0) - sin60*t3rb
        ab(i, kp, 2) = ab(i, kp, 2) + t2ib
        ab(i, k, 0) = ab(i, k, 0) + t2rb
        ab(i, kp, 1) = ab(i, kp, 1) + t1ib
        ab(i, k, 2) = ab(i, k, 2) - t1ib
        ab(i, k, 1) = ab(i, k, 1) + t1rb
        ab(i, kp, 0) = ab(i, kp, 0) + t1rb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    t2b = bb(i, 2, 0)
    t3b = -bb(i, 2, 0)
    bb(i, 2, 0) = 0.D0
    t2b = t2b + bb(i, 1, 0)
    t3b = t3b + bb(i, 1, 0)
    bb(i, 1, 0) = 0.D0
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
    t1b = bb(i, 0, 0) - 0.5d0*t2b
    bb(i, 0, 0) = 0.D0
    ab(i, 0, 2) = ab(i, 0, 2) + sin60*t3b
    ab(i, 0, 0) = ab(i, 0, 0) + t2b
    ab(i, 0, 1) = ab(i, 0, 1) + t1b
  END DO
END SUBROUTINE C06FQV_B
