!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpv in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FPV_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-697 (DEC 1989).
!
!     Radix three Real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:2, 0:r-1), b(0:p-1, 0:r-1, 0:2), cosine&
& (0:r-1, 2), sine(0:r-1, 2)
  DOUBLE PRECISION :: ab(0:p-1, 0:2, 0:r-1), bb(0:p-1, 0:r-1, 0:2)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, ck, s2k, sk, t1, t1i, t1r, t2i, t2r, t3i, t3r&
& , x1p, x2p, y1p, y2p
  DOUBLE PRECISION :: t1b, t1ib, t1rb, t2ib, t2rb, t3ib, t3rb, x1pb, &
& x2pb, y1pb, y2pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!
!     Code for general K
!
  IF (p .LE. (r-1)/2) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        ab(i, 0, r-k) = ab(i, 0, r-k) + bb(i, r-k, 2)
        t1ib = bb(i, r-k, 2)
        bb(i, r-k, 2) = 0.D0
        t2ib = -bb(i, k, 2)
        t3rb = -bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        t2ib = t2ib + bb(i, r-k, 1)
        t3rb = t3rb - bb(i, r-k, 1)
        bb(i, r-k, 1) = 0.D0
        t2rb = bb(i, k, 1)
        t3ib = bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        t2rb = t2rb + bb(i, r-k, 0)
        t3ib = t3ib - bb(i, r-k, 0)
        bb(i, r-k, 0) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        t1rb = bb(i, k, 0) - 0.5d0*t2rb
        bb(i, k, 0) = 0.D0
        x1pb = t1rb + sin60*t3rb
        x2pb = t1rb - sin60*t3rb
        ab(i, 0, r-k) = ab(i, 0, r-k) + t2ib
        t1ib = t1ib - 0.5d0*t2ib
        y1pb = t1ib + sin60*t3ib
        y2pb = t1ib - sin60*t3ib
        ab(i, 0, k) = ab(i, 0, k) + t2rb
        ab(i, 2, r-k) = ab(i, 2, r-k) + cosine(k, 2)*y2pb
        ab(i, 2, k) = ab(i, 2, k) + cosine(k, 2)*x2pb + sine(k, 2)*y2pb
        ab(i, 2, r-k) = ab(i, 2, r-k) - sine(k, 2)*x2pb
        ab(i, 1, r-k) = ab(i, 1, r-k) + cosine(k, 1)*y1pb
        ab(i, 1, k) = ab(i, 1, k) + cosine(k, 1)*x1pb + sine(k, 1)*y1pb
        ab(i, 1, r-k) = ab(i, 1, r-k) - sine(k, 1)*x1pb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      kp = r - k
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        ab(i, 0, kp) = ab(i, 0, kp) + bb(i, kp, 2)
        t1ib = bb(i, kp, 2)
        bb(i, kp, 2) = 0.D0
        t2ib = -bb(i, k, 2)
        t3rb = -bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        t2ib = t2ib + bb(i, kp, 1)
        t3rb = t3rb - bb(i, kp, 1)
        bb(i, kp, 1) = 0.D0
        t2rb = bb(i, k, 1)
        t3ib = bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        t2rb = t2rb + bb(i, kp, 0)
        t3ib = t3ib - bb(i, kp, 0)
        bb(i, kp, 0) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        t1rb = bb(i, k, 0) - 0.5d0*t2rb
        bb(i, k, 0) = 0.D0
        x1pb = t1rb + sin60*t3rb
        x2pb = t1rb - sin60*t3rb
        ab(i, 0, kp) = ab(i, 0, kp) + t2ib
        t1ib = t1ib - 0.5d0*t2ib
        y1pb = t1ib + sin60*t3ib
        y2pb = t1ib - sin60*t3ib
        ab(i, 0, k) = ab(i, 0, k) + t2rb
        ab(i, 2, kp) = ab(i, 2, kp) + c2k*y2pb
        ab(i, 2, k) = ab(i, 2, k) + c2k*x2pb + s2k*y2pb
        ab(i, 2, kp) = ab(i, 2, kp) - s2k*x2pb
        ab(i, 1, kp) = ab(i, 1, kp) + ck*y1pb
        ab(i, 1, k) = ab(i, 1, k) + ck*x1pb + sk*y1pb
        ab(i, 1, kp) = ab(i, 1, kp) - sk*x1pb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    ab(i, 1, 0) = ab(i, 1, 0) - sin60*bb(i, 0, 2)
    ab(i, 2, 0) = ab(i, 2, 0) + sin60*bb(i, 0, 2)
    bb(i, 0, 2) = 0.D0
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 1)
    t1b = -(0.5d0*bb(i, 0, 1))
    bb(i, 0, 1) = 0.D0
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
    t1b = t1b + bb(i, 0, 0)
    bb(i, 0, 0) = 0.D0
    ab(i, 1, 0) = ab(i, 1, 0) + t1b
    ab(i, 2, 0) = ab(i, 2, 0) + t1b
  END DO
END SUBROUTINE C06FPV_B
