!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqt in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FQT_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-700 (DEC 1989).
!
!     Radix five Hermitian to real fast Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Parameters ..
  DOUBLE PRECISION :: r54, sin36, sin72, s36s72
  PARAMETER (r54=0.559016994374947424102293417182819d0, sin36=&
&   0.587785252292473129168705954639073d0, sin72=&
&   0.951056516295153572116439333379382d0, s36s72=&
&   0.618033988749894848204586834365638d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:4), b(0:p-1, 0:4, 0:r-1), cosine&
& (0:r-1, 4), sine(0:r-1, 4)
  DOUBLE PRECISION :: ab(0:p-1, 0:r-1, 0:4), bb(0:p-1, 0:4, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, c4k, ck, s2k, s3k, s4k, sk, t1, t10, &
& t10i, t10r, t11, t11i, t11r, t1i, t1r, t2, t2i, t2r, t3, t3i, t3r, t4&
& , t4i, t4r, t5, t5i, t5r, t6, t6i, t6r, t7, t7i, t7r, t8, t8i, t8r, t9&
& , t9i, t9r, x0p, x1p, x2p, x3p, x4p, y0p, y1p, y2p, y3p, y4p
  DOUBLE PRECISION :: t1b, t10b, t10ib, t10rb, t11b, t11ib, t11rb, t1ib&
& , t1rb, t2b, t2ib, t2rb, t3b, t3ib, t3rb, t4b, t4ib, t4rb, t5b, t5ib, &
& t5rb, t6b, t6ib, t6rb, t7b, t7ib, t7rb, t8b, t8ib, t8rb, t9b, t9ib, &
& t9rb, x0pb, x1pb, x2pb, x3pb, x4pb, y0pb, y1pb, y2pb, y3pb, y4pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!
!     Code for general K --
!
  IF (p .LE. (r-1)/2) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        y4pb = cosine(k, 4)*bb(i, 4, r-k)
        x4pb = sine(k, 4)*bb(i, 4, r-k)
        bb(i, 4, r-k) = 0.D0
        x4pb = x4pb + cosine(k, 4)*bb(i, 4, k)
        y4pb = y4pb - sine(k, 4)*bb(i, 4, k)
        bb(i, 4, k) = 0.D0
        y3pb = cosine(k, 3)*bb(i, 3, r-k)
        x3pb = sine(k, 3)*bb(i, 3, r-k)
        bb(i, 3, r-k) = 0.D0
        x3pb = x3pb + cosine(k, 3)*bb(i, 3, k)
        y3pb = y3pb - sine(k, 3)*bb(i, 3, k)
        bb(i, 3, k) = 0.D0
        y2pb = cosine(k, 2)*bb(i, 2, r-k)
        x2pb = sine(k, 2)*bb(i, 2, r-k)
        bb(i, 2, r-k) = 0.D0
        x2pb = x2pb + cosine(k, 2)*bb(i, 2, k)
        y2pb = y2pb - sine(k, 2)*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        y1pb = cosine(k, 1)*bb(i, 1, r-k)
        x1pb = sine(k, 1)*bb(i, 1, r-k)
        bb(i, 1, r-k) = 0.D0
        x1pb = x1pb + cosine(k, 1)*bb(i, 1, k)
        y1pb = y1pb - sine(k, 1)*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, r-k)
        bb(i, 0, r-k) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        t8ib = y1pb + y4pb
        t10rb = y4pb - y1pb
        t8rb = x1pb + x4pb
        t10ib = x1pb - x4pb
        t9ib = y2pb + y3pb
        t11rb = y3pb - y2pb
        t9rb = x2pb + x3pb
        t11ib = x2pb - x3pb
        ab(i, r-k, 4) = ab(i, r-k, 4) + y0pb
        ab(i, k, 0) = ab(i, k, 0) + x0pb
        t3ib = t10ib + s36s72*t11ib
        t4ib = s36s72*t10ib - t11ib
        t3rb = t10rb + s36s72*t11rb
        t4rb = s36s72*t10rb - t11rb
        t7ib = t8ib + t9ib
        t5ib = y0pb - 0.25d0*t7ib
        t6ib = t8ib - t9ib
        t7rb = t8rb + t9rb
        t5rb = x0pb - 0.25d0*t7rb
        t6rb = t8rb - t9rb
        ab(i, r-k, 4) = ab(i, r-k, 4) + t7ib
        ab(i, k, 0) = ab(i, k, 0) + t7rb
        t1ib = t5ib + r54*t6ib
        t2ib = t5ib - r54*t6ib
        t1rb = t5rb + r54*t6rb
        t2rb = t5rb - r54*t6rb
        ab(i, r-k, 2) = ab(i, r-k, 2) + sin72*t4ib
        ab(i, k, 3) = ab(i, k, 3) + sin72*t4ib
        ab(i, k, 2) = ab(i, k, 2) + sin72*t4rb
        ab(i, r-k, 1) = ab(i, r-k, 1) - sin72*t4rb
        ab(i, r-k, 3) = ab(i, r-k, 3) + sin72*t3ib
        ab(i, k, 4) = ab(i, k, 4) + sin72*t3ib
        ab(i, k, 1) = ab(i, k, 1) + sin72*t3rb
        ab(i, r-k, 0) = ab(i, r-k, 0) - sin72*t3rb
        ab(i, r-k, 2) = ab(i, r-k, 2) + t2ib
        ab(i, k, 3) = ab(i, k, 3) - t2ib
        ab(i, k, 2) = ab(i, k, 2) + t2rb
        ab(i, r-k, 1) = ab(i, r-k, 1) + t2rb
        ab(i, r-k, 3) = ab(i, r-k, 3) + t1ib
        ab(i, k, 4) = ab(i, k, 4) - t1ib
        ab(i, k, 1) = ab(i, k, 1) + t1rb
        ab(i, r-k, 0) = ab(i, r-k, 0) + t1rb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      s3k = sine(k, 3)
      c3k = cosine(k, 3)
      kp = r - k
      s4k = sine(k, 4)
      c4k = cosine(k, 4)
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        y4pb = c4k*bb(i, 4, kp)
        x4pb = s4k*bb(i, 4, kp)
        bb(i, 4, kp) = 0.D0
        x4pb = x4pb + c4k*bb(i, 4, k)
        y4pb = y4pb - s4k*bb(i, 4, k)
        bb(i, 4, k) = 0.D0
        y3pb = c3k*bb(i, 3, kp)
        x3pb = s3k*bb(i, 3, kp)
        bb(i, 3, kp) = 0.D0
        x3pb = x3pb + c3k*bb(i, 3, k)
        y3pb = y3pb - s3k*bb(i, 3, k)
        bb(i, 3, k) = 0.D0
        y2pb = c2k*bb(i, 2, kp)
        x2pb = s2k*bb(i, 2, kp)
        bb(i, 2, kp) = 0.D0
        x2pb = x2pb + c2k*bb(i, 2, k)
        y2pb = y2pb - s2k*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        y1pb = ck*bb(i, 1, kp)
        x1pb = sk*bb(i, 1, kp)
        bb(i, 1, kp) = 0.D0
        x1pb = x1pb + ck*bb(i, 1, k)
        y1pb = y1pb - sk*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, kp)
        bb(i, 0, kp) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        t8ib = y1pb + y4pb
        t10rb = y4pb - y1pb
        t8rb = x1pb + x4pb
        t10ib = x1pb - x4pb
        t9ib = y2pb + y3pb
        t11rb = y3pb - y2pb
        t9rb = x2pb + x3pb
        t11ib = x2pb - x3pb
        ab(i, kp, 4) = ab(i, kp, 4) + y0pb
        ab(i, k, 0) = ab(i, k, 0) + x0pb
        t3ib = t10ib + s36s72*t11ib
        t4ib = s36s72*t10ib - t11ib
        t3rb = t10rb + s36s72*t11rb
        t4rb = s36s72*t10rb - t11rb
        t7ib = t8ib + t9ib
        t5ib = y0pb - 0.25d0*t7ib
        t6ib = t8ib - t9ib
        t7rb = t8rb + t9rb
        t5rb = x0pb - 0.25d0*t7rb
        t6rb = t8rb - t9rb
        ab(i, kp, 4) = ab(i, kp, 4) + t7ib
        ab(i, k, 0) = ab(i, k, 0) + t7rb
        t1ib = t5ib + r54*t6ib
        t2ib = t5ib - r54*t6ib
        t1rb = t5rb + r54*t6rb
        t2rb = t5rb - r54*t6rb
        ab(i, kp, 2) = ab(i, kp, 2) + sin72*t4ib
        ab(i, k, 3) = ab(i, k, 3) + sin72*t4ib
        ab(i, k, 2) = ab(i, k, 2) + sin72*t4rb
        ab(i, kp, 1) = ab(i, kp, 1) - sin72*t4rb
        ab(i, kp, 3) = ab(i, kp, 3) + sin72*t3ib
        ab(i, k, 4) = ab(i, k, 4) + sin72*t3ib
        ab(i, k, 1) = ab(i, k, 1) + sin72*t3rb
        ab(i, kp, 0) = ab(i, kp, 0) - sin72*t3rb
        ab(i, kp, 2) = ab(i, kp, 2) + t2ib
        ab(i, k, 3) = ab(i, k, 3) - t2ib
        ab(i, k, 2) = ab(i, k, 2) + t2rb
        ab(i, kp, 1) = ab(i, kp, 1) + t2rb
        ab(i, kp, 3) = ab(i, kp, 3) + t1ib
        ab(i, k, 4) = ab(i, k, 4) - t1ib
        ab(i, k, 1) = ab(i, k, 1) + t1rb
        ab(i, kp, 0) = ab(i, kp, 0) + t1rb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    t8b = bb(i, 4, 0)
    t10b = -bb(i, 4, 0)
    bb(i, 4, 0) = 0.D0
    t9b = bb(i, 3, 0)
    t11b = -bb(i, 3, 0)
    bb(i, 3, 0) = 0.D0
    t9b = t9b + bb(i, 2, 0)
    t11b = t11b + bb(i, 2, 0)
    bb(i, 2, 0) = 0.D0
    t8b = t8b + bb(i, 1, 0)
    t10b = t10b + bb(i, 1, 0)
    bb(i, 1, 0) = 0.D0
    t3b = t10b + s36s72*t11b
    t4b = s36s72*t10b - t11b
    t7b = t8b + t9b
    ab(i, 0, 0) = ab(i, 0, 0) + t7b + bb(i, 0, 0)
    t5b = bb(i, 0, 0) - 0.25d0*t7b
    bb(i, 0, 0) = 0.D0
    t6b = t8b - t9b
    t1b = t5b + r54*t6b
    t2b = t5b - r54*t6b
    ab(i, 0, 3) = ab(i, 0, 3) + sin72*t4b
    ab(i, 0, 4) = ab(i, 0, 4) + sin72*t3b
    ab(i, 0, 2) = ab(i, 0, 2) + t2b
    ab(i, 0, 1) = ab(i, 0, 1) + t1b
  END DO
END SUBROUTINE C06FQT_B
