!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpu in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FPU_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-696 (DEC 1989).
!
!     Radix four real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: root2i
  PARAMETER (root2i=0.707106781186547524400844362104849d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:3, 0:r-1), b(0:p-1, 0:r-1, 0:3), cosine&
& (0:r-1, 3), sine(0:r-1, 3)
  DOUBLE PRECISION :: ab(0:p-1, 0:3, 0:r-1), bb(0:p-1, 0:r-1, 0:3)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, ck, s2k, s3k, sk, t1, t1i, t1r, t2, t2i&
& , t2r, t3i, t3r, t4i, t4r, x1p, x2p, x3p, y1p, y2p, y3p
  DOUBLE PRECISION :: t1b, t1ib, t1rb, t2b, t2ib, t2rb, t3ib, t3rb, t4ib&
& , t4rb, x1pb, x2pb, x3pb, y1pb, y2pb, y3pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
  INTEGER :: branch
!
!     Code for general K --
!
  IF (p .LT. (r-1)/2) THEN
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=p-1,0,-1
      ab(i, 2, r2) = ab(i, 2, r2) - bb(i, r2, 3)
      t2b = -bb(i, r2, 3)
      bb(i, r2, 3) = 0.D0
      ab(i, 2, r2) = ab(i, 2, r2) + bb(i, r2, 2)
      t2b = t2b - bb(i, r2, 2)
      bb(i, r2, 2) = 0.D0
      ab(i, 0, r2) = ab(i, 0, r2) + bb(i, r2, 1)
      t1b = -bb(i, r2, 1)
      bb(i, r2, 1) = 0.D0
      ab(i, 0, r2) = ab(i, 0, r2) + bb(i, r2, 0)
      t1b = t1b + bb(i, r2, 0)
      bb(i, r2, 0) = 0.D0
      ab(i, 1, r2) = ab(i, 1, r2) + root2i*t2b
      ab(i, 3, r2) = ab(i, 3, r2) + root2i*t2b
      ab(i, 1, r2) = ab(i, 1, r2) + root2i*t1b
      ab(i, 3, r2) = ab(i, 3, r2) - root2i*t1b
    END DO
  END IF
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        t1ib = bb(i, r-k, 3)
        t2ib = bb(i, r-k, 3)
        bb(i, r-k, 3) = 0.D0
        t3ib = -bb(i, k, 3)
        t4rb = -bb(i, k, 3)
        bb(i, k, 3) = 0.D0
        t3ib = t3ib + bb(i, r-k, 2)
        t4rb = t4rb - bb(i, r-k, 2)
        bb(i, r-k, 2) = 0.D0
        t2ib = t2ib + bb(i, k, 2)
        t1ib = t1ib - bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        t1rb = bb(i, r-k, 1)
        t2rb = -bb(i, r-k, 1)
        bb(i, r-k, 1) = 0.D0
        t3rb = bb(i, k, 1)
        t4ib = bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        t3rb = t3rb + bb(i, r-k, 0)
        t4ib = t4ib - bb(i, r-k, 0)
        bb(i, r-k, 0) = 0.D0
        t1rb = t1rb + bb(i, k, 0)
        t2rb = t2rb + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
        y1pb = t2ib + t4ib
        y3pb = t2ib - t4ib
        x1pb = t2rb + t4rb
        x3pb = t2rb - t4rb
        ab(i, 0, r-k) = ab(i, 0, r-k) + t3ib
        y2pb = t1ib - t3ib
        ab(i, 0, k) = ab(i, 0, k) + t3rb
        x2pb = t1rb - t3rb
        ab(i, 0, r-k) = ab(i, 0, r-k) + t1ib
        ab(i, 0, k) = ab(i, 0, k) + t1rb
        ab(i, 3, r-k) = ab(i, 3, r-k) + cosine(k, 3)*y3pb
        ab(i, 3, k) = ab(i, 3, k) + cosine(k, 3)*x3pb + sine(k, 3)*y3pb
        ab(i, 3, r-k) = ab(i, 3, r-k) - sine(k, 3)*x3pb
        ab(i, 2, r-k) = ab(i, 2, r-k) + cosine(k, 2)*y2pb
        ab(i, 2, k) = ab(i, 2, k) + cosine(k, 2)*x2pb + sine(k, 2)*y2pb
        ab(i, 2, r-k) = ab(i, 2, r-k) - sine(k, 2)*x2pb
        ab(i, 1, r-k) = ab(i, 1, r-k) + cosine(k, 1)*y1pb
        ab(i, 1, k) = ab(i, 1, k) + cosine(k, 1)*x1pb + sine(k, 1)*y1pb
        ab(i, 1, r-k) = ab(i, 1, r-k) - sine(k, 1)*x1pb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      s3k = sine(k, 3)
      c3k = cosine(k, 3)
      kp = r - k
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        t1ib = bb(i, kp, 3)
        t2ib = bb(i, kp, 3)
        bb(i, kp, 3) = 0.D0
        t3ib = -bb(i, k, 3)
        t4rb = -bb(i, k, 3)
        bb(i, k, 3) = 0.D0
        t3ib = t3ib + bb(i, kp, 2)
        t4rb = t4rb - bb(i, kp, 2)
        bb(i, kp, 2) = 0.D0
        t2ib = t2ib + bb(i, k, 2)
        t1ib = t1ib - bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        t1rb = bb(i, kp, 1)
        t2rb = -bb(i, kp, 1)
        bb(i, kp, 1) = 0.D0
        t3rb = bb(i, k, 1)
        t4ib = bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        t3rb = t3rb + bb(i, kp, 0)
        t4ib = t4ib - bb(i, kp, 0)
        bb(i, kp, 0) = 0.D0
        t1rb = t1rb + bb(i, k, 0)
        t2rb = t2rb + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
        y1pb = t2ib + t4ib
        y3pb = t2ib - t4ib
        x1pb = t2rb + t4rb
        x3pb = t2rb - t4rb
        ab(i, 0, kp) = ab(i, 0, kp) + t3ib
        y2pb = t1ib - t3ib
        ab(i, 0, k) = ab(i, 0, k) + t3rb
        x2pb = t1rb - t3rb
        ab(i, 0, kp) = ab(i, 0, kp) + t1ib
        ab(i, 0, k) = ab(i, 0, k) + t1rb
        ab(i, 3, kp) = ab(i, 3, kp) + c3k*y3pb
        ab(i, 3, k) = ab(i, 3, k) + c3k*x3pb + s3k*y3pb
        ab(i, 3, kp) = ab(i, 3, kp) - s3k*x3pb
        ab(i, 2, kp) = ab(i, 2, kp) + c2k*y2pb
        ab(i, 2, k) = ab(i, 2, k) + c2k*x2pb + s2k*y2pb
        ab(i, 2, kp) = ab(i, 2, kp) - s2k*x2pb
        ab(i, 1, kp) = ab(i, 1, kp) + ck*y1pb
        ab(i, 1, k) = ab(i, 1, k) + ck*x1pb + sk*y1pb
        ab(i, 1, kp) = ab(i, 1, kp) - sk*x1pb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    ab(i, 3, 0) = ab(i, 3, 0) + bb(i, 0, 3)
    ab(i, 1, 0) = ab(i, 1, 0) - bb(i, 0, 3)
    bb(i, 0, 3) = 0.D0
    t1b = bb(i, 0, 2)
    t2b = -bb(i, 0, 2)
    bb(i, 0, 2) = 0.D0
    ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 1)
    ab(i, 2, 0) = ab(i, 2, 0) - bb(i, 0, 1)
    bb(i, 0, 1) = 0.D0
    t1b = t1b + bb(i, 0, 0)
    t2b = t2b + bb(i, 0, 0)
    bb(i, 0, 0) = 0.D0
    ab(i, 1, 0) = ab(i, 1, 0) + t2b
    ab(i, 3, 0) = ab(i, 3, 0) + t2b
    ab(i, 0, 0) = ab(i, 0, 0) + t1b
    ab(i, 2, 0) = ab(i, 2, 0) + t1b
  END DO
END SUBROUTINE C06FPU_B
