!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqu in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FQU_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-701 (DEC 1989).
!
!     Radix four Hermitian to real fast Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Parameters ..
  DOUBLE PRECISION :: root2i
  PARAMETER (root2i=0.707106781186547524400844362104849d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:3), b(0:p-1, 0:3, 0:r-1), cosine&
& (0:r-1, 3), sine(0:r-1, 3)
  DOUBLE PRECISION :: ab(0:p-1, 0:r-1, 0:3), bb(0:p-1, 0:3, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, ck, s2k, s3k, sk, t1, t1i, t1r, t2, t2i&
& , t2r, t3, t3i, t3r, t4, t4i, t4r, x0p, x1p, x2p, x3p, y0p, y1p, y2p, &
& y3p
  DOUBLE PRECISION :: t1b, t1ib, t1rb, t2b, t2ib, t2rb, t3b, t3ib, t3rb&
& , t4b, t4ib, t4rb, x0pb, x1pb, x2pb, x3pb, y0pb, y1pb, y2pb, y3pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
  INTEGER :: branch
!
!     Code for general K --
!
  IF (p .LT. (r-1)/2) THEN
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=p-1,0,-1
      t3b = -(root2i*bb(i, 3, r2))
      t4b = root2i*bb(i, 3, r2)
      bb(i, 3, r2) = 0.D0
      t3b = t3b + root2i*bb(i, 1, r2)
      t4b = t4b + root2i*bb(i, 1, r2)
      bb(i, 1, r2) = 0.D0
      ab(i, r2, 3) = ab(i, r2, 3) + t4b
      ab(i, r2, 2) = ab(i, r2, 2) + t4b
      ab(i, r2, 0) = ab(i, r2, 0) + t3b
      ab(i, r2, 1) = ab(i, r2, 1) - t3b
      ab(i, r2, 3) = ab(i, r2, 3) + bb(i, 2, r2)
      ab(i, r2, 2) = ab(i, r2, 2) - bb(i, 2, r2)
      bb(i, 2, r2) = 0.D0
      ab(i, r2, 0) = ab(i, r2, 0) + bb(i, 0, r2)
      ab(i, r2, 1) = ab(i, r2, 1) + bb(i, 0, r2)
      bb(i, 0, r2) = 0.D0
    END DO
  END IF
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        y3pb = cosine(k, 3)*bb(i, 3, r-k)
        x3pb = sine(k, 3)*bb(i, 3, r-k)
        bb(i, 3, r-k) = 0.D0
        x3pb = x3pb + cosine(k, 3)*bb(i, 3, k)
        y3pb = y3pb - sine(k, 3)*bb(i, 3, k)
        bb(i, 3, k) = 0.D0
        y2pb = cosine(k, 2)*bb(i, 2, r-k)
        x2pb = sine(k, 2)*bb(i, 2, r-k)
        bb(i, 2, r-k) = 0.D0
        x2pb = x2pb + cosine(k, 2)*bb(i, 2, k)
        y2pb = y2pb - sine(k, 2)*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        y1pb = cosine(k, 1)*bb(i, 1, r-k)
        x1pb = sine(k, 1)*bb(i, 1, r-k)
        bb(i, 1, r-k) = 0.D0
        x1pb = x1pb + cosine(k, 1)*bb(i, 1, k)
        y1pb = y1pb - sine(k, 1)*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, r-k)
        bb(i, 0, r-k) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        t3ib = y1pb + y3pb
        t4rb = y3pb - y1pb
        t3rb = x1pb + x3pb
        t4ib = x1pb - x3pb
        t1ib = y0pb + y2pb
        t2ib = y0pb - y2pb
        t1rb = x0pb + x2pb
        t2rb = x0pb - x2pb
        ab(i, r-k, 2) = ab(i, r-k, 2) + t4ib
        ab(i, k, 3) = ab(i, k, 3) + t4ib
        ab(i, k, 1) = ab(i, k, 1) + t4rb
        ab(i, r-k, 0) = ab(i, r-k, 0) - t4rb
        ab(i, r-k, 3) = ab(i, r-k, 3) + t3ib
        ab(i, k, 2) = ab(i, k, 2) + t3ib
        ab(i, k, 0) = ab(i, k, 0) + t3rb
        ab(i, r-k, 1) = ab(i, r-k, 1) - t3rb
        ab(i, r-k, 2) = ab(i, r-k, 2) + t2ib
        ab(i, k, 3) = ab(i, k, 3) - t2ib
        ab(i, k, 1) = ab(i, k, 1) + t2rb
        ab(i, r-k, 0) = ab(i, r-k, 0) + t2rb
        ab(i, r-k, 3) = ab(i, r-k, 3) + t1ib
        ab(i, k, 2) = ab(i, k, 2) - t1ib
        ab(i, k, 0) = ab(i, k, 0) + t1rb
        ab(i, r-k, 1) = ab(i, r-k, 1) + t1rb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      s3k = sine(k, 3)
      c3k = cosine(k, 3)
      kp = r - k
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        y3pb = c3k*bb(i, 3, kp)
        x3pb = s3k*bb(i, 3, kp)
        bb(i, 3, kp) = 0.D0
        x3pb = x3pb + c3k*bb(i, 3, k)
        y3pb = y3pb - s3k*bb(i, 3, k)
        bb(i, 3, k) = 0.D0
        y2pb = c2k*bb(i, 2, kp)
        x2pb = s2k*bb(i, 2, kp)
        bb(i, 2, kp) = 0.D0
        x2pb = x2pb + c2k*bb(i, 2, k)
        y2pb = y2pb - s2k*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        y1pb = ck*bb(i, 1, kp)
        x1pb = sk*bb(i, 1, kp)
        bb(i, 1, kp) = 0.D0
        x1pb = x1pb + ck*bb(i, 1, k)
        y1pb = y1pb - sk*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, kp)
        bb(i, 0, kp) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        t3ib = y1pb + y3pb
        t4rb = y3pb - y1pb
        t3rb = x1pb + x3pb
        t4ib = x1pb - x3pb
        t1ib = y0pb + y2pb
        t2ib = y0pb - y2pb
        t1rb = x0pb + x2pb
        t2rb = x0pb - x2pb
        ab(i, kp, 2) = ab(i, kp, 2) + t4ib
        ab(i, k, 3) = ab(i, k, 3) + t4ib
        ab(i, k, 1) = ab(i, k, 1) + t4rb
        ab(i, kp, 0) = ab(i, kp, 0) - t4rb
        ab(i, kp, 3) = ab(i, kp, 3) + t3ib
        ab(i, k, 2) = ab(i, k, 2) + t3ib
        ab(i, k, 0) = ab(i, k, 0) + t3rb
        ab(i, kp, 1) = ab(i, kp, 1) - t3rb
        ab(i, kp, 2) = ab(i, kp, 2) + t2ib
        ab(i, k, 3) = ab(i, k, 3) - t2ib
        ab(i, k, 1) = ab(i, k, 1) + t2rb
        ab(i, kp, 0) = ab(i, kp, 0) + t2rb
        ab(i, kp, 3) = ab(i, kp, 3) + t1ib
        ab(i, k, 2) = ab(i, k, 2) - t1ib
        ab(i, k, 0) = ab(i, k, 0) + t1rb
        ab(i, kp, 1) = ab(i, kp, 1) + t1rb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    t3b = bb(i, 3, 0)
    t4b = -bb(i, 3, 0)
    bb(i, 3, 0) = 0.D0
    t1b = bb(i, 2, 0)
    t2b = -bb(i, 2, 0)
    bb(i, 2, 0) = 0.D0
    t3b = t3b + bb(i, 1, 0)
    t4b = t4b + bb(i, 1, 0)
    bb(i, 1, 0) = 0.D0
    t1b = t1b + bb(i, 0, 0)
    t2b = t2b + bb(i, 0, 0)
    bb(i, 0, 0) = 0.D0
    ab(i, 0, 3) = ab(i, 0, 3) + t4b
    ab(i, 0, 0) = ab(i, 0, 0) + t3b
    ab(i, 0, 2) = ab(i, 0, 2) - t3b
    ab(i, 0, 1) = ab(i, 0, 1) + t2b
    ab(i, 0, 0) = ab(i, 0, 0) + t1b
    ab(i, 0, 2) = ab(i, 0, 2) + t1b
  END DO
END SUBROUTINE C06FQU_B
