!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpr in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FPR_B(a, ab, b, bb, p, q, r, cosine, sine)
  IMPLICIT NONE
!     MARK 15 RE-ISSUE. NAG COPYRIGHT 1991.
!
!     Real to Hermitian fast Fourier transform kernel
!     Odd factors greater than 6
!
!     Self-sorting, decimation in time
!
!     .. Scalar Arguments ..
  INTEGER :: p, q, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:q-1, 0:r-1), b(0:p-1, 0:r-1, 0:q-1), &
& cosine(0:r-1, q-1), sine(0:r-1, q-1)
  DOUBLE PRECISION :: ab(0:p-1, 0:q-1, 0:r-1), bb(0:p-1, 0:r-1, 0:q-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: ai, ar, temp1, temp2, temp3, temp4
  DOUBLE PRECISION :: aib, arb, temp1b, temp2b, temp3b, temp4b
  INTEGER :: i, indx, j, k, kp, l, q2, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
  DOUBLE PRECISION :: tmp
  DOUBLE PRECISION :: tmpb
  DOUBLE PRECISION :: tmp0
  DOUBLE PRECISION :: tmp1
  DOUBLE PRECISION :: tmpb0
  DOUBLE PRECISION :: tmpb1
  DOUBLE PRECISION :: tmp2
  DOUBLE PRECISION :: tmp3
  DOUBLE PRECISION :: tmpb2
  DOUBLE PRECISION :: tmpb3
  DOUBLE PRECISION :: tmp4
  DOUBLE PRECISION :: tmpb4
  DOUBLE PRECISION :: tmp5
  DOUBLE PRECISION :: tmp6
  DOUBLE PRECISION :: tmpb5
  DOUBLE PRECISION :: tmpb6
  DOUBLE PRECISION :: tmp7
  DOUBLE PRECISION :: tmp8
  DOUBLE PRECISION :: tmpb7
  DOUBLE PRECISION :: tmpb8
  INTEGER :: branch
!     .. Executable Statements ..
!
  q2 = (q-1)/2
  IF (p .GE. r/2) THEN
    DO l=1,q2
      DO j=1,q2
        CALL PUSHINTEGER4(indx)
        indx = MOD(j*l, q)
      END DO
    END DO
!
!        Code for general K --
!
    DO k=1,(r-1)/2
      DO l=1,q2
        DO j=1,q2
          CALL PUSHINTEGER4(indx)
          indx = MOD(j*l, q)
        END DO
      END DO
    END DO
!
!        Code for K=R/2 if R is even --
!
    IF (MOD(r, 2) .EQ. 0) THEN
      r2 = r/2
      IF (MOD(q2, 2) .EQ. 1) THEN
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
      DO l=0,q2-1
        DO j=1,q2
          CALL PUSHINTEGER4(indx)
          indx = MOD(j*(l+q2+1), q)
        END DO
      END DO
      DO j=q2,1,-1
        DO i=p-1,0,-1
          ab(i, j, r2) = ab(i, j, r2) + bb(i, r2, q2)
        END DO
      END DO
      DO i=p-1,0,-1
        ab(i, 0, r2) = ab(i, 0, r2) + bb(i, r2, q2)
        bb(i, r2, q2) = 0.D0
      END DO
      DO l=q2-1,0,-1
        DO j=q2,1,-1
          DO i=p-1,0,-1
            ab(i, q-j, r2) = ab(i, q-j, r2) + sine(0, indx)*bb(i, r2, q-&
&             l-1)
            ab(i, j, r2) = ab(i, j, r2) + cosine(0, indx)*bb(i, r2, l)
          END DO
          CALL POPINTEGER4(indx)
        END DO
        DO i=p-1,0,-1
          bb(i, r2, q-l-1) = 0.D0
          ab(i, 0, r2) = ab(i, 0, r2) + bb(i, r2, l)
          bb(i, r2, l) = 0.D0
        END DO
      END DO
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        DO i=p-1,0,-1
          temp1b = -ab(i, q2+1, r2)
          temp2b = -ab(i, q2+1, r2)
          ab(i, q2+1, r2) = 0.D0
          temp2b = temp2b + ab(i, q2, r2)
          temp1b = temp1b - ab(i, q2, r2)
          ab(i, q2, r2) = 0.D0
          ab(i, q2+1, r2) = ab(i, q2+1, r2) + temp2b
          ab(i, q2, r2) = ab(i, q2, r2) + temp1b
        END DO
      END IF
      DO j=q2-MOD(q2-2, 2)-1,1,-2
        DO i=p-1,0,-1
          temp3b = ab(i, q-j-1, r2)
          temp4b = ab(i, q-j-1, r2)
          ab(i, q-j-1, r2) = 0.D0
          temp3b = temp3b + ab(i, j+1, r2)
          temp4b = temp4b - ab(i, j+1, r2)
          ab(i, j+1, r2) = 0.D0
          ab(i, q-j-1, r2) = ab(i, q-j-1, r2) + temp4b
          ab(i, j+1, r2) = ab(i, j+1, r2) + temp3b
          temp1b = -ab(i, q-j, r2)
          temp2b = -ab(i, q-j, r2)
          ab(i, q-j, r2) = 0.D0
          temp2b = temp2b + ab(i, j, r2)
          temp1b = temp1b - ab(i, j, r2)
          ab(i, j, r2) = 0.D0
          ab(i, q-j, r2) = ab(i, q-j, r2) + temp2b
          ab(i, j, r2) = ab(i, j, r2) + temp1b
        END DO
      END DO
    END IF
    DO k=(r-1)/2,1,-1
      kp = r - k
      DO l=q2,1,-1
        DO i=p-1,0,-1
          temp2b = -bb(i, k, q-l)
          temp3b = -bb(i, k, q-l)
          bb(i, k, q-l) = 0.D0
          temp2b = temp2b + bb(i, kp, q-l-1)
          temp3b = temp3b - bb(i, kp, q-l-1)
          bb(i, kp, q-l-1) = 0.D0
          tmpb2 = bb(i, kp, l-1)
          bb(i, kp, l-1) = 0.D0
          bb(i, k, q-l) = bb(i, k, q-l) + tmpb2
          tmpb3 = bb(i, k, l)
          temp1b = tmpb3 + tmpb2
          bb(i, k, l) = 0.D0
          bb(i, k, q-l) = bb(i, k, q-l) - tmpb3
          bb(i, kp, l-1) = bb(i, kp, l-1) + temp3b
          bb(i, kp, q-l-1) = bb(i, kp, q-l-1) + temp2b
          bb(i, k, l) = bb(i, k, l) + temp1b
        END DO
      END DO
      DO j=q2,1,-1
        DO i=p-1,0,-1
          ab(i, j, kp) = ab(i, j, kp) + bb(i, kp, q-1)
          ab(i, j, k) = ab(i, j, k) + bb(i, k, 0)
        END DO
      END DO
      DO i=p-1,0,-1
        ab(i, 0, kp) = ab(i, 0, kp) + bb(i, kp, q-1)
        bb(i, kp, q-1) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
      END DO
      DO l=q2,1,-1
        DO j=q2,1,-1
          DO i=p-1,0,-1
            ab(i, q-j, kp) = ab(i, q-j, kp) + sine(0, indx)*bb(i, k, q-l&
&             )
            ab(i, q-j, k) = ab(i, q-j, k) - sine(0, indx)*bb(i, kp, l-1)
            ab(i, j, kp) = ab(i, j, kp) + cosine(0, indx)*bb(i, kp, q-l-&
&             1)
            ab(i, j, k) = ab(i, j, k) + cosine(0, indx)*bb(i, k, l)
          END DO
          CALL POPINTEGER4(indx)
        END DO
        DO i=p-1,0,-1
          bb(i, k, q-l) = 0.D0
          bb(i, kp, l-1) = 0.D0
          ab(i, 0, kp) = ab(i, 0, kp) + bb(i, kp, q-l-1)
          bb(i, kp, q-l-1) = 0.D0
          ab(i, 0, k) = ab(i, 0, k) + bb(i, k, l)
          bb(i, k, l) = 0.D0
        END DO
      END DO
      DO j=q2,1,-1
        DO i=p-1,0,-1
          temp2b = ab(i, q-j, kp)
          ab(i, q-j, kp) = -ab(i, q-j, kp)
          temp1b = ab(i, q-j, k)
          ab(i, q-j, k) = -ab(i, q-j, k)
          tmpb0 = ab(i, j, kp)
          ab(i, j, kp) = 0.D0
          temp2b = temp2b + tmpb0
          ab(i, q-j, kp) = ab(i, q-j, kp) + tmpb0
          tmpb1 = ab(i, j, k)
          ab(i, j, k) = 0.D0
          temp1b = temp1b + tmpb1
          ab(i, q-j, k) = ab(i, q-j, k) + tmpb1
          ab(i, j, kp) = ab(i, j, kp) + temp2b
          ab(i, j, k) = ab(i, j, k) + temp1b
        END DO
      END DO
      DO j=q-1,1,-1
        DO i=p-1,0,-1
          aib = cosine(k, j)*ab(i, j, kp)
          arb = sine(k, j)*ab(i, j, kp)
          ab(i, j, kp) = 0.D0
          arb = arb + cosine(k, j)*ab(i, j, k)
          aib = aib - sine(k, j)*ab(i, j, k)
          ab(i, j, k) = 0.D0
          ab(i, j, kp) = ab(i, j, kp) + aib
          ab(i, j, k) = ab(i, j, k) + arb
        END DO
      END DO
    END DO
    DO j=q2,1,-1
      DO i=p-1,0,-1
        ab(i, j, 0) = ab(i, j, 0) + bb(i, 0, 0)
      END DO
    END DO
    DO i=p-1,0,-1
      ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
      bb(i, 0, 0) = 0.D0
    END DO
    DO l=q2,1,-1
      DO j=q2,1,-1
        DO i=p-1,0,-1
          ab(i, q-j, 0) = ab(i, q-j, 0) + sine(0, indx)*bb(i, 0, q-l)
          ab(i, j, 0) = ab(i, j, 0) + cosine(0, indx)*bb(i, 0, l)
        END DO
        CALL POPINTEGER4(indx)
      END DO
      DO i=p-1,0,-1
        bb(i, 0, q-l) = 0.D0
        ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, l)
        bb(i, 0, l) = 0.D0
      END DO
    END DO
    DO j=q2,1,-1
      DO i=p-1,0,-1
        temp1b = ab(i, q-j, 0)
        ab(i, q-j, 0) = -ab(i, q-j, 0)
        tmpb = ab(i, j, 0)
        ab(i, j, 0) = 0.D0
        temp1b = temp1b + tmpb
        ab(i, q-j, 0) = ab(i, q-j, 0) + tmpb
        ab(i, j, 0) = ab(i, j, 0) + temp1b
      END DO
    END DO
  ELSE
!
!
    DO i=0,p-1
      DO l=1,q2
        DO j=1,q2
          CALL PUSHINTEGER4(indx)
          indx = MOD(j*l, q)
        END DO
      END DO
      DO l=1,q2
        DO j=1,q2
          CALL PUSHINTEGER4(indx)
          indx = MOD(j*l, q)
        END DO
      END DO
!
!           Code for K=R/2 if R is even --
!
      IF (MOD(r, 2) .EQ. 0) THEN
        CALL PUSHINTEGER4(r2)
        r2 = r/2
        IF (MOD(q2, 2) .EQ. 1) THEN
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
        DO l=0,q2-1
          DO j=1,q2
            CALL PUSHINTEGER4(indx)
            indx = MOD(j*(l+q2+1), q)
          END DO
        END DO
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
    END DO
    DO i=p-1,0,-1
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        DO j=q2,1,-1
          ab(i, j, r2) = ab(i, j, r2) + bb(i, r2, q2)
        END DO
        ab(i, 0, r2) = ab(i, 0, r2) + bb(i, r2, q2)
        bb(i, r2, q2) = 0.D0
        DO l=q2-1,0,-1
          DO j=q2,1,-1
            ab(i, q-j, r2) = ab(i, q-j, r2) + sine(0, indx)*bb(i, r2, q-&
&             l-1)
            ab(i, j, r2) = ab(i, j, r2) + cosine(0, indx)*bb(i, r2, l)
            CALL POPINTEGER4(indx)
          END DO
          bb(i, r2, q-l-1) = 0.D0
          ab(i, 0, r2) = ab(i, 0, r2) + bb(i, r2, l)
          bb(i, r2, l) = 0.D0
        END DO
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) THEN
          temp1b = -ab(i, q2+1, r2)
          temp2b = -ab(i, q2+1, r2)
          ab(i, q2+1, r2) = 0.D0
          temp2b = temp2b + ab(i, q2, r2)
          temp1b = temp1b - ab(i, q2, r2)
          ab(i, q2, r2) = 0.D0
          ab(i, q2+1, r2) = ab(i, q2+1, r2) + temp2b
          ab(i, q2, r2) = ab(i, q2, r2) + temp1b
        END IF
        DO j=q2-MOD(q2-2, 2)-1,1,-2
          temp3b = ab(i, q-j-1, r2)
          temp4b = ab(i, q-j-1, r2)
          ab(i, q-j-1, r2) = 0.D0
          temp3b = temp3b + ab(i, j+1, r2)
          temp4b = temp4b - ab(i, j+1, r2)
          ab(i, j+1, r2) = 0.D0
          ab(i, q-j-1, r2) = ab(i, q-j-1, r2) + temp4b
          ab(i, j+1, r2) = ab(i, j+1, r2) + temp3b
          temp1b = -ab(i, q-j, r2)
          temp2b = -ab(i, q-j, r2)
          ab(i, q-j, r2) = 0.D0
          temp2b = temp2b + ab(i, j, r2)
          temp1b = temp1b - ab(i, j, r2)
          ab(i, j, r2) = 0.D0
          ab(i, q-j, r2) = ab(i, q-j, r2) + temp2b
          ab(i, j, r2) = ab(i, j, r2) + temp1b
        END DO
        CALL POPINTEGER4(r2)
      END IF
      DO l=q2,1,-1
        DO k=(r-1)/2,1,-1
          temp2b = -bb(i, k, q-l)
          temp3b = -bb(i, k, q-l)
          bb(i, k, q-l) = 0.D0
          temp2b = temp2b + bb(i, r-k, q-l-1)
          temp3b = temp3b - bb(i, r-k, q-l-1)
          bb(i, r-k, q-l-1) = 0.D0
          tmpb7 = bb(i, r-k, l-1)
          bb(i, r-k, l-1) = 0.D0
          bb(i, k, q-l) = bb(i, k, q-l) + tmpb7
          tmpb8 = bb(i, k, l)
          temp1b = tmpb8 + tmpb7
          bb(i, k, l) = 0.D0
          bb(i, k, q-l) = bb(i, k, q-l) - tmpb8
          bb(i, r-k, l-1) = bb(i, r-k, l-1) + temp3b
          bb(i, r-k, q-l-1) = bb(i, r-k, q-l-1) + temp2b
          bb(i, k, l) = bb(i, k, l) + temp1b
        END DO
      END DO
      DO j=q2,1,-1
        DO k=(r-1)/2,1,-1
          ab(i, j, r-k) = ab(i, j, r-k) + bb(i, r-k, q-1)
          ab(i, j, k) = ab(i, j, k) + bb(i, k, 0)
        END DO
      END DO
      DO k=(r-1)/2,1,-1
        ab(i, 0, r-k) = ab(i, 0, r-k) + bb(i, r-k, q-1)
        bb(i, r-k, q-1) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        bb(i, k, 0) = 0.D0
      END DO
      DO l=q2,1,-1
        DO j=q2,1,-1
          DO k=(r-1)/2,1,-1
            ab(i, q-j, r-k) = ab(i, q-j, r-k) + sine(0, indx)*bb(i, k, q&
&             -l)
            ab(i, q-j, k) = ab(i, q-j, k) - sine(0, indx)*bb(i, r-k, l-1&
&             )
            ab(i, j, r-k) = ab(i, j, r-k) + cosine(0, indx)*bb(i, r-k, q&
&             -l-1)
            ab(i, j, k) = ab(i, j, k) + cosine(0, indx)*bb(i, k, l)
          END DO
          CALL POPINTEGER4(indx)
        END DO
        DO k=(r-1)/2,1,-1
          bb(i, k, q-l) = 0.D0
          bb(i, r-k, l-1) = 0.D0
          ab(i, 0, r-k) = ab(i, 0, r-k) + bb(i, r-k, q-l-1)
          bb(i, r-k, q-l-1) = 0.D0
          ab(i, 0, k) = ab(i, 0, k) + bb(i, k, l)
          bb(i, k, l) = 0.D0
        END DO
      END DO
      DO j=q2,1,-1
        DO k=(r-1)/2,1,-1
          temp2b = ab(i, q-j, r-k)
          ab(i, q-j, r-k) = -ab(i, q-j, r-k)
          temp1b = ab(i, q-j, k)
          ab(i, q-j, k) = -ab(i, q-j, k)
          tmpb5 = ab(i, j, r-k)
          ab(i, j, r-k) = 0.D0
          temp2b = temp2b + tmpb5
          ab(i, q-j, r-k) = ab(i, q-j, r-k) + tmpb5
          tmpb6 = ab(i, j, k)
          ab(i, j, k) = 0.D0
          temp1b = temp1b + tmpb6
          ab(i, q-j, k) = ab(i, q-j, k) + tmpb6
          ab(i, j, r-k) = ab(i, j, r-k) + temp2b
          ab(i, j, k) = ab(i, j, k) + temp1b
        END DO
      END DO
      DO j=q-1,1,-1
        DO k=(r-1)/2,1,-1
          aib = cosine(k, j)*ab(i, j, r-k)
          arb = sine(k, j)*ab(i, j, r-k)
          ab(i, j, r-k) = 0.D0
          arb = arb + cosine(k, j)*ab(i, j, k)
          aib = aib - sine(k, j)*ab(i, j, k)
          ab(i, j, k) = 0.D0
          ab(i, j, r-k) = ab(i, j, r-k) + aib
          ab(i, j, k) = ab(i, j, k) + arb
        END DO
      END DO
      DO j=q2,1,-1
        ab(i, j, 0) = ab(i, j, 0) + bb(i, 0, 0)
      END DO
      ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, 0)
      bb(i, 0, 0) = 0.D0
      DO l=q2,1,-1
        DO j=q2,1,-1
          ab(i, q-j, 0) = ab(i, q-j, 0) + sine(0, indx)*bb(i, 0, q-l)
          ab(i, j, 0) = ab(i, j, 0) + cosine(0, indx)*bb(i, 0, l)
          CALL POPINTEGER4(indx)
        END DO
        bb(i, 0, q-l) = 0.D0
        ab(i, 0, 0) = ab(i, 0, 0) + bb(i, 0, l)
        bb(i, 0, l) = 0.D0
      END DO
      DO j=q2,1,-1
        temp1b = ab(i, q-j, 0)
        ab(i, q-j, 0) = -ab(i, q-j, 0)
        tmpb4 = ab(i, j, 0)
        ab(i, j, 0) = 0.D0
        temp1b = temp1b + tmpb4
        ab(i, q-j, 0) = ab(i, q-j, 0) + tmpb4
        ab(i, j, 0) = ab(i, j, 0) + temp1b
      END DO
    END DO
  END IF
END SUBROUTINE C06FPR_B
