!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqs in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FQS_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-699 (DEC 1989).
!
!     Radix six Hermitian to real fast Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:5), b(0:p-1, 0:5, 0:r-1), cosine&
& (0:r-1, 5), sine(0:r-1, 5)
  DOUBLE PRECISION :: ab(0:p-1, 0:r-1, 0:5), bb(0:p-1, 0:5, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, c4k, c5k, ck, s2k, s3k, s4k, s5k, sk, t1&
& , t1i, t1r, t2, t2i, t2r, t3, t3i, t3r, t4, t5, t6, u0, u0i, u0r, u1, &
& u1i, u1r, u2, u2i, u2r, v0, v0i, v0r, v1, v1i, v1r, v2, v2i, v2r, x0p&
& , x1p, x2p, x3p, x4p, x5p, y0p, y1p, y2p, y3p, y4p, y5p
  DOUBLE PRECISION :: t1b, t1ib, t1rb, t2b, t2ib, t2rb, t3b, t3ib, t3rb&
& , t4b, t5b, t6b, u0b, u0ib, u0rb, u1b, u1ib, u1rb, u2b, u2ib, u2rb, &
& v0b, v0ib, v0rb, v1b, v1ib, v1rb, v2b, v2ib, v2rb, x0pb, x1pb, x2pb, &
& x3pb, x4pb, x5pb, y0pb, y1pb, y2pb, y3pb, y4pb, y5pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
  INTEGER :: branch
!
!     Code for general K --
!
  IF (p .LE. (r-1)/2) THEN
    CALL PUSHCONTROL1B(0)
  ELSE
    CALL PUSHCONTROL1B(1)
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=p-1,0,-1
      t4b = bb(i, 5, r2)
      t5b = -bb(i, 5, r2)
      bb(i, 5, r2) = 0.D0
      t3b = bb(i, 4, r2)
      t6b = bb(i, 4, r2)
      bb(i, 4, r2) = 0.D0
      t2b = bb(i, 3, r2)
      ab(i, r2, 4) = ab(i, r2, 4) - bb(i, 3, r2)
      bb(i, 3, r2) = 0.D0
      t6b = t6b + bb(i, 2, r2)
      t3b = t3b - bb(i, 2, r2)
      bb(i, 2, r2) = 0.D0
      t4b = t4b + bb(i, 1, r2)
      t5b = t5b + bb(i, 1, r2)
      bb(i, 1, r2) = 0.D0
      ab(i, r2, 1) = ab(i, r2, 1) + bb(i, 0, r2)
      t1b = bb(i, 0, r2) - 0.5d0*t3b
      bb(i, 0, r2) = 0.D0
      ab(i, r2, 5) = ab(i, r2, 5) + sin60*t6b
      ab(i, r2, 3) = ab(i, r2, 3) - sin60*t6b
      ab(i, r2, 0) = ab(i, r2, 0) + sin60*t5b
      ab(i, r2, 2) = ab(i, r2, 2) - sin60*t5b
      ab(i, r2, 4) = ab(i, r2, 4) + t4b
      t2b = t2b + 0.5d0*t4b
      ab(i, r2, 1) = ab(i, r2, 1) + t3b
      ab(i, r2, 5) = ab(i, r2, 5) + t2b
      ab(i, r2, 3) = ab(i, r2, 3) + t2b
      ab(i, r2, 0) = ab(i, r2, 0) + t1b
      ab(i, r2, 2) = ab(i, r2, 2) + t1b
    END DO
  END IF
  CALL POPCONTROL1B(branch)
  IF (branch .EQ. 0) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        y5pb = cosine(k, 5)*bb(i, 5, r-k)
        x5pb = sine(k, 5)*bb(i, 5, r-k)
        bb(i, 5, r-k) = 0.D0
        x5pb = x5pb + cosine(k, 5)*bb(i, 5, k)
        y5pb = y5pb - sine(k, 5)*bb(i, 5, k)
        bb(i, 5, k) = 0.D0
        y4pb = cosine(k, 4)*bb(i, 4, r-k)
        x4pb = sine(k, 4)*bb(i, 4, r-k)
        bb(i, 4, r-k) = 0.D0
        x4pb = x4pb + cosine(k, 4)*bb(i, 4, k)
        y4pb = y4pb - sine(k, 4)*bb(i, 4, k)
        bb(i, 4, k) = 0.D0
        y3pb = cosine(k, 3)*bb(i, 3, r-k)
        x3pb = sine(k, 3)*bb(i, 3, r-k)
        bb(i, 3, r-k) = 0.D0
        x3pb = x3pb + cosine(k, 3)*bb(i, 3, k)
        y3pb = y3pb - sine(k, 3)*bb(i, 3, k)
        bb(i, 3, k) = 0.D0
        y2pb = cosine(k, 2)*bb(i, 2, r-k)
        x2pb = sine(k, 2)*bb(i, 2, r-k)
        bb(i, 2, r-k) = 0.D0
        x2pb = x2pb + cosine(k, 2)*bb(i, 2, k)
        y2pb = y2pb - sine(k, 2)*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        y1pb = cosine(k, 1)*bb(i, 1, r-k)
        x1pb = sine(k, 1)*bb(i, 1, r-k)
        bb(i, 1, r-k) = 0.D0
        x1pb = x1pb + cosine(k, 1)*bb(i, 1, k)
        y1pb = y1pb - sine(k, 1)*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, r-k)
        bb(i, 0, r-k) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        u2ib = y2pb + y5pb
        v2ib = y2pb - y5pb
        u2rb = x2pb + x5pb
        v2rb = x2pb - x5pb
        u1ib = y1pb + y4pb
        v1ib = y4pb - y1pb
        u1rb = x1pb + x4pb
        v1rb = x4pb - x1pb
        u0ib = y0pb + y3pb
        v0ib = y0pb - y3pb
        u0rb = x0pb + x3pb
        v0rb = x0pb - x3pb
        t2ib = v1ib + v2ib
        t3rb = v2ib - v1ib
        t2rb = v1rb + v2rb
        t3ib = v1rb - v2rb
        t1ib = v0ib - 0.5d0*t2ib
        ab(i, k, 3) = ab(i, k, 3) - v0ib
        ab(i, r-k, 2) = ab(i, r-k, 2) + v0rb
        t1rb = v0rb - 0.5d0*t2rb
        ab(i, k, 5) = ab(i, k, 5) - sin60*t3ib
        ab(i, r-k, 4) = ab(i, r-k, 4) - sin60*t3ib
        ab(i, r-k, 0) = ab(i, r-k, 0) + sin60*t3rb
        ab(i, k, 1) = ab(i, k, 1) - sin60*t3rb
        ab(i, k, 3) = ab(i, k, 3) - t2ib
        ab(i, r-k, 2) = ab(i, r-k, 2) + t2rb
        ab(i, r-k, 4) = ab(i, r-k, 4) + t1ib
        ab(i, k, 5) = ab(i, k, 5) - t1ib
        ab(i, r-k, 0) = ab(i, r-k, 0) + t1rb
        ab(i, k, 1) = ab(i, k, 1) + t1rb
        t2ib = u1ib + u2ib
        t3rb = u2ib - u1ib
        t2rb = u1rb + u2rb
        t3ib = u1rb - u2rb
        ab(i, r-k, 5) = ab(i, r-k, 5) + u0ib
        t1ib = u0ib - 0.5d0*t2ib
        ab(i, k, 0) = ab(i, k, 0) + u0rb
        t1rb = u0rb - 0.5d0*t2rb
        ab(i, r-k, 3) = ab(i, r-k, 3) + sin60*t3ib
        ab(i, k, 4) = ab(i, k, 4) + sin60*t3ib
        ab(i, k, 2) = ab(i, k, 2) + sin60*t3rb
        ab(i, r-k, 1) = ab(i, r-k, 1) - sin60*t3rb
        ab(i, r-k, 5) = ab(i, r-k, 5) + t2ib
        ab(i, k, 0) = ab(i, k, 0) + t2rb
        ab(i, r-k, 3) = ab(i, r-k, 3) + t1ib
        ab(i, k, 4) = ab(i, k, 4) - t1ib
        ab(i, k, 2) = ab(i, k, 2) + t1rb
        ab(i, r-k, 1) = ab(i, r-k, 1) + t1rb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      s3k = sine(k, 3)
      c3k = cosine(k, 3)
      kp = r - k
      s4k = sine(k, 4)
      c4k = cosine(k, 4)
      s5k = sine(k, 5)
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c5k = cosine(k, 5)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        y5pb = c5k*bb(i, 5, kp)
        x5pb = s5k*bb(i, 5, kp)
        bb(i, 5, kp) = 0.D0
        x5pb = x5pb + c5k*bb(i, 5, k)
        y5pb = y5pb - s5k*bb(i, 5, k)
        bb(i, 5, k) = 0.D0
        y4pb = c4k*bb(i, 4, kp)
        x4pb = s4k*bb(i, 4, kp)
        bb(i, 4, kp) = 0.D0
        x4pb = x4pb + c4k*bb(i, 4, k)
        y4pb = y4pb - s4k*bb(i, 4, k)
        bb(i, 4, k) = 0.D0
        y3pb = c3k*bb(i, 3, kp)
        x3pb = s3k*bb(i, 3, kp)
        bb(i, 3, kp) = 0.D0
        x3pb = x3pb + c3k*bb(i, 3, k)
        y3pb = y3pb - s3k*bb(i, 3, k)
        bb(i, 3, k) = 0.D0
        y2pb = c2k*bb(i, 2, kp)
        x2pb = s2k*bb(i, 2, kp)
        bb(i, 2, kp) = 0.D0
        x2pb = x2pb + c2k*bb(i, 2, k)
        y2pb = y2pb - s2k*bb(i, 2, k)
        bb(i, 2, k) = 0.D0
        y1pb = ck*bb(i, 1, kp)
        x1pb = sk*bb(i, 1, kp)
        bb(i, 1, kp) = 0.D0
        x1pb = x1pb + ck*bb(i, 1, k)
        y1pb = y1pb - sk*bb(i, 1, k)
        bb(i, 1, k) = 0.D0
        y0pb = bb(i, 0, kp)
        bb(i, 0, kp) = 0.D0
        x0pb = bb(i, 0, k)
        bb(i, 0, k) = 0.D0
        u2ib = y2pb + y5pb
        v2ib = y2pb - y5pb
        u2rb = x2pb + x5pb
        v2rb = x2pb - x5pb
        u1ib = y1pb + y4pb
        v1ib = y4pb - y1pb
        u1rb = x1pb + x4pb
        v1rb = x4pb - x1pb
        u0ib = y0pb + y3pb
        v0ib = y0pb - y3pb
        u0rb = x0pb + x3pb
        v0rb = x0pb - x3pb
        t2ib = v1ib + v2ib
        t3rb = v2ib - v1ib
        t2rb = v1rb + v2rb
        t3ib = v1rb - v2rb
        t1ib = v0ib - 0.5d0*t2ib
        ab(i, k, 3) = ab(i, k, 3) - v0ib
        ab(i, kp, 2) = ab(i, kp, 2) + v0rb
        t1rb = v0rb - 0.5d0*t2rb
        ab(i, k, 5) = ab(i, k, 5) - sin60*t3ib
        ab(i, kp, 4) = ab(i, kp, 4) - sin60*t3ib
        ab(i, kp, 0) = ab(i, kp, 0) + sin60*t3rb
        ab(i, k, 1) = ab(i, k, 1) - sin60*t3rb
        ab(i, k, 3) = ab(i, k, 3) - t2ib
        ab(i, kp, 2) = ab(i, kp, 2) + t2rb
        ab(i, kp, 4) = ab(i, kp, 4) + t1ib
        ab(i, k, 5) = ab(i, k, 5) - t1ib
        ab(i, kp, 0) = ab(i, kp, 0) + t1rb
        ab(i, k, 1) = ab(i, k, 1) + t1rb
        t2ib = u1ib + u2ib
        t3rb = u2ib - u1ib
        t2rb = u1rb + u2rb
        t3ib = u1rb - u2rb
        ab(i, kp, 5) = ab(i, kp, 5) + u0ib
        t1ib = u0ib - 0.5d0*t2ib
        ab(i, k, 0) = ab(i, k, 0) + u0rb
        t1rb = u0rb - 0.5d0*t2rb
        ab(i, kp, 3) = ab(i, kp, 3) + sin60*t3ib
        ab(i, k, 4) = ab(i, k, 4) + sin60*t3ib
        ab(i, k, 2) = ab(i, k, 2) + sin60*t3rb
        ab(i, kp, 1) = ab(i, kp, 1) - sin60*t3rb
        ab(i, kp, 5) = ab(i, kp, 5) + t2ib
        ab(i, k, 0) = ab(i, k, 0) + t2rb
        ab(i, kp, 3) = ab(i, kp, 3) + t1ib
        ab(i, k, 4) = ab(i, k, 4) - t1ib
        ab(i, k, 2) = ab(i, k, 2) + t1rb
        ab(i, kp, 1) = ab(i, kp, 1) + t1rb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    u2b = bb(i, 5, 0)
    v2b = -bb(i, 5, 0)
    bb(i, 5, 0) = 0.D0
    u1b = bb(i, 4, 0)
    v1b = bb(i, 4, 0)
    bb(i, 4, 0) = 0.D0
    u0b = bb(i, 3, 0)
    v0b = -bb(i, 3, 0)
    bb(i, 3, 0) = 0.D0
    u2b = u2b + bb(i, 2, 0)
    v2b = v2b + bb(i, 2, 0)
    bb(i, 2, 0) = 0.D0
    u1b = u1b + bb(i, 1, 0)
    v1b = v1b - bb(i, 1, 0)
    bb(i, 1, 0) = 0.D0
    u0b = u0b + bb(i, 0, 0)
    v0b = v0b + bb(i, 0, 0)
    bb(i, 0, 0) = 0.D0
    t2b = v1b + v2b
    t3b = v1b - v2b
    ab(i, 0, 3) = ab(i, 0, 3) + v0b
    t1b = v0b - 0.5d0*t2b
    ab(i, 0, 5) = ab(i, 0, 5) - sin60*t3b
    ab(i, 0, 3) = ab(i, 0, 3) + t2b
    ab(i, 0, 1) = ab(i, 0, 1) + t1b
    t2b = u1b + u2b
    t3b = u1b - u2b
    ab(i, 0, 0) = ab(i, 0, 0) + u0b
    t1b = u0b - 0.5d0*t2b
    ab(i, 0, 4) = ab(i, 0, 4) + sin60*t3b
    ab(i, 0, 0) = ab(i, 0, 0) + t2b
    ab(i, 0, 2) = ab(i, 0, 2) + t1b
  END DO
END SUBROUTINE C06FQS_B
