!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpt in reverse (adjoint) mode:
!   gradient     of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FPT_B(a, ab, b, bb, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-695 (DEC 1989).
!
!     Radix five real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: r54, sin72, s36s72
  PARAMETER (r54=0.559016994374947424102293417182819d0, sin72=&
&   0.951056516295153572116439333379382d0, s36s72=&
&   0.618033988749894848204586834365638d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:4, 0:r-1), b(0:p-1, 0:r-1, 0:4), cosine&
& (0:r-1, 4), sine(0:r-1, 4)
  DOUBLE PRECISION :: ab(0:p-1, 0:4, 0:r-1), bb(0:p-1, 0:r-1, 0:4)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, c4k, ck, s2k, s3k, s4k, sk, t1, t10i, &
& t10r, t11i, t11r, t1i, t1r, t2, t2i, t2r, t3, t3i, t3r, t4, t4i, t4r, &
& t5, t5i, t5r, t6, t6i, t6r, t7, t7i, t7r, t8i, t8r, t9i, t9r, x1p, x2p&
& , x3p, x4p, y1p, y2p, y3p, y4p
  DOUBLE PRECISION :: t1b, t10ib, t10rb, t11ib, t11rb, t1ib, t1rb, t2b, &
& t2ib, t2rb, t3b, t3ib, t3rb, t4b, t4ib, t4rb, t5b, t5ib, t5rb, t6b, &
& t6ib, t6rb, t7b, t7ib, t7rb, t8ib, t8rb, t9ib, t9rb, x1pb, x2pb, x3pb&
& , x4pb, y1pb, y2pb, y3pb, y4pb
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!
!     Code for general K --
!
  IF (p .LE. (r-1)/2) THEN
    DO i=p-1,0,-1
      DO k=(r-1)/2,1,-1
        ab(i, 0, r-k) = ab(i, 0, r-k) + bb(i, r-k, 4)
        t5ib = bb(i, r-k, 4)
        bb(i, r-k, 4) = 0.D0
        t8ib = -bb(i, k, 4)
        t10rb = -bb(i, k, 4)
        bb(i, k, 4) = 0.D0
        t8ib = t8ib + bb(i, r-k, 3)
        t10rb = t10rb - bb(i, r-k, 3)
        bb(i, r-k, 3) = 0.D0
        t9ib = -bb(i, k, 3)
        t11rb = -bb(i, k, 3)
        bb(i, k, 3) = 0.D0
        t9ib = t9ib + bb(i, r-k, 2)
        t11rb = t11rb - bb(i, r-k, 2)
        bb(i, r-k, 2) = 0.D0
        t9rb = bb(i, k, 2)
        t11ib = bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        t9rb = t9rb + bb(i, r-k, 1)
        t11ib = t11ib - bb(i, r-k, 1)
        bb(i, r-k, 1) = 0.D0
        t8rb = bb(i, k, 1)
        t10ib = bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        t8rb = t8rb + bb(i, r-k, 0)
        t10ib = t10ib - bb(i, r-k, 0)
        bb(i, r-k, 0) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        t3ib = t10ib + s36s72*t11ib
        t4ib = s36s72*t10ib - t11ib
        t3rb = t10rb + s36s72*t11rb
        t4rb = s36s72*t10rb - t11rb
        t7ib = t8ib + t9ib
        t6ib = t8ib - t9ib
        t7rb = t8rb + t9rb
        t5rb = bb(i, k, 0) - 0.25d0*t7rb
        bb(i, k, 0) = 0.D0
        t6rb = t8rb - t9rb
        ab(i, 0, r-k) = ab(i, 0, r-k) + t7ib
        t5ib = t5ib - 0.25d0*t7ib
        ab(i, 0, k) = ab(i, 0, k) + t7rb
        t1ib = t5ib + r54*t6ib
        t2ib = t5ib - r54*t6ib
        t1rb = t5rb + r54*t6rb
        t2rb = t5rb - r54*t6rb
        y2pb = t2ib + sin72*t4ib
        y3pb = t2ib - sin72*t4ib
        x2pb = t2rb + sin72*t4rb
        x3pb = t2rb - sin72*t4rb
        y1pb = t1ib + sin72*t3ib
        y4pb = t1ib - sin72*t3ib
        x1pb = t1rb + sin72*t3rb
        x4pb = t1rb - sin72*t3rb
        ab(i, 4, r-k) = ab(i, 4, r-k) + cosine(k, 4)*y4pb
        ab(i, 4, k) = ab(i, 4, k) + cosine(k, 4)*x4pb + sine(k, 4)*y4pb
        ab(i, 4, r-k) = ab(i, 4, r-k) - sine(k, 4)*x4pb
        ab(i, 3, r-k) = ab(i, 3, r-k) + cosine(k, 3)*y3pb
        ab(i, 3, k) = ab(i, 3, k) + cosine(k, 3)*x3pb + sine(k, 3)*y3pb
        ab(i, 3, r-k) = ab(i, 3, r-k) - sine(k, 3)*x3pb
        ab(i, 2, r-k) = ab(i, 2, r-k) + cosine(k, 2)*y2pb
        ab(i, 2, k) = ab(i, 2, k) + cosine(k, 2)*x2pb + sine(k, 2)*y2pb
        ab(i, 2, r-k) = ab(i, 2, r-k) - sine(k, 2)*x2pb
        ab(i, 1, r-k) = ab(i, 1, r-k) + cosine(k, 1)*y1pb
        ab(i, 1, k) = ab(i, 1, k) + cosine(k, 1)*x1pb + sine(k, 1)*y1pb
        ab(i, 1, r-k) = ab(i, 1, r-k) - sine(k, 1)*x1pb
      END DO
    END DO
  ELSE
    DO k=(r-1)/2,1,-1
      s3k = sine(k, 3)
      c3k = cosine(k, 3)
      kp = r - k
      s4k = sine(k, 4)
      c4k = cosine(k, 4)
      sk = sine(k, 1)
      s2k = sine(k, 2)
      ck = cosine(k, 1)
      c2k = cosine(k, 2)
      DO i=p-1,0,-1
        ab(i, 0, kp) = ab(i, 0, kp) + bb(i, kp, 4)
        t5ib = bb(i, kp, 4)
        bb(i, kp, 4) = 0.D0
        t8ib = -bb(i, k, 4)
        t10rb = -bb(i, k, 4)
        bb(i, k, 4) = 0.D0
        t8ib = t8ib + bb(i, kp, 3)
        t10rb = t10rb - bb(i, kp, 3)
        bb(i, kp, 3) = 0.D0
        t9ib = -bb(i, k, 3)
        t11rb = -bb(i, k, 3)
        bb(i, k, 3) = 0.D0
        t9ib = t9ib + bb(i, kp, 2)
        t11rb = t11rb - bb(i, kp, 2)
        bb(i, kp, 2) = 0.D0
        t9rb = bb(i, k, 2)
        t11ib = bb(i, k, 2)
        bb(i, k, 2) = 0.D0
        t9rb = t9rb + bb(i, kp, 1)
        t11ib = t11ib - bb(i, kp, 1)
        bb(i, kp, 1) = 0.D0
        t8rb = bb(i, k, 1)
        t10ib = bb(i, k, 1)
        bb(i, k, 1) = 0.D0
        t8rb = t8rb + bb(i, kp, 0)
        t10ib = t10ib - bb(i, kp, 0)
        bb(i, kp, 0) = 0.D0
        ab(i, 0, k) = ab(i, 0, k) + bb(i, k, 0)
        t3ib = t10ib + s36s72*t11ib
        t4ib = s36s72*t10ib - t11ib
        t3rb = t10rb + s36s72*t11rb
        t4rb = s36s72*t10rb - t11rb
        t7ib = t8ib + t9ib
        t6ib = t8ib - t9ib
        t7rb = t8rb + t9rb
        t5rb = bb(i, k, 0) - 0.25d0*t7rb
        bb(i, k, 0) = 0.D0
        t6rb = t8rb - t9rb
        ab(i, 0, kp) = ab(i, 0, kp) + t7ib
        t5ib = t5ib - 0.25d0*t7ib
        ab(i, 0, k) = ab(i, 0, k) + t7rb
        t1ib = t5ib + r54*t6ib
        t2ib = t5ib - r54*t6ib
        t1rb = t5rb + r54*t6rb
        t2rb = t5rb - r54*t6rb
        y2pb = t2ib + sin72*t4ib
        y3pb = t2ib - sin72*t4ib
        x2pb = t2rb + sin72*t4rb
        x3pb = t2rb - sin72*t4rb
        y1pb = t1ib + sin72*t3ib
        y4pb = t1ib - sin72*t3ib
        x1pb = t1rb + sin72*t3rb
        x4pb = t1rb - sin72*t3rb
        ab(i, 4, kp) = ab(i, 4, kp) + c4k*y4pb
        ab(i, 4, k) = ab(i, 4, k) + c4k*x4pb + s4k*y4pb
        ab(i, 4, kp) = ab(i, 4, kp) - s4k*x4pb
        ab(i, 3, kp) = ab(i, 3, kp) + c3k*y3pb
        ab(i, 3, k) = ab(i, 3, k) + c3k*x3pb + s3k*y3pb
        ab(i, 3, kp) = ab(i, 3, kp) - s3k*x3pb
        ab(i, 2, kp) = ab(i, 2, kp) + c2k*y2pb
        ab(i, 2, k) = ab(i, 2, k) + c2k*x2pb + s2k*y2pb
        ab(i, 2, kp) = ab(i, 2, kp) - s2k*x2pb
        ab(i, 1, kp) = ab(i, 1, kp) + ck*y1pb
        ab(i, 1, k) = ab(i, 1, k) + ck*x1pb + sk*y1pb
        ab(i, 1, kp) = ab(i, 1, kp) - sk*x1pb
      END DO
    END DO
  END IF
  DO i=p-1,0,-1
    t3b = -bb(i, 0, 4)
    t4b = -(s36s72*bb(i, 0, 4))
    bb(i, 0, 4) = 0.D0
    t4b = t4b + bb(i, 0, 3)
    t3b = t3b - s36s72*bb(i, 0, 3)
    bb(i, 0, 3) = 0.D0
    t7b = bb(i, 0, 2)
    t6b = -bb(i, 0, 2)
    bb(i, 0, 2) = 0.D0
    t7b = t7b + bb(i, 0, 1)
    t6b = t6b + bb(i, 0, 1)
    bb(i, 0, 1) = 0.D0
    ab(i, 0, 0) = ab(i, 0, 0) + t7b + bb(i, 0, 0)
    t5b = bb(i, 0, 0) - 0.25d0*t7b
    bb(i, 0, 0) = 0.D0
    t1b = t5b + r54*t6b
    t2b = t5b - r54*t6b
    ab(i, 2, 0) = ab(i, 2, 0) + sin72*t4b
    ab(i, 3, 0) = ab(i, 3, 0) - sin72*t4b
    ab(i, 1, 0) = ab(i, 1, 0) + sin72*t3b
    ab(i, 4, 0) = ab(i, 4, 0) - sin72*t3b
    ab(i, 2, 0) = ab(i, 2, 0) + t2b
    ab(i, 3, 0) = ab(i, 3, 0) + t2b
    ab(i, 1, 0) = ab(i, 1, 0) + t1b
    ab(i, 4, 0) = ab(i, 4, 0) + t1b
  END DO
END SUBROUTINE C06FPT_B
