!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpv in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FPV_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-697 (DEC 1989).
!
!     Radix three Real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:2, 0:r-1), b(0:p-1, 0:r-1, 0:2), cosine&
& (0:r-1, 2), sine(0:r-1, 2)
  DOUBLE PRECISION :: ad(0:p-1, 0:2, 0:r-1), bd(0:p-1, 0:r-1, 0:2)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, ck, s2k, sk, t1, t1i, t1r, t2i, t2r, t3i, t3r&
& , x1p, x2p, y1p, y2p
  DOUBLE PRECISION :: t1d, t1id, t1rd, t2id, t2rd, t3id, t3rd, x1pd, &
& x2pd, y1pd, y2pd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    t1d = ad(i, 1, 0) + ad(i, 2, 0)
    t1 = a(i, 1, 0) + a(i, 2, 0)
    bd(i, 0, 0) = ad(i, 0, 0) + t1d
    b(i, 0, 0) = a(i, 0, 0) + t1
    bd(i, 0, 1) = ad(i, 0, 0) - 0.5d0*t1d
    b(i, 0, 1) = a(i, 0, 0) - 0.5d0*t1
    bd(i, 0, 2) = -(sin60*(ad(i, 1, 0)-ad(i, 2, 0)))
    b(i, 0, 2) = -(sin60*(a(i, 1, 0)-a(i, 2, 0)))
  END DO
!
!     Code for general K
!
  IF (p .LE. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        x1pd = cosine(k, 1)*ad(i, 1, k) - sine(k, 1)*ad(i, 1, r-k)
        x1p = cosine(k, 1)*a(i, 1, k) - sine(k, 1)*a(i, 1, r-k)
        y1pd = cosine(k, 1)*ad(i, 1, r-k) + sine(k, 1)*ad(i, 1, k)
        y1p = cosine(k, 1)*a(i, 1, r-k) + sine(k, 1)*a(i, 1, k)
        x2pd = cosine(k, 2)*ad(i, 2, k) - sine(k, 2)*ad(i, 2, r-k)
        x2p = cosine(k, 2)*a(i, 2, k) - sine(k, 2)*a(i, 2, r-k)
        y2pd = cosine(k, 2)*ad(i, 2, r-k) + sine(k, 2)*ad(i, 2, k)
        y2p = cosine(k, 2)*a(i, 2, r-k) + sine(k, 2)*a(i, 2, k)
        t1rd = x1pd + x2pd
        t1r = x1p + x2p
        t1id = y1pd + y2pd
        t1i = y1p + y2p
        t2rd = ad(i, 0, k) - 0.5d0*t1rd
        t2r = a(i, 0, k) - 0.5d0*t1r
        t2id = ad(i, 0, r-k) - 0.5d0*t1id
        t2i = a(i, 0, r-k) - 0.5d0*t1i
        t3rd = sin60*(x1pd-x2pd)
        t3r = sin60*(x1p-x2p)
        t3id = sin60*(y1pd-y2pd)
        t3i = sin60*(y1p-y2p)
        bd(i, k, 0) = ad(i, 0, k) + t1rd
        b(i, k, 0) = a(i, 0, k) + t1r
        bd(i, r-k, 0) = t2rd - t3id
        b(i, r-k, 0) = t2r - t3i
        bd(i, k, 1) = t2rd + t3id
        b(i, k, 1) = t2r + t3i
        bd(i, r-k, 1) = t2id - t3rd
        b(i, r-k, 1) = t2i - t3r
        bd(i, k, 2) = -(t2id+t3rd)
        b(i, k, 2) = -(t2i+t3r)
        bd(i, r-k, 2) = ad(i, 0, r-k) + t1id
        b(i, r-k, 2) = a(i, 0, r-k) + t1i
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k, 1)
      sk = sine(k, 1)
      c2k = cosine(k, 2)
      s2k = sine(k, 2)
      DO i=0,p-1
        x1pd = ck*ad(i, 1, k) - sk*ad(i, 1, kp)
        x1p = ck*a(i, 1, k) - sk*a(i, 1, kp)
        y1pd = ck*ad(i, 1, kp) + sk*ad(i, 1, k)
        y1p = ck*a(i, 1, kp) + sk*a(i, 1, k)
        x2pd = c2k*ad(i, 2, k) - s2k*ad(i, 2, kp)
        x2p = c2k*a(i, 2, k) - s2k*a(i, 2, kp)
        y2pd = c2k*ad(i, 2, kp) + s2k*ad(i, 2, k)
        y2p = c2k*a(i, 2, kp) + s2k*a(i, 2, k)
        t1rd = x1pd + x2pd
        t1r = x1p + x2p
        t1id = y1pd + y2pd
        t1i = y1p + y2p
        t2rd = ad(i, 0, k) - 0.5d0*t1rd
        t2r = a(i, 0, k) - 0.5d0*t1r
        t2id = ad(i, 0, kp) - 0.5d0*t1id
        t2i = a(i, 0, kp) - 0.5d0*t1i
        t3rd = sin60*(x1pd-x2pd)
        t3r = sin60*(x1p-x2p)
        t3id = sin60*(y1pd-y2pd)
        t3i = sin60*(y1p-y2p)
        bd(i, k, 0) = ad(i, 0, k) + t1rd
        b(i, k, 0) = a(i, 0, k) + t1r
        bd(i, kp, 0) = t2rd - t3id
        b(i, kp, 0) = t2r - t3i
        bd(i, k, 1) = t2rd + t3id
        b(i, k, 1) = t2r + t3i
        bd(i, kp, 1) = t2id - t3rd
        b(i, kp, 1) = t2i - t3r
        bd(i, k, 2) = -(t2id+t3rd)
        b(i, k, 2) = -(t2i+t3r)
        bd(i, kp, 2) = ad(i, 0, kp) + t1id
        b(i, kp, 2) = a(i, 0, kp) + t1i
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even not needed
!
!     IF (MOD(R,2).EQ.0) THEN
!        R2 = R/2
!        DO 120 I = 0, P - 1
!           T1 = A(I,1,R2) - A(I,2,R2)
!           B(I,R2,0) = A(I,0,R2) + 0.5D0*T1
!           B(I,R2,1) = A(I,0,R2) - T1
!           B(I,R2,2) = -SIN60*(A(I,1,R2)+A(I,2,R2))
! 120    CONTINUE
!     END IF
!
  RETURN
END SUBROUTINE C06FPV_D
