!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpr in forward (tangent) mode:
!   variations   of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FPR_D(a, ad, b, bd, p, q, r, cosine, sine)
  IMPLICIT NONE
!     MARK 15 RE-ISSUE. NAG COPYRIGHT 1991.
!
!     Real to Hermitian fast Fourier transform kernel
!     Odd factors greater than 6
!
!     Self-sorting, decimation in time
!
!     .. Scalar Arguments ..
  INTEGER :: p, q, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:q-1, 0:r-1), b(0:p-1, 0:r-1, 0:q-1), &
& cosine(0:r-1, q-1), sine(0:r-1, q-1)
  DOUBLE PRECISION :: ad(0:p-1, 0:q-1, 0:r-1), bd(0:p-1, 0:r-1, 0:q-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: ai, ar, temp1, temp2, temp3, temp4
  DOUBLE PRECISION :: aid, ard, temp1d, temp2d, temp3d, temp4d
  INTEGER :: i, indx, j, k, kp, l, q2, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
!
  q2 = (q-1)/2
  IF (p .GE. r/2) THEN
!
!        Code for K=0 --
!
    DO j=1,q2
      DO i=0,p-1
        temp1d = ad(i, j, 0)
        temp1 = a(i, j, 0)
        ad(i, j, 0) = temp1d + ad(i, q-j, 0)
        a(i, j, 0) = temp1 + a(i, q-j, 0)
        ad(i, q-j, 0) = temp1d - ad(i, q-j, 0)
        a(i, q-j, 0) = temp1 - a(i, q-j, 0)
      END DO
    END DO
    DO l=1,q2
      DO i=0,p-1
        bd(i, 0, l) = ad(i, 0, 0)
        b(i, 0, l) = a(i, 0, 0)
        bd(i, 0, q-l) = 0.D0
        b(i, 0, q-l) = 0.0d0
      END DO
      DO j=1,q2
        indx = MOD(j*l, q)
        DO i=0,p-1
          bd(i, 0, l) = bd(i, 0, l) + cosine(0, indx)*ad(i, j, 0)
          b(i, 0, l) = b(i, 0, l) + a(i, j, 0)*cosine(0, indx)
          bd(i, 0, q-l) = bd(i, 0, q-l) + sine(0, indx)*ad(i, q-j, 0)
          b(i, 0, q-l) = b(i, 0, q-l) + a(i, q-j, 0)*sine(0, indx)
        END DO
      END DO
    END DO
    DO i=0,p-1
      bd(i, 0, 0) = ad(i, 0, 0)
      b(i, 0, 0) = a(i, 0, 0)
    END DO
    DO j=1,q2
      DO i=0,p-1
        bd(i, 0, 0) = bd(i, 0, 0) + ad(i, j, 0)
        b(i, 0, 0) = b(i, 0, 0) + a(i, j, 0)
      END DO
    END DO
!
!        Code for general K --
!
    DO k=1,(r-1)/2
      kp = r - k
      DO j=1,q-1
        DO i=0,p-1
          ard = ad(i, j, k)
          ar = a(i, j, k)
          aid = ad(i, j, kp)
          ai = a(i, j, kp)
          ad(i, j, k) = cosine(k, j)*ard - sine(k, j)*aid
          a(i, j, k) = cosine(k, j)*ar - sine(k, j)*ai
          ad(i, j, kp) = cosine(k, j)*aid + sine(k, j)*ard
          a(i, j, kp) = cosine(k, j)*ai + sine(k, j)*ar
        END DO
      END DO
      DO j=1,q2
        DO i=0,p-1
          temp1d = ad(i, j, k)
          temp1 = a(i, j, k)
          temp2d = ad(i, j, kp)
          temp2 = a(i, j, kp)
          ad(i, j, k) = temp1d + ad(i, q-j, k)
          a(i, j, k) = temp1 + a(i, q-j, k)
          ad(i, j, kp) = temp2d + ad(i, q-j, kp)
          a(i, j, kp) = temp2 + a(i, q-j, kp)
          ad(i, q-j, k) = temp1d - ad(i, q-j, k)
          a(i, q-j, k) = temp1 - a(i, q-j, k)
          ad(i, q-j, kp) = temp2d - ad(i, q-j, kp)
          a(i, q-j, kp) = temp2 - a(i, q-j, kp)
        END DO
      END DO
      DO l=1,q2
        DO i=0,p-1
          bd(i, k, l) = ad(i, 0, k)
          b(i, k, l) = a(i, 0, k)
          bd(i, kp, q-l-1) = ad(i, 0, kp)
          b(i, kp, q-l-1) = a(i, 0, kp)
          bd(i, kp, l-1) = 0.D0
          b(i, kp, l-1) = 0.0d0
          bd(i, k, q-l) = 0.D0
          b(i, k, q-l) = 0.0d0
        END DO
        DO j=1,q2
          indx = MOD(j*l, q)
          DO i=0,p-1
            bd(i, k, l) = bd(i, k, l) + cosine(0, indx)*ad(i, j, k)
            b(i, k, l) = b(i, k, l) + a(i, j, k)*cosine(0, indx)
            bd(i, kp, q-l-1) = bd(i, kp, q-l-1) + cosine(0, indx)*ad(i, &
&             j, kp)
            b(i, kp, q-l-1) = b(i, kp, q-l-1) + a(i, j, kp)*cosine(0, &
&             indx)
            bd(i, kp, l-1) = bd(i, kp, l-1) - sine(0, indx)*ad(i, q-j, k&
&             )
            b(i, kp, l-1) = b(i, kp, l-1) - a(i, q-j, k)*sine(0, indx)
            bd(i, k, q-l) = bd(i, k, q-l) + sine(0, indx)*ad(i, q-j, kp)
            b(i, k, q-l) = b(i, k, q-l) + a(i, q-j, kp)*sine(0, indx)
          END DO
        END DO
      END DO
      DO i=0,p-1
        bd(i, k, 0) = ad(i, 0, k)
        b(i, k, 0) = a(i, 0, k)
        bd(i, kp, q-1) = ad(i, 0, kp)
        b(i, kp, q-1) = a(i, 0, kp)
      END DO
      DO j=1,q2
        DO i=0,p-1
          bd(i, k, 0) = bd(i, k, 0) + ad(i, j, k)
          b(i, k, 0) = b(i, k, 0) + a(i, j, k)
          bd(i, kp, q-1) = bd(i, kp, q-1) + ad(i, j, kp)
          b(i, kp, q-1) = b(i, kp, q-1) + a(i, j, kp)
        END DO
      END DO
      DO l=1,q2
        DO i=0,p-1
          temp1d = bd(i, k, l)
          temp1 = b(i, k, l)
          temp2d = bd(i, kp, q-l-1)
          temp2 = b(i, kp, q-l-1)
          temp3d = bd(i, kp, l-1)
          temp3 = b(i, kp, l-1)
          bd(i, k, l) = temp1d - bd(i, k, q-l)
          b(i, k, l) = temp1 - b(i, k, q-l)
          bd(i, kp, l-1) = temp1d + bd(i, k, q-l)
          b(i, kp, l-1) = temp1 + b(i, k, q-l)
          bd(i, kp, q-l-1) = temp2d - temp3d
          b(i, kp, q-l-1) = temp2 - temp3
          bd(i, k, q-l) = -temp2d - temp3d
          b(i, k, q-l) = -temp2 - temp3
        END DO
      END DO
    END DO
!
!        Code for K=R/2 if R is even --
!
    IF (MOD(r, 2) .EQ. 0) THEN
      r2 = r/2
      DO j=1,q2-1,2
        DO i=0,p-1
          temp1d = ad(i, j, r2)
          temp1 = a(i, j, r2)
          temp2d = ad(i, q-j, r2)
          temp2 = a(i, q-j, r2)
          ad(i, j, r2) = temp2d - temp1d
          a(i, j, r2) = -temp1 + temp2
          ad(i, q-j, r2) = -temp1d - temp2d
          a(i, q-j, r2) = -temp1 - temp2
          temp3d = ad(i, j+1, r2)
          temp3 = a(i, j+1, r2)
          temp4d = ad(i, q-j-1, r2)
          temp4 = a(i, q-j-1, r2)
          ad(i, j+1, r2) = temp3d - temp4d
          a(i, j+1, r2) = temp3 - temp4
          ad(i, q-j-1, r2) = temp3d + temp4d
          a(i, q-j-1, r2) = temp3 + temp4
        END DO
      END DO
      IF (MOD(q2, 2) .EQ. 1) THEN
        DO i=0,p-1
          temp1d = ad(i, q2, r2)
          temp1 = a(i, q2, r2)
          temp2d = ad(i, q2+1, r2)
          temp2 = a(i, q2+1, r2)
          ad(i, q2, r2) = temp2d - temp1d
          a(i, q2, r2) = -temp1 + temp2
          ad(i, q2+1, r2) = -temp1d - temp2d
          a(i, q2+1, r2) = -temp1 - temp2
        END DO
      END IF
      DO l=0,q2-1
        DO i=0,p-1
          bd(i, r2, l) = ad(i, 0, r2)
          b(i, r2, l) = a(i, 0, r2)
          bd(i, r2, q-l-1) = 0.D0
          b(i, r2, q-l-1) = 0.0d0
        END DO
        DO j=1,q2
          indx = MOD(j*(l+q2+1), q)
          DO i=0,p-1
            bd(i, r2, l) = bd(i, r2, l) + cosine(0, indx)*ad(i, j, r2)
            b(i, r2, l) = b(i, r2, l) + a(i, j, r2)*cosine(0, indx)
            bd(i, r2, q-l-1) = bd(i, r2, q-l-1) + sine(0, indx)*ad(i, q-&
&             j, r2)
            b(i, r2, q-l-1) = b(i, r2, q-l-1) + a(i, q-j, r2)*sine(0, &
&             indx)
          END DO
        END DO
      END DO
      DO i=0,p-1
        bd(i, r2, q2) = ad(i, 0, r2)
        b(i, r2, q2) = a(i, 0, r2)
      END DO
      DO j=1,q2
        DO i=0,p-1
          bd(i, r2, q2) = bd(i, r2, q2) + ad(i, j, r2)
          b(i, r2, q2) = b(i, r2, q2) + a(i, j, r2)
        END DO
      END DO
    END IF
  ELSE
!
!
    DO i=0,p-1
!
!           Code for K=0 --
!
      DO j=1,q2
        temp1d = ad(i, j, 0)
        temp1 = a(i, j, 0)
        ad(i, j, 0) = temp1d + ad(i, q-j, 0)
        a(i, j, 0) = temp1 + a(i, q-j, 0)
        ad(i, q-j, 0) = temp1d - ad(i, q-j, 0)
        a(i, q-j, 0) = temp1 - a(i, q-j, 0)
      END DO
      DO l=1,q2
        bd(i, 0, l) = ad(i, 0, 0)
        b(i, 0, l) = a(i, 0, 0)
        bd(i, 0, q-l) = 0.D0
        b(i, 0, q-l) = 0.0d0
        DO j=1,q2
          indx = MOD(j*l, q)
          bd(i, 0, l) = bd(i, 0, l) + cosine(0, indx)*ad(i, j, 0)
          b(i, 0, l) = b(i, 0, l) + a(i, j, 0)*cosine(0, indx)
          bd(i, 0, q-l) = bd(i, 0, q-l) + sine(0, indx)*ad(i, q-j, 0)
          b(i, 0, q-l) = b(i, 0, q-l) + a(i, q-j, 0)*sine(0, indx)
        END DO
      END DO
      bd(i, 0, 0) = ad(i, 0, 0)
      b(i, 0, 0) = a(i, 0, 0)
      DO j=1,q2
        bd(i, 0, 0) = bd(i, 0, 0) + ad(i, j, 0)
        b(i, 0, 0) = b(i, 0, 0) + a(i, j, 0)
      END DO
!
!           Code for general K --
!
      DO j=1,q-1
        DO k=1,(r-1)/2
          ard = ad(i, j, k)
          ar = a(i, j, k)
          aid = ad(i, j, r-k)
          ai = a(i, j, r-k)
          ad(i, j, k) = cosine(k, j)*ard - sine(k, j)*aid
          a(i, j, k) = cosine(k, j)*ar - sine(k, j)*ai
          ad(i, j, r-k) = cosine(k, j)*aid + sine(k, j)*ard
          a(i, j, r-k) = cosine(k, j)*ai + sine(k, j)*ar
        END DO
      END DO
      DO j=1,q2
        DO k=1,(r-1)/2
          temp1d = ad(i, j, k)
          temp1 = a(i, j, k)
          temp2d = ad(i, j, r-k)
          temp2 = a(i, j, r-k)
          ad(i, j, k) = temp1d + ad(i, q-j, k)
          a(i, j, k) = temp1 + a(i, q-j, k)
          ad(i, j, r-k) = temp2d + ad(i, q-j, r-k)
          a(i, j, r-k) = temp2 + a(i, q-j, r-k)
          ad(i, q-j, k) = temp1d - ad(i, q-j, k)
          a(i, q-j, k) = temp1 - a(i, q-j, k)
          ad(i, q-j, r-k) = temp2d - ad(i, q-j, r-k)
          a(i, q-j, r-k) = temp2 - a(i, q-j, r-k)
        END DO
      END DO
      DO l=1,q2
        DO k=1,(r-1)/2
          bd(i, k, l) = ad(i, 0, k)
          b(i, k, l) = a(i, 0, k)
          bd(i, r-k, q-l-1) = ad(i, 0, r-k)
          b(i, r-k, q-l-1) = a(i, 0, r-k)
          bd(i, r-k, l-1) = 0.D0
          b(i, r-k, l-1) = 0.0d0
          bd(i, k, q-l) = 0.D0
          b(i, k, q-l) = 0.0d0
        END DO
        DO j=1,q2
          indx = MOD(j*l, q)
          DO k=1,(r-1)/2
            bd(i, k, l) = bd(i, k, l) + cosine(0, indx)*ad(i, j, k)
            b(i, k, l) = b(i, k, l) + a(i, j, k)*cosine(0, indx)
            bd(i, r-k, q-l-1) = bd(i, r-k, q-l-1) + cosine(0, indx)*ad(i&
&             , j, r-k)
            b(i, r-k, q-l-1) = b(i, r-k, q-l-1) + a(i, j, r-k)*cosine(0&
&             , indx)
            bd(i, r-k, l-1) = bd(i, r-k, l-1) - sine(0, indx)*ad(i, q-j&
&             , k)
            b(i, r-k, l-1) = b(i, r-k, l-1) - a(i, q-j, k)*sine(0, indx)
            bd(i, k, q-l) = bd(i, k, q-l) + sine(0, indx)*ad(i, q-j, r-k&
&             )
            b(i, k, q-l) = b(i, k, q-l) + a(i, q-j, r-k)*sine(0, indx)
          END DO
        END DO
      END DO
      DO k=1,(r-1)/2
        bd(i, k, 0) = ad(i, 0, k)
        b(i, k, 0) = a(i, 0, k)
        bd(i, r-k, q-1) = ad(i, 0, r-k)
        b(i, r-k, q-1) = a(i, 0, r-k)
      END DO
      DO j=1,q2
        DO k=1,(r-1)/2
          bd(i, k, 0) = bd(i, k, 0) + ad(i, j, k)
          b(i, k, 0) = b(i, k, 0) + a(i, j, k)
          bd(i, r-k, q-1) = bd(i, r-k, q-1) + ad(i, j, r-k)
          b(i, r-k, q-1) = b(i, r-k, q-1) + a(i, j, r-k)
        END DO
      END DO
      DO l=1,q2
        DO k=1,(r-1)/2
          temp1d = bd(i, k, l)
          temp1 = b(i, k, l)
          temp2d = bd(i, r-k, q-l-1)
          temp2 = b(i, r-k, q-l-1)
          temp3d = bd(i, r-k, l-1)
          temp3 = b(i, r-k, l-1)
          bd(i, k, l) = temp1d - bd(i, k, q-l)
          b(i, k, l) = temp1 - b(i, k, q-l)
          bd(i, r-k, l-1) = temp1d + bd(i, k, q-l)
          b(i, r-k, l-1) = temp1 + b(i, k, q-l)
          bd(i, r-k, q-l-1) = temp2d - temp3d
          b(i, r-k, q-l-1) = temp2 - temp3
          bd(i, k, q-l) = -temp2d - temp3d
          b(i, k, q-l) = -temp2 - temp3
        END DO
      END DO
!
!           Code for K=R/2 if R is even --
!
      IF (MOD(r, 2) .EQ. 0) THEN
        r2 = r/2
        DO j=1,q2-1,2
          temp1d = ad(i, j, r2)
          temp1 = a(i, j, r2)
          temp2d = ad(i, q-j, r2)
          temp2 = a(i, q-j, r2)
          ad(i, j, r2) = temp2d - temp1d
          a(i, j, r2) = -temp1 + temp2
          ad(i, q-j, r2) = -temp1d - temp2d
          a(i, q-j, r2) = -temp1 - temp2
          temp3d = ad(i, j+1, r2)
          temp3 = a(i, j+1, r2)
          temp4d = ad(i, q-j-1, r2)
          temp4 = a(i, q-j-1, r2)
          ad(i, j+1, r2) = temp3d - temp4d
          a(i, j+1, r2) = temp3 - temp4
          ad(i, q-j-1, r2) = temp3d + temp4d
          a(i, q-j-1, r2) = temp3 + temp4
        END DO
        IF (MOD(q2, 2) .EQ. 1) THEN
          temp1d = ad(i, q2, r2)
          temp1 = a(i, q2, r2)
          temp2d = ad(i, q2+1, r2)
          temp2 = a(i, q2+1, r2)
          ad(i, q2, r2) = temp2d - temp1d
          a(i, q2, r2) = -temp1 + temp2
          ad(i, q2+1, r2) = -temp1d - temp2d
          a(i, q2+1, r2) = -temp1 - temp2
        END IF
        DO l=0,q2-1
          bd(i, r2, l) = ad(i, 0, r2)
          b(i, r2, l) = a(i, 0, r2)
          bd(i, r2, q-l-1) = 0.D0
          b(i, r2, q-l-1) = 0.0d0
          DO j=1,q2
            indx = MOD(j*(l+q2+1), q)
            bd(i, r2, l) = bd(i, r2, l) + cosine(0, indx)*ad(i, j, r2)
            b(i, r2, l) = b(i, r2, l) + a(i, j, r2)*cosine(0, indx)
            bd(i, r2, q-l-1) = bd(i, r2, q-l-1) + sine(0, indx)*ad(i, q-&
&             j, r2)
            b(i, r2, q-l-1) = b(i, r2, q-l-1) + a(i, q-j, r2)*sine(0, &
&             indx)
          END DO
        END DO
        bd(i, r2, q2) = ad(i, 0, r2)
        b(i, r2, q2) = a(i, 0, r2)
        DO j=1,q2
          bd(i, r2, q2) = bd(i, r2, q2) + ad(i, j, r2)
          b(i, r2, q2) = b(i, r2, q2) + a(i, j, r2)
        END DO
      END IF
    END DO
  END IF
  RETURN
END SUBROUTINE C06FPR_D
