!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpu in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FPU_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-696 (DEC 1989).
!
!     Radix four real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: root2i
  PARAMETER (root2i=0.707106781186547524400844362104849d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:3, 0:r-1), b(0:p-1, 0:r-1, 0:3), cosine&
& (0:r-1, 3), sine(0:r-1, 3)
  DOUBLE PRECISION :: ad(0:p-1, 0:3, 0:r-1), bd(0:p-1, 0:r-1, 0:3)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, ck, s2k, s3k, sk, t1, t1i, t1r, t2, t2i&
& , t2r, t3i, t3r, t4i, t4r, x1p, x2p, x3p, y1p, y2p, y3p
  DOUBLE PRECISION :: t1d, t1id, t1rd, t2d, t2id, t2rd, t3id, t3rd, t4id&
& , t4rd, x1pd, x2pd, x3pd, y1pd, y2pd, y3pd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    t1d = ad(i, 0, 0) + ad(i, 2, 0)
    t1 = a(i, 0, 0) + a(i, 2, 0)
    t2d = ad(i, 1, 0) + ad(i, 3, 0)
    t2 = a(i, 1, 0) + a(i, 3, 0)
    bd(i, 0, 0) = t1d + t2d
    b(i, 0, 0) = t1 + t2
    bd(i, 0, 1) = ad(i, 0, 0) - ad(i, 2, 0)
    b(i, 0, 1) = a(i, 0, 0) - a(i, 2, 0)
    bd(i, 0, 2) = t1d - t2d
    b(i, 0, 2) = t1 - t2
    bd(i, 0, 3) = ad(i, 3, 0) - ad(i, 1, 0)
    b(i, 0, 3) = -a(i, 1, 0) + a(i, 3, 0)
  END DO
!
!     Code for general K --
!
  IF (p .LT. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        x1pd = cosine(k, 1)*ad(i, 1, k) - sine(k, 1)*ad(i, 1, r-k)
        x1p = cosine(k, 1)*a(i, 1, k) - sine(k, 1)*a(i, 1, r-k)
        y1pd = cosine(k, 1)*ad(i, 1, r-k) + sine(k, 1)*ad(i, 1, k)
        y1p = cosine(k, 1)*a(i, 1, r-k) + sine(k, 1)*a(i, 1, k)
        x2pd = cosine(k, 2)*ad(i, 2, k) - sine(k, 2)*ad(i, 2, r-k)
        x2p = cosine(k, 2)*a(i, 2, k) - sine(k, 2)*a(i, 2, r-k)
        y2pd = cosine(k, 2)*ad(i, 2, r-k) + sine(k, 2)*ad(i, 2, k)
        y2p = cosine(k, 2)*a(i, 2, r-k) + sine(k, 2)*a(i, 2, k)
        x3pd = cosine(k, 3)*ad(i, 3, k) - sine(k, 3)*ad(i, 3, r-k)
        x3p = cosine(k, 3)*a(i, 3, k) - sine(k, 3)*a(i, 3, r-k)
        y3pd = cosine(k, 3)*ad(i, 3, r-k) + sine(k, 3)*ad(i, 3, k)
        y3p = cosine(k, 3)*a(i, 3, r-k) + sine(k, 3)*a(i, 3, k)
        t1rd = ad(i, 0, k) + x2pd
        t1r = a(i, 0, k) + x2p
        t1id = ad(i, 0, r-k) + y2pd
        t1i = a(i, 0, r-k) + y2p
        t2rd = x1pd + x3pd
        t2r = x1p + x3p
        t2id = y1pd + y3pd
        t2i = y1p + y3p
        t3rd = ad(i, 0, k) - x2pd
        t3r = a(i, 0, k) - x2p
        t3id = ad(i, 0, r-k) - y2pd
        t3i = a(i, 0, r-k) - y2p
        t4rd = x1pd - x3pd
        t4r = x1p - x3p
        t4id = y1pd - y3pd
        t4i = y1p - y3p
        bd(i, k, 0) = t1rd + t2rd
        b(i, k, 0) = t1r + t2r
        bd(i, r-k, 0) = t3rd - t4id
        b(i, r-k, 0) = t3r - t4i
        bd(i, k, 1) = t3rd + t4id
        b(i, k, 1) = t3r + t4i
        bd(i, r-k, 1) = t1rd - t2rd
        b(i, r-k, 1) = t1r - t2r
        bd(i, k, 2) = t2id - t1id
        b(i, k, 2) = t2i - t1i
        bd(i, r-k, 2) = t3id - t4rd
        b(i, r-k, 2) = t3i - t4r
        bd(i, k, 3) = -t3id - t4rd
        b(i, k, 3) = -t3i - t4r
        bd(i, r-k, 3) = t1id + t2id
        b(i, r-k, 3) = t1i + t2i
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k, 1)
      sk = sine(k, 1)
      c2k = cosine(k, 2)
      s2k = sine(k, 2)
      c3k = cosine(k, 3)
      s3k = sine(k, 3)
      DO i=0,p-1
        x1pd = ck*ad(i, 1, k) - sk*ad(i, 1, kp)
        x1p = ck*a(i, 1, k) - sk*a(i, 1, kp)
        y1pd = ck*ad(i, 1, kp) + sk*ad(i, 1, k)
        y1p = ck*a(i, 1, kp) + sk*a(i, 1, k)
        x2pd = c2k*ad(i, 2, k) - s2k*ad(i, 2, kp)
        x2p = c2k*a(i, 2, k) - s2k*a(i, 2, kp)
        y2pd = c2k*ad(i, 2, kp) + s2k*ad(i, 2, k)
        y2p = c2k*a(i, 2, kp) + s2k*a(i, 2, k)
        x3pd = c3k*ad(i, 3, k) - s3k*ad(i, 3, kp)
        x3p = c3k*a(i, 3, k) - s3k*a(i, 3, kp)
        y3pd = c3k*ad(i, 3, kp) + s3k*ad(i, 3, k)
        y3p = c3k*a(i, 3, kp) + s3k*a(i, 3, k)
        t1rd = ad(i, 0, k) + x2pd
        t1r = a(i, 0, k) + x2p
        t1id = ad(i, 0, kp) + y2pd
        t1i = a(i, 0, kp) + y2p
        t2rd = x1pd + x3pd
        t2r = x1p + x3p
        t2id = y1pd + y3pd
        t2i = y1p + y3p
        t3rd = ad(i, 0, k) - x2pd
        t3r = a(i, 0, k) - x2p
        t3id = ad(i, 0, kp) - y2pd
        t3i = a(i, 0, kp) - y2p
        t4rd = x1pd - x3pd
        t4r = x1p - x3p
        t4id = y1pd - y3pd
        t4i = y1p - y3p
        bd(i, k, 0) = t1rd + t2rd
        b(i, k, 0) = t1r + t2r
        bd(i, kp, 0) = t3rd - t4id
        b(i, kp, 0) = t3r - t4i
        bd(i, k, 1) = t3rd + t4id
        b(i, k, 1) = t3r + t4i
        bd(i, kp, 1) = t1rd - t2rd
        b(i, kp, 1) = t1r - t2r
        bd(i, k, 2) = t2id - t1id
        b(i, k, 2) = t2i - t1i
        bd(i, kp, 2) = t3id - t4rd
        b(i, kp, 2) = t3i - t4r
        bd(i, k, 3) = -t3id - t4rd
        b(i, k, 3) = -t3i - t4r
        bd(i, kp, 3) = t1id + t2id
        b(i, kp, 3) = t1i + t2i
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=0,p-1
      t1d = root2i*(ad(i, 1, r2)-ad(i, 3, r2))
      t1 = root2i*(a(i, 1, r2)-a(i, 3, r2))
      t2d = root2i*(ad(i, 1, r2)+ad(i, 3, r2))
      t2 = root2i*(a(i, 1, r2)+a(i, 3, r2))
      bd(i, r2, 0) = ad(i, 0, r2) + t1d
      b(i, r2, 0) = a(i, 0, r2) + t1
      bd(i, r2, 1) = ad(i, 0, r2) - t1d
      b(i, r2, 1) = a(i, 0, r2) - t1
      bd(i, r2, 2) = ad(i, 2, r2) - t2d
      b(i, r2, 2) = a(i, 2, r2) - t2
      bd(i, r2, 3) = -ad(i, 2, r2) - t2d
      b(i, r2, 3) = -a(i, 2, r2) - t2
    END DO
  END IF
!
  RETURN
END SUBROUTINE C06FPU_D
