!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqu in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FQU_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-701 (DEC 1989).
!
!     Radix four Hermitian to real fast Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Parameters ..
  DOUBLE PRECISION :: root2i
  PARAMETER (root2i=0.707106781186547524400844362104849d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:3), b(0:p-1, 0:3, 0:r-1), cosine&
& (0:r-1, 3), sine(0:r-1, 3)
  DOUBLE PRECISION :: ad(0:p-1, 0:r-1, 0:3), bd(0:p-1, 0:3, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, ck, s2k, s3k, sk, t1, t1i, t1r, t2, t2i&
& , t2r, t3, t3i, t3r, t4, t4i, t4r, x0p, x1p, x2p, x3p, y0p, y1p, y2p, &
& y3p
  DOUBLE PRECISION :: t1d, t1id, t1rd, t2d, t2id, t2rd, t3d, t3id, t3rd&
& , t4d, t4id, t4rd, x0pd, x1pd, x2pd, x3pd, y0pd, y1pd, y2pd, y3pd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    t1d = ad(i, 0, 0) + ad(i, 0, 2)
    t1 = a(i, 0, 0) + a(i, 0, 2)
    t2d = ad(i, 0, 1)
    t2 = a(i, 0, 1)
    t3d = ad(i, 0, 0) - ad(i, 0, 2)
    t3 = a(i, 0, 0) - a(i, 0, 2)
    t4d = ad(i, 0, 3)
    t4 = a(i, 0, 3)
    bd(i, 0, 0) = t1d + t2d
    b(i, 0, 0) = t1 + t2
    bd(i, 1, 0) = t3d + t4d
    b(i, 1, 0) = t3 + t4
    bd(i, 2, 0) = t1d - t2d
    b(i, 2, 0) = t1 - t2
    bd(i, 3, 0) = t3d - t4d
    b(i, 3, 0) = t3 - t4
  END DO
!
!     Code for general K --
!
  IF (p .LT. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        t1rd = ad(i, k, 0) + ad(i, r-k, 1)
        t1r = a(i, k, 0) + a(i, r-k, 1)
        t1id = ad(i, r-k, 3) - ad(i, k, 2)
        t1i = a(i, r-k, 3) - a(i, k, 2)
        t2rd = ad(i, k, 1) + ad(i, r-k, 0)
        t2r = a(i, k, 1) + a(i, r-k, 0)
        t2id = ad(i, r-k, 2) - ad(i, k, 3)
        t2i = a(i, r-k, 2) - a(i, k, 3)
        t3rd = ad(i, k, 0) - ad(i, r-k, 1)
        t3r = a(i, k, 0) - a(i, r-k, 1)
        t3id = ad(i, r-k, 3) + ad(i, k, 2)
        t3i = a(i, r-k, 3) + a(i, k, 2)
        t4rd = ad(i, k, 1) - ad(i, r-k, 0)
        t4r = a(i, k, 1) - a(i, r-k, 0)
        t4id = ad(i, r-k, 2) + ad(i, k, 3)
        t4i = a(i, r-k, 2) + a(i, k, 3)
        x0pd = t1rd + t2rd
        x0p = t1r + t2r
        y0pd = t1id + t2id
        y0p = t1i + t2i
        x1pd = t3rd + t4id
        x1p = t3r + t4i
        y1pd = t3id - t4rd
        y1p = t3i - t4r
        x2pd = t1rd - t2rd
        x2p = t1r - t2r
        y2pd = t1id - t2id
        y2p = t1i - t2i
        x3pd = t3rd - t4id
        x3p = t3r - t4i
        y3pd = t3id + t4rd
        y3p = t3i + t4r
        bd(i, 0, k) = x0pd
        b(i, 0, k) = x0p
        bd(i, 0, r-k) = y0pd
        b(i, 0, r-k) = y0p
        bd(i, 1, k) = cosine(k, 1)*x1pd - sine(k, 1)*y1pd
        b(i, 1, k) = cosine(k, 1)*x1p - sine(k, 1)*y1p
        bd(i, 1, r-k) = cosine(k, 1)*y1pd + sine(k, 1)*x1pd
        b(i, 1, r-k) = cosine(k, 1)*y1p + sine(k, 1)*x1p
        bd(i, 2, k) = cosine(k, 2)*x2pd - sine(k, 2)*y2pd
        b(i, 2, k) = cosine(k, 2)*x2p - sine(k, 2)*y2p
        bd(i, 2, r-k) = cosine(k, 2)*y2pd + sine(k, 2)*x2pd
        b(i, 2, r-k) = cosine(k, 2)*y2p + sine(k, 2)*x2p
        bd(i, 3, k) = cosine(k, 3)*x3pd - sine(k, 3)*y3pd
        b(i, 3, k) = cosine(k, 3)*x3p - sine(k, 3)*y3p
        bd(i, 3, r-k) = cosine(k, 3)*y3pd + sine(k, 3)*x3pd
        b(i, 3, r-k) = cosine(k, 3)*y3p + sine(k, 3)*x3p
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k, 1)
      sk = sine(k, 1)
      c2k = cosine(k, 2)
      s2k = sine(k, 2)
      c3k = cosine(k, 3)
      s3k = sine(k, 3)
      DO i=0,p-1
        t1rd = ad(i, k, 0) + ad(i, kp, 1)
        t1r = a(i, k, 0) + a(i, kp, 1)
        t1id = ad(i, kp, 3) - ad(i, k, 2)
        t1i = a(i, kp, 3) - a(i, k, 2)
        t2rd = ad(i, k, 1) + ad(i, kp, 0)
        t2r = a(i, k, 1) + a(i, kp, 0)
        t2id = ad(i, kp, 2) - ad(i, k, 3)
        t2i = a(i, kp, 2) - a(i, k, 3)
        t3rd = ad(i, k, 0) - ad(i, kp, 1)
        t3r = a(i, k, 0) - a(i, kp, 1)
        t3id = ad(i, kp, 3) + ad(i, k, 2)
        t3i = a(i, kp, 3) + a(i, k, 2)
        t4rd = ad(i, k, 1) - ad(i, kp, 0)
        t4r = a(i, k, 1) - a(i, kp, 0)
        t4id = ad(i, kp, 2) + ad(i, k, 3)
        t4i = a(i, kp, 2) + a(i, k, 3)
        x0pd = t1rd + t2rd
        x0p = t1r + t2r
        y0pd = t1id + t2id
        y0p = t1i + t2i
        x1pd = t3rd + t4id
        x1p = t3r + t4i
        y1pd = t3id - t4rd
        y1p = t3i - t4r
        x2pd = t1rd - t2rd
        x2p = t1r - t2r
        y2pd = t1id - t2id
        y2p = t1i - t2i
        x3pd = t3rd - t4id
        x3p = t3r - t4i
        y3pd = t3id + t4rd
        y3p = t3i + t4r
        bd(i, 0, k) = x0pd
        b(i, 0, k) = x0p
        bd(i, 0, kp) = y0pd
        b(i, 0, kp) = y0p
        bd(i, 1, k) = ck*x1pd - sk*y1pd
        b(i, 1, k) = ck*x1p - sk*y1p
        bd(i, 1, kp) = ck*y1pd + sk*x1pd
        b(i, 1, kp) = ck*y1p + sk*x1p
        bd(i, 2, k) = c2k*x2pd - s2k*y2pd
        b(i, 2, k) = c2k*x2p - s2k*y2p
        bd(i, 2, kp) = c2k*y2pd + s2k*x2pd
        b(i, 2, kp) = c2k*y2p + s2k*x2p
        bd(i, 3, k) = c3k*x3pd - s3k*y3pd
        b(i, 3, k) = c3k*x3p - s3k*y3p
        bd(i, 3, kp) = c3k*y3pd + s3k*x3pd
        b(i, 3, kp) = c3k*y3p + s3k*x3p
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=0,p-1
      bd(i, 0, r2) = ad(i, r2, 0) + ad(i, r2, 1)
      b(i, 0, r2) = a(i, r2, 0) + a(i, r2, 1)
      bd(i, 2, r2) = ad(i, r2, 3) - ad(i, r2, 2)
      b(i, 2, r2) = a(i, r2, 3) - a(i, r2, 2)
      t3d = ad(i, r2, 0) - ad(i, r2, 1)
      t3 = a(i, r2, 0) - a(i, r2, 1)
      t4d = ad(i, r2, 3) + ad(i, r2, 2)
      t4 = a(i, r2, 3) + a(i, r2, 2)
      bd(i, 1, r2) = root2i*(t3d+t4d)
      b(i, 1, r2) = root2i*(t3+t4)
      bd(i, 3, r2) = -(root2i*(t3d-t4d))
      b(i, 3, r2) = -(root2i*(t3-t4))
    END DO
  END IF
!
  RETURN
END SUBROUTINE C06FQU_D
