!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqv in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FQV_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-702 (DEC 1989).
!
!     Radix three Hermitian to real Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:2), b(0:p-1, 0:2, 0:r-1), cosine&
& (0:r-1, 2), sine(0:r-1, 2)
  DOUBLE PRECISION :: ad(0:p-1, 0:r-1, 0:2), bd(0:p-1, 0:2, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, ck, s2k, sk, t1, t1i, t1r, t2, t2i, t2r, t3, &
& t3i, t3r, x0p, x1p, x2p, y0p, y1p, y2p
  DOUBLE PRECISION :: t1d, t1id, t1rd, t2d, t2id, t2rd, t3d, t3id, t3rd&
& , x0pd, x1pd, x2pd, y0pd, y1pd, y2pd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    t1d = ad(i, 0, 1)
    t1 = a(i, 0, 1)
    t2d = ad(i, 0, 0) - 0.5d0*t1d
    t2 = a(i, 0, 0) - 0.5d0*t1
    t3d = sin60*ad(i, 0, 2)
    t3 = sin60*a(i, 0, 2)
    bd(i, 0, 0) = ad(i, 0, 0) + t1d
    b(i, 0, 0) = a(i, 0, 0) + t1
    bd(i, 1, 0) = t2d + t3d
    b(i, 1, 0) = t2 + t3
    bd(i, 2, 0) = t2d - t3d
    b(i, 2, 0) = t2 - t3
  END DO
!
!     Code for general K
!
  IF (p .LE. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        t1rd = ad(i, k, 1) + ad(i, r-k, 0)
        t1r = a(i, k, 1) + a(i, r-k, 0)
        t1id = ad(i, r-k, 1) - ad(i, k, 2)
        t1i = a(i, r-k, 1) - a(i, k, 2)
        t2rd = ad(i, k, 0) - 0.5d0*t1rd
        t2r = a(i, k, 0) - 0.5d0*t1r
        t2id = ad(i, r-k, 2) - 0.5d0*t1id
        t2i = a(i, r-k, 2) - 0.5d0*t1i
        t3rd = sin60*(ad(i, k, 1)-ad(i, r-k, 0))
        t3r = sin60*(a(i, k, 1)-a(i, r-k, 0))
        t3id = sin60*(ad(i, r-k, 1)+ad(i, k, 2))
        t3i = sin60*(a(i, r-k, 1)+a(i, k, 2))
        x0pd = ad(i, k, 0) + t1rd
        x0p = a(i, k, 0) + t1r
        y0pd = ad(i, r-k, 2) + t1id
        y0p = a(i, r-k, 2) + t1i
        x1pd = t2rd + t3id
        x1p = t2r + t3i
        y1pd = t2id - t3rd
        y1p = t2i - t3r
        x2pd = t2rd - t3id
        x2p = t2r - t3i
        y2pd = t2id + t3rd
        y2p = t2i + t3r
        bd(i, 0, k) = x0pd
        b(i, 0, k) = x0p
        bd(i, 0, r-k) = y0pd
        b(i, 0, r-k) = y0p
        bd(i, 1, k) = cosine(k, 1)*x1pd - sine(k, 1)*y1pd
        b(i, 1, k) = cosine(k, 1)*x1p - sine(k, 1)*y1p
        bd(i, 1, r-k) = sine(k, 1)*x1pd + cosine(k, 1)*y1pd
        b(i, 1, r-k) = sine(k, 1)*x1p + cosine(k, 1)*y1p
        bd(i, 2, k) = cosine(k, 2)*x2pd - sine(k, 2)*y2pd
        b(i, 2, k) = cosine(k, 2)*x2p - sine(k, 2)*y2p
        bd(i, 2, r-k) = sine(k, 2)*x2pd + cosine(k, 2)*y2pd
        b(i, 2, r-k) = sine(k, 2)*x2p + cosine(k, 2)*y2p
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k, 1)
      sk = sine(k, 1)
      c2k = cosine(k, 2)
      s2k = sine(k, 2)
      DO i=0,p-1
        t1rd = ad(i, k, 1) + ad(i, kp, 0)
        t1r = a(i, k, 1) + a(i, kp, 0)
        t1id = ad(i, kp, 1) - ad(i, k, 2)
        t1i = a(i, kp, 1) - a(i, k, 2)
        t2rd = ad(i, k, 0) - 0.5d0*t1rd
        t2r = a(i, k, 0) - 0.5d0*t1r
        t2id = ad(i, kp, 2) - 0.5d0*t1id
        t2i = a(i, kp, 2) - 0.5d0*t1i
        t3rd = sin60*(ad(i, k, 1)-ad(i, kp, 0))
        t3r = sin60*(a(i, k, 1)-a(i, kp, 0))
        t3id = sin60*(ad(i, kp, 1)+ad(i, k, 2))
        t3i = sin60*(a(i, kp, 1)+a(i, k, 2))
        x0pd = ad(i, k, 0) + t1rd
        x0p = a(i, k, 0) + t1r
        y0pd = ad(i, kp, 2) + t1id
        y0p = a(i, kp, 2) + t1i
        x1pd = t2rd + t3id
        x1p = t2r + t3i
        y1pd = t2id - t3rd
        y1p = t2i - t3r
        x2pd = t2rd - t3id
        x2p = t2r - t3i
        y2pd = t2id + t3rd
        y2p = t2i + t3r
        bd(i, 0, k) = x0pd
        b(i, 0, k) = x0p
        bd(i, 0, kp) = y0pd
        b(i, 0, kp) = y0p
        bd(i, 1, k) = ck*x1pd - sk*y1pd
        b(i, 1, k) = ck*x1p - sk*y1p
        bd(i, 1, kp) = sk*x1pd + ck*y1pd
        b(i, 1, kp) = sk*x1p + ck*y1p
        bd(i, 2, k) = c2k*x2pd - s2k*y2pd
        b(i, 2, k) = c2k*x2p - s2k*y2p
        bd(i, 2, kp) = s2k*x2pd + c2k*y2pd
        b(i, 2, kp) = s2k*x2p + c2k*y2p
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even not needed
!
!     IF (MOD(R,2).EQ.0) THEN
!        R2 = R/2
!        DO 120 I = 0, P - 1
!           T1 = A(I,R2,0) + A(I,R2,1)
!           T2 = 0.5D0*A(I,R2,0) - A(I,R2,1)
!           T3 = SIN60*A(I,R2,2)
!           B(I,0,R2) = T1
!           B(I,1,R2) = T2 + T3
!           B(I,2,R2) = -T2 + T3
! 120    CONTINUE
!     END IF
!
  RETURN
END SUBROUTINE C06FQV_D
