!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqr in forward (tangent) mode:
!   variations   of useful results: a b
!   with respect to varying inputs: a b
SUBROUTINE C06FQR_D(a, ad, b, bd, p, q, r, cosine, sine)
  IMPLICIT NONE
!     MARK 15 RE-ISSUE. NAG COPYRIGHT 1991.
!
!     Hermitian to real fast Fourier transform kernel
!     Odd factors greater than 6
!
!     Self-sorting, decimation in frequency
!
!     .. Scalar Arguments ..
  INTEGER :: p, q, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:q-1), b(0:p-1, 0:q-1, 0:r-1), &
& cosine(0:r-1, q-1), sine(0:r-1, q-1)
  DOUBLE PRECISION :: ad(0:p-1, 0:r-1, 0:q-1), bd(0:p-1, 0:q-1, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: bi, br, temp, temp1, tempi, tempr
  DOUBLE PRECISION :: bid, brd, tempd, temp1d, tempid, temprd
  INTEGER :: i, indx, j, k, kp, l, q2, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
!
  q2 = (q-1)/2
  IF (p .GE. r/2) THEN
!
!        Code for K=0 --
!
    DO l=1,q2
      DO i=0,p-1
        bd(i, l, 0) = ad(i, 0, 0)
        b(i, l, 0) = a(i, 0, 0)
        bd(i, q-l, 0) = 0.D0
        b(i, q-l, 0) = 0.0d0
      END DO
      DO j=1,q2
        indx = MOD(j*l, q)
        DO i=0,p-1
          bd(i, l, 0) = bd(i, l, 0) + cosine(0, indx)*ad(i, 0, j)
          b(i, l, 0) = b(i, l, 0) + a(i, 0, j)*cosine(0, indx)
          bd(i, q-l, 0) = bd(i, q-l, 0) - sine(0, indx)*ad(i, 0, q-j)
          b(i, q-l, 0) = b(i, q-l, 0) - a(i, 0, q-j)*sine(0, indx)
        END DO
      END DO
    END DO
    DO i=0,p-1
      bd(i, 0, 0) = ad(i, 0, 0)
      b(i, 0, 0) = a(i, 0, 0)
    END DO
    DO j=1,q2
      DO i=0,p-1
        bd(i, 0, 0) = bd(i, 0, 0) + ad(i, 0, j)
        b(i, 0, 0) = b(i, 0, 0) + a(i, 0, j)
      END DO
    END DO
    DO j=1,q2
      DO i=0,p-1
        tempd = bd(i, j, 0)
        temp = b(i, j, 0)
        bd(i, j, 0) = bd(i, j, 0) + bd(i, q-j, 0)
        b(i, j, 0) = b(i, j, 0) + b(i, q-j, 0)
        bd(i, q-j, 0) = tempd - bd(i, q-j, 0)
        b(i, q-j, 0) = temp - b(i, q-j, 0)
      END DO
    END DO
!
!        Code for general K --
!
    DO k=1,(r-1)/2
      kp = r - k
      DO j=1,q2
        DO i=0,p-1
          temprd = ad(i, k, j)
          tempr = a(i, k, j)
          tempid = ad(i, kp, q-j-1)
          tempi = a(i, kp, q-j-1)
          ad(i, k, j) = temprd + ad(i, kp, j-1)
          a(i, k, j) = tempr + a(i, kp, j-1)
          ad(i, kp, q-j-1) = tempid - ad(i, k, q-j)
          a(i, kp, q-j-1) = tempi - a(i, k, q-j)
          ad(i, kp, j-1) = temprd - ad(i, kp, j-1)
          a(i, kp, j-1) = tempr - a(i, kp, j-1)
          ad(i, k, q-j) = -tempid - ad(i, k, q-j)
          a(i, k, q-j) = -tempi - a(i, k, q-j)
        END DO
      END DO
      DO l=1,q2
        DO i=0,p-1
          bd(i, l, k) = ad(i, k, 0)
          b(i, l, k) = a(i, k, 0)
          bd(i, l, kp) = ad(i, kp, q-1)
          b(i, l, kp) = a(i, kp, q-1)
          bd(i, q-l, k) = 0.D0
          b(i, q-l, k) = 0.0d0
          bd(i, q-l, kp) = 0.D0
          b(i, q-l, kp) = 0.0d0
        END DO
        DO j=1,q2
          indx = MOD(j*l, q)
          DO i=0,p-1
            bd(i, l, k) = bd(i, l, k) + cosine(0, indx)*ad(i, k, j)
            b(i, l, k) = b(i, l, k) + a(i, k, j)*cosine(0, indx)
            bd(i, l, kp) = bd(i, l, kp) + cosine(0, indx)*ad(i, kp, q-j-&
&             1)
            b(i, l, kp) = b(i, l, kp) + a(i, kp, q-j-1)*cosine(0, indx)
            bd(i, q-l, k) = bd(i, q-l, k) + sine(0, indx)*ad(i, kp, j-1)
            b(i, q-l, k) = b(i, q-l, k) + a(i, kp, j-1)*sine(0, indx)
            bd(i, q-l, kp) = bd(i, q-l, kp) - sine(0, indx)*ad(i, k, q-j&
&             )
            b(i, q-l, kp) = b(i, q-l, kp) - a(i, k, q-j)*sine(0, indx)
          END DO
        END DO
      END DO
      DO i=0,p-1
        bd(i, 0, k) = ad(i, k, 0)
        b(i, 0, k) = a(i, k, 0)
        bd(i, 0, kp) = ad(i, kp, q-1)
        b(i, 0, kp) = a(i, kp, q-1)
      END DO
      DO j=1,q2
        DO i=0,p-1
          bd(i, 0, k) = bd(i, 0, k) + ad(i, k, j)
          b(i, 0, k) = b(i, 0, k) + a(i, k, j)
          bd(i, 0, kp) = bd(i, 0, kp) + ad(i, kp, q-j-1)
          b(i, 0, kp) = b(i, 0, kp) + a(i, kp, q-j-1)
        END DO
      END DO
      DO j=1,q2
        DO i=0,p-1
          temprd = bd(i, j, k)
          tempr = b(i, j, k)
          tempid = bd(i, j, kp)
          tempi = b(i, j, kp)
          bd(i, j, k) = temprd - bd(i, q-j, kp)
          b(i, j, k) = tempr - b(i, q-j, kp)
          bd(i, j, kp) = tempid + bd(i, q-j, k)
          b(i, j, kp) = tempi + b(i, q-j, k)
          temp1d = bd(i, q-j, k)
          temp1 = b(i, q-j, k)
          bd(i, q-j, k) = temprd + bd(i, q-j, kp)
          b(i, q-j, k) = tempr + b(i, q-j, kp)
          bd(i, q-j, kp) = tempid - temp1d
          b(i, q-j, kp) = tempi - temp1
        END DO
      END DO
      DO j=1,q-1
        DO i=0,p-1
          brd = bd(i, j, k)
          br = b(i, j, k)
          bid = bd(i, j, kp)
          bi = b(i, j, kp)
          bd(i, j, k) = cosine(k, j)*brd - sine(k, j)*bid
          b(i, j, k) = cosine(k, j)*br - sine(k, j)*bi
          bd(i, j, kp) = cosine(k, j)*bid + sine(k, j)*brd
          b(i, j, kp) = cosine(k, j)*bi + sine(k, j)*br
        END DO
      END DO
    END DO
!
!        Code for K=R/2 when R is even --
!
    IF (MOD(r, 2) .EQ. 0) THEN
      r2 = r/2
      DO l=1,q2
        DO i=0,p-1
          bd(i, l, r2) = ad(i, r2, q2)
          b(i, l, r2) = a(i, r2, q2)
          bd(i, q-l, r2) = 0.D0
          b(i, q-l, r2) = 0.0d0
        END DO
      END DO
      DO l=1,q2
        DO j=0,q2-1
          indx = MOD(l*(j+q2+1), q)
          DO i=0,p-1
            bd(i, l, r2) = bd(i, l, r2) + cosine(0, indx)*ad(i, r2, j)
            b(i, l, r2) = b(i, l, r2) + a(i, r2, j)*cosine(0, indx)
            bd(i, q-l, r2) = bd(i, q-l, r2) + sine(0, indx)*ad(i, r2, q-&
&             j-1)
            b(i, q-l, r2) = b(i, q-l, r2) + a(i, r2, q-j-1)*sine(0, indx&
&             )
          END DO
        END DO
      END DO
      DO i=0,p-1
        bd(i, 0, r2) = ad(i, r2, q2)
        b(i, 0, r2) = a(i, r2, q2)
      END DO
      DO j=0,q2-1
        DO i=0,p-1
          bd(i, 0, r2) = bd(i, 0, r2) + ad(i, r2, j)
          b(i, 0, r2) = b(i, 0, r2) + a(i, r2, j)
        END DO
      END DO
      DO j=1,q2-1,2
        DO i=0,p-1
          temprd = bd(i, j, r2)
          tempr = b(i, j, r2)
          tempid = bd(i, q-j, r2)
          tempi = b(i, q-j, r2)
          bd(i, j, r2) = tempid - temprd
          b(i, j, r2) = tempi - tempr
          bd(i, q-j, r2) = temprd + tempid
          b(i, q-j, r2) = tempr + tempi
          temprd = bd(i, j+1, r2)
          tempr = b(i, j+1, r2)
          tempid = bd(i, q-j-1, r2)
          tempi = b(i, q-j-1, r2)
          bd(i, j+1, r2) = temprd - tempid
          b(i, j+1, r2) = tempr - tempi
          bd(i, q-j-1, r2) = -temprd - tempid
          b(i, q-j-1, r2) = -tempr - tempi
        END DO
      END DO
      IF (MOD(q2, 2) .EQ. 1) THEN
        DO i=0,p-1
          temprd = bd(i, q2, r2)
          tempr = b(i, q2, r2)
          tempid = bd(i, q2+1, r2)
          tempi = b(i, q2+1, r2)
          bd(i, q2, r2) = tempid - temprd
          b(i, q2, r2) = tempi - tempr
          bd(i, q2+1, r2) = temprd + tempid
          b(i, q2+1, r2) = tempr + tempi
        END DO
      END IF
    END IF
  ELSE
!
!
    DO i=0,p-1
!
!           Code for K=0 --
!
      DO l=1,q2
        bd(i, l, 0) = ad(i, 0, 0)
        b(i, l, 0) = a(i, 0, 0)
        bd(i, q-l, 0) = 0.D0
        b(i, q-l, 0) = 0.0d0
        DO j=1,q2
          indx = MOD(j*l, q)
          bd(i, l, 0) = bd(i, l, 0) + cosine(0, indx)*ad(i, 0, j)
          b(i, l, 0) = b(i, l, 0) + a(i, 0, j)*cosine(0, indx)
          bd(i, q-l, 0) = bd(i, q-l, 0) - sine(0, indx)*ad(i, 0, q-j)
          b(i, q-l, 0) = b(i, q-l, 0) - a(i, 0, q-j)*sine(0, indx)
        END DO
      END DO
      bd(i, 0, 0) = ad(i, 0, 0)
      b(i, 0, 0) = a(i, 0, 0)
      DO j=1,q2
        bd(i, 0, 0) = bd(i, 0, 0) + ad(i, 0, j)
        b(i, 0, 0) = b(i, 0, 0) + a(i, 0, j)
      END DO
      DO j=1,q2
        tempd = bd(i, j, 0)
        temp = b(i, j, 0)
        bd(i, j, 0) = bd(i, j, 0) + bd(i, q-j, 0)
        b(i, j, 0) = b(i, j, 0) + b(i, q-j, 0)
        bd(i, q-j, 0) = tempd - bd(i, q-j, 0)
        b(i, q-j, 0) = temp - b(i, q-j, 0)
      END DO
!
!           Code for general K --
!
      DO j=1,q2
        DO k=1,(r-1)/2
          temprd = ad(i, k, j)
          tempr = a(i, k, j)
          tempid = ad(i, r-k, q-j-1)
          tempi = a(i, r-k, q-j-1)
          ad(i, k, j) = temprd + ad(i, r-k, j-1)
          a(i, k, j) = tempr + a(i, r-k, j-1)
          ad(i, r-k, q-j-1) = tempid - ad(i, k, q-j)
          a(i, r-k, q-j-1) = tempi - a(i, k, q-j)
          ad(i, r-k, j-1) = temprd - ad(i, r-k, j-1)
          a(i, r-k, j-1) = tempr - a(i, r-k, j-1)
          ad(i, k, q-j) = -tempid - ad(i, k, q-j)
          a(i, k, q-j) = -tempi - a(i, k, q-j)
        END DO
      END DO
      DO l=1,q2
        DO k=1,(r-1)/2
          bd(i, l, k) = ad(i, k, 0)
          b(i, l, k) = a(i, k, 0)
          bd(i, l, r-k) = ad(i, r-k, q-1)
          b(i, l, r-k) = a(i, r-k, q-1)
          bd(i, q-l, k) = 0.D0
          b(i, q-l, k) = 0.0d0
          bd(i, q-l, r-k) = 0.D0
          b(i, q-l, r-k) = 0.0d0
        END DO
        DO j=1,q2
          indx = MOD(j*l, q)
          DO k=1,(r-1)/2
            bd(i, l, k) = bd(i, l, k) + cosine(0, indx)*ad(i, k, j)
            b(i, l, k) = b(i, l, k) + a(i, k, j)*cosine(0, indx)
            bd(i, l, r-k) = bd(i, l, r-k) + cosine(0, indx)*ad(i, r-k, q&
&             -j-1)
            b(i, l, r-k) = b(i, l, r-k) + a(i, r-k, q-j-1)*cosine(0, &
&             indx)
            bd(i, q-l, k) = bd(i, q-l, k) + sine(0, indx)*ad(i, r-k, j-1&
&             )
            b(i, q-l, k) = b(i, q-l, k) + a(i, r-k, j-1)*sine(0, indx)
            bd(i, q-l, r-k) = bd(i, q-l, r-k) - sine(0, indx)*ad(i, k, q&
&             -j)
            b(i, q-l, r-k) = b(i, q-l, r-k) - a(i, k, q-j)*sine(0, indx)
          END DO
        END DO
      END DO
      DO k=1,(r-1)/2
        bd(i, 0, k) = ad(i, k, 0)
        b(i, 0, k) = a(i, k, 0)
        bd(i, 0, r-k) = ad(i, r-k, q-1)
        b(i, 0, r-k) = a(i, r-k, q-1)
      END DO
      DO j=1,q2
        DO k=1,(r-1)/2
          bd(i, 0, k) = bd(i, 0, k) + ad(i, k, j)
          b(i, 0, k) = b(i, 0, k) + a(i, k, j)
          bd(i, 0, r-k) = bd(i, 0, r-k) + ad(i, r-k, q-j-1)
          b(i, 0, r-k) = b(i, 0, r-k) + a(i, r-k, q-j-1)
        END DO
      END DO
      DO j=1,q2
        DO k=1,(r-1)/2
          temprd = bd(i, j, k)
          tempr = b(i, j, k)
          tempid = bd(i, j, r-k)
          tempi = b(i, j, r-k)
          bd(i, j, k) = temprd - bd(i, q-j, r-k)
          b(i, j, k) = tempr - b(i, q-j, r-k)
          bd(i, j, r-k) = tempid + bd(i, q-j, k)
          b(i, j, r-k) = tempi + b(i, q-j, k)
          temp1d = bd(i, q-j, k)
          temp1 = b(i, q-j, k)
          bd(i, q-j, k) = temprd + bd(i, q-j, r-k)
          b(i, q-j, k) = tempr + b(i, q-j, r-k)
          bd(i, q-j, r-k) = tempid - temp1d
          b(i, q-j, r-k) = tempi - temp1
        END DO
      END DO
      DO j=1,q-1
        DO k=1,(r-1)/2
          brd = bd(i, j, k)
          br = b(i, j, k)
          bid = bd(i, j, r-k)
          bi = b(i, j, r-k)
          bd(i, j, k) = cosine(k, j)*brd - sine(k, j)*bid
          b(i, j, k) = cosine(k, j)*br - sine(k, j)*bi
          bd(i, j, r-k) = cosine(k, j)*bid + sine(k, j)*brd
          b(i, j, r-k) = cosine(k, j)*bi + sine(k, j)*br
        END DO
      END DO
!
!           Code for K=R/2 when R is even --
!
      IF (MOD(r, 2) .EQ. 0) THEN
        r2 = r/2
        DO l=1,q2
          bd(i, l, r2) = ad(i, r2, q2)
          b(i, l, r2) = a(i, r2, q2)
          bd(i, q-l, r2) = 0.D0
          b(i, q-l, r2) = 0.0d0
        END DO
        DO l=1,q2
          DO j=0,q2-1
            indx = MOD(l*(j+q2+1), q)
            bd(i, l, r2) = bd(i, l, r2) + cosine(0, indx)*ad(i, r2, j)
            b(i, l, r2) = b(i, l, r2) + a(i, r2, j)*cosine(0, indx)
            bd(i, q-l, r2) = bd(i, q-l, r2) + sine(0, indx)*ad(i, r2, q-&
&             j-1)
            b(i, q-l, r2) = b(i, q-l, r2) + a(i, r2, q-j-1)*sine(0, indx&
&             )
          END DO
        END DO
        bd(i, 0, r2) = ad(i, r2, q2)
        b(i, 0, r2) = a(i, r2, q2)
        DO j=0,q2-1
          bd(i, 0, r2) = bd(i, 0, r2) + ad(i, r2, j)
          b(i, 0, r2) = b(i, 0, r2) + a(i, r2, j)
        END DO
        DO j=1,q2-1,2
          temprd = bd(i, j, r2)
          tempr = b(i, j, r2)
          tempid = bd(i, q-j, r2)
          tempi = b(i, q-j, r2)
          bd(i, j, r2) = tempid - temprd
          b(i, j, r2) = tempi - tempr
          bd(i, q-j, r2) = temprd + tempid
          b(i, q-j, r2) = tempr + tempi
          temprd = bd(i, j+1, r2)
          tempr = b(i, j+1, r2)
          tempid = bd(i, q-j-1, r2)
          tempi = b(i, q-j-1, r2)
          bd(i, j+1, r2) = temprd - tempid
          b(i, j+1, r2) = tempr - tempi
          bd(i, q-j-1, r2) = -temprd - tempid
          b(i, q-j-1, r2) = -tempr - tempi
        END DO
        IF (MOD(q2, 2) .EQ. 1) THEN
          temprd = bd(i, q2, r2)
          tempr = b(i, q2, r2)
          tempid = bd(i, q2+1, r2)
          tempi = b(i, q2+1, r2)
          bd(i, q2, r2) = tempid - temprd
          b(i, q2, r2) = tempi - tempr
          bd(i, q2+1, r2) = temprd + tempid
          b(i, q2+1, r2) = tempr + tempi
        END IF
      END IF
    END DO
  END IF
  RETURN
END SUBROUTINE C06FQR_D
