!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fps in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FPS_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-694 (DEC 1989).
!
!     Radix six real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:5, 0:r-1), b(0:p-1, 0:r-1, 0:5), cosine&
& (0:r-1, 5), sine(0:r-1, 5)
  DOUBLE PRECISION :: ad(0:p-1, 0:5, 0:r-1), bd(0:p-1, 0:r-1, 0:5)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, c4k, c5k, ck, s2k, s3k, s4k, s5k, sk, t1&
& , t1i, t1r, t2, t2i, t2r, t3, t3i, t3r, t4, t5, t6, u0, u0i, u0r, u1i&
& , u1r, u2i, u2r, ui, ur, v0, v0i, v0r, v1i, v1r, v2i, v2r, vi, vr, x1p&
& , x2p, x3p, x4p, x5p, y1p, y2p, y3p, y4p, y5p
  DOUBLE PRECISION :: t1d, t1id, t1rd, t2d, t2id, t2rd, t3d, t3id, t3rd&
& , t4d, t5d, t6d, u0d, u0id, u0rd, u1id, u1rd, u2id, u2rd, uid, urd, &
& v0d, v0id, v0rd, v1id, v1rd, v2id, v2rd, vid, vrd, x1pd, x2pd, x3pd, &
& x4pd, x5pd, y1pd, y2pd, y3pd, y4pd, y5pd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    t1d = ad(i, 2, 0) + ad(i, 4, 0)
    t1 = a(i, 2, 0) + a(i, 4, 0)
    urd = ad(i, 0, 0) - 0.5d0*t1d
    ur = a(i, 0, 0) - 0.5d0*t1
    uid = -(sin60*(ad(i, 2, 0)-ad(i, 4, 0)))
    ui = -(sin60*(a(i, 2, 0)-a(i, 4, 0)))
    u0d = ad(i, 0, 0) + t1d
    u0 = a(i, 0, 0) + t1
    t1d = ad(i, 5, 0) + ad(i, 1, 0)
    t1 = a(i, 5, 0) + a(i, 1, 0)
    vrd = ad(i, 3, 0) - 0.5d0*t1d
    vr = a(i, 3, 0) - 0.5d0*t1
    vid = -(sin60*(ad(i, 5, 0)-ad(i, 1, 0)))
    vi = -(sin60*(a(i, 5, 0)-a(i, 1, 0)))
    v0d = ad(i, 3, 0) + t1d
    v0 = a(i, 3, 0) + t1
    bd(i, 0, 0) = u0d + v0d
    b(i, 0, 0) = u0 + v0
    bd(i, 0, 1) = urd - vrd
    b(i, 0, 1) = ur - vr
    bd(i, 0, 2) = urd + vrd
    b(i, 0, 2) = ur + vr
    bd(i, 0, 3) = u0d - v0d
    b(i, 0, 3) = u0 - v0
    bd(i, 0, 4) = -uid - vid
    b(i, 0, 4) = -ui - vi
    bd(i, 0, 5) = uid - vid
    b(i, 0, 5) = ui - vi
  END DO
!
!     Code for general K --
!
  IF (p .LE. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        x1pd = cosine(k, 1)*ad(i, 1, k) - sine(k, 1)*ad(i, 1, r-k)
        x1p = cosine(k, 1)*a(i, 1, k) - sine(k, 1)*a(i, 1, r-k)
        y1pd = cosine(k, 1)*ad(i, 1, r-k) + sine(k, 1)*ad(i, 1, k)
        y1p = cosine(k, 1)*a(i, 1, r-k) + sine(k, 1)*a(i, 1, k)
        x2pd = cosine(k, 2)*ad(i, 2, k) - sine(k, 2)*ad(i, 2, r-k)
        x2p = cosine(k, 2)*a(i, 2, k) - sine(k, 2)*a(i, 2, r-k)
        y2pd = cosine(k, 2)*ad(i, 2, r-k) + sine(k, 2)*ad(i, 2, k)
        y2p = cosine(k, 2)*a(i, 2, r-k) + sine(k, 2)*a(i, 2, k)
        x3pd = cosine(k, 3)*ad(i, 3, k) - sine(k, 3)*ad(i, 3, r-k)
        x3p = cosine(k, 3)*a(i, 3, k) - sine(k, 3)*a(i, 3, r-k)
        y3pd = cosine(k, 3)*ad(i, 3, r-k) + sine(k, 3)*ad(i, 3, k)
        y3p = cosine(k, 3)*a(i, 3, r-k) + sine(k, 3)*a(i, 3, k)
        x4pd = cosine(k, 4)*ad(i, 4, k) - sine(k, 4)*ad(i, 4, r-k)
        x4p = cosine(k, 4)*a(i, 4, k) - sine(k, 4)*a(i, 4, r-k)
        y4pd = cosine(k, 4)*ad(i, 4, r-k) + sine(k, 4)*ad(i, 4, k)
        y4p = cosine(k, 4)*a(i, 4, r-k) + sine(k, 4)*a(i, 4, k)
        x5pd = cosine(k, 5)*ad(i, 5, k) - sine(k, 5)*ad(i, 5, r-k)
        x5p = cosine(k, 5)*a(i, 5, k) - sine(k, 5)*a(i, 5, r-k)
        y5pd = cosine(k, 5)*ad(i, 5, r-k) + sine(k, 5)*ad(i, 5, k)
        y5p = cosine(k, 5)*a(i, 5, r-k) + sine(k, 5)*a(i, 5, k)
        t1rd = x2pd + x4pd
        t1r = x2p + x4p
        t1id = y2pd + y4pd
        t1i = y2p + y4p
        t2rd = ad(i, 0, k) - 0.5d0*t1rd
        t2r = a(i, 0, k) - 0.5d0*t1r
        t2id = ad(i, 0, r-k) - 0.5d0*t1id
        t2i = a(i, 0, r-k) - 0.5d0*t1i
        t3rd = sin60*(x2pd-x4pd)
        t3r = sin60*(x2p-x4p)
        t3id = sin60*(y2pd-y4pd)
        t3i = sin60*(y2p-y4p)
        u0rd = ad(i, 0, k) + t1rd
        u0r = a(i, 0, k) + t1r
        u0id = ad(i, 0, r-k) + t1id
        u0i = a(i, 0, r-k) + t1i
        u1rd = t2rd + t3id
        u1r = t2r + t3i
        u1id = t2id - t3rd
        u1i = t2i - t3r
        u2rd = t2rd - t3id
        u2r = t2r - t3i
        u2id = t2id + t3rd
        u2i = t2i + t3r
        t1rd = x5pd + x1pd
        t1r = x5p + x1p
        t1id = y5pd + y1pd
        t1i = y5p + y1p
        t2rd = x3pd - 0.5d0*t1rd
        t2r = x3p - 0.5d0*t1r
        t2id = y3pd - 0.5d0*t1id
        t2i = y3p - 0.5d0*t1i
        t3rd = sin60*(x5pd-x1pd)
        t3r = sin60*(x5p-x1p)
        t3id = sin60*(y5pd-y1pd)
        t3i = sin60*(y5p-y1p)
        v0rd = x3pd + t1rd
        v0r = x3p + t1r
        v0id = y3pd + t1id
        v0i = y3p + t1i
        v1rd = t2rd + t3id
        v1r = t2r + t3i
        v1id = t2id - t3rd
        v1i = t2i - t3r
        v2rd = t2rd - t3id
        v2r = t2r - t3i
        v2id = t2id + t3rd
        v2i = t2i + t3r
        bd(i, k, 0) = u0rd + v0rd
        b(i, k, 0) = u0r + v0r
        bd(i, r-k, 0) = u2rd - v2rd
        b(i, r-k, 0) = u2r - v2r
        bd(i, k, 1) = u1rd - v1rd
        b(i, k, 1) = u1r - v1r
        bd(i, r-k, 1) = u1rd + v1rd
        b(i, r-k, 1) = u1r + v1r
        bd(i, k, 2) = u2rd + v2rd
        b(i, k, 2) = u2r + v2r
        bd(i, r-k, 2) = u0rd - v0rd
        b(i, r-k, 2) = u0r - v0r
        bd(i, k, 3) = v0id - u0id
        b(i, k, 3) = -u0i + v0i
        bd(i, r-k, 3) = u2id + v2id
        b(i, r-k, 3) = u2i + v2i
        bd(i, k, 4) = -u1id - v1id
        b(i, k, 4) = -u1i - v1i
        bd(i, r-k, 4) = u1id - v1id
        b(i, r-k, 4) = u1i - v1i
        bd(i, k, 5) = v2id - u2id
        b(i, k, 5) = -u2i + v2i
        bd(i, r-k, 5) = u0id + v0id
        b(i, r-k, 5) = u0i + v0i
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k, 1)
      sk = sine(k, 1)
      c2k = cosine(k, 2)
      s2k = sine(k, 2)
      c3k = cosine(k, 3)
      s3k = sine(k, 3)
      c4k = cosine(k, 4)
      s4k = sine(k, 4)
      c5k = cosine(k, 5)
      s5k = sine(k, 5)
      DO i=0,p-1
        x1pd = ck*ad(i, 1, k) - sk*ad(i, 1, kp)
        x1p = ck*a(i, 1, k) - sk*a(i, 1, kp)
        y1pd = ck*ad(i, 1, kp) + sk*ad(i, 1, k)
        y1p = ck*a(i, 1, kp) + sk*a(i, 1, k)
        x2pd = c2k*ad(i, 2, k) - s2k*ad(i, 2, kp)
        x2p = c2k*a(i, 2, k) - s2k*a(i, 2, kp)
        y2pd = c2k*ad(i, 2, kp) + s2k*ad(i, 2, k)
        y2p = c2k*a(i, 2, kp) + s2k*a(i, 2, k)
        x3pd = c3k*ad(i, 3, k) - s3k*ad(i, 3, kp)
        x3p = c3k*a(i, 3, k) - s3k*a(i, 3, kp)
        y3pd = c3k*ad(i, 3, kp) + s3k*ad(i, 3, k)
        y3p = c3k*a(i, 3, kp) + s3k*a(i, 3, k)
        x4pd = c4k*ad(i, 4, k) - s4k*ad(i, 4, kp)
        x4p = c4k*a(i, 4, k) - s4k*a(i, 4, kp)
        y4pd = c4k*ad(i, 4, kp) + s4k*ad(i, 4, k)
        y4p = c4k*a(i, 4, kp) + s4k*a(i, 4, k)
        x5pd = c5k*ad(i, 5, k) - s5k*ad(i, 5, kp)
        x5p = c5k*a(i, 5, k) - s5k*a(i, 5, kp)
        y5pd = c5k*ad(i, 5, kp) + s5k*ad(i, 5, k)
        y5p = c5k*a(i, 5, kp) + s5k*a(i, 5, k)
        t1rd = x2pd + x4pd
        t1r = x2p + x4p
        t1id = y2pd + y4pd
        t1i = y2p + y4p
        t2rd = ad(i, 0, k) - 0.5d0*t1rd
        t2r = a(i, 0, k) - 0.5d0*t1r
        t2id = ad(i, 0, kp) - 0.5d0*t1id
        t2i = a(i, 0, kp) - 0.5d0*t1i
        t3rd = sin60*(x2pd-x4pd)
        t3r = sin60*(x2p-x4p)
        t3id = sin60*(y2pd-y4pd)
        t3i = sin60*(y2p-y4p)
        u0rd = ad(i, 0, k) + t1rd
        u0r = a(i, 0, k) + t1r
        u0id = ad(i, 0, kp) + t1id
        u0i = a(i, 0, kp) + t1i
        u1rd = t2rd + t3id
        u1r = t2r + t3i
        u1id = t2id - t3rd
        u1i = t2i - t3r
        u2rd = t2rd - t3id
        u2r = t2r - t3i
        u2id = t2id + t3rd
        u2i = t2i + t3r
        t1rd = x5pd + x1pd
        t1r = x5p + x1p
        t1id = y5pd + y1pd
        t1i = y5p + y1p
        t2rd = x3pd - 0.5d0*t1rd
        t2r = x3p - 0.5d0*t1r
        t2id = y3pd - 0.5d0*t1id
        t2i = y3p - 0.5d0*t1i
        t3rd = sin60*(x5pd-x1pd)
        t3r = sin60*(x5p-x1p)
        t3id = sin60*(y5pd-y1pd)
        t3i = sin60*(y5p-y1p)
        v0rd = x3pd + t1rd
        v0r = x3p + t1r
        v0id = y3pd + t1id
        v0i = y3p + t1i
        v1rd = t2rd + t3id
        v1r = t2r + t3i
        v1id = t2id - t3rd
        v1i = t2i - t3r
        v2rd = t2rd - t3id
        v2r = t2r - t3i
        v2id = t2id + t3rd
        v2i = t2i + t3r
        bd(i, k, 0) = u0rd + v0rd
        b(i, k, 0) = u0r + v0r
        bd(i, kp, 0) = u2rd - v2rd
        b(i, kp, 0) = u2r - v2r
        bd(i, k, 1) = u1rd - v1rd
        b(i, k, 1) = u1r - v1r
        bd(i, kp, 1) = u1rd + v1rd
        b(i, kp, 1) = u1r + v1r
        bd(i, k, 2) = u2rd + v2rd
        b(i, k, 2) = u2r + v2r
        bd(i, kp, 2) = u0rd - v0rd
        b(i, kp, 2) = u0r - v0r
        bd(i, k, 3) = v0id - u0id
        b(i, k, 3) = -u0i + v0i
        bd(i, kp, 3) = u2id + v2id
        b(i, kp, 3) = u2i + v2i
        bd(i, k, 4) = -u1id - v1id
        b(i, k, 4) = -u1i - v1i
        bd(i, kp, 4) = u1id - v1id
        b(i, kp, 4) = u1i - v1i
        bd(i, k, 5) = v2id - u2id
        b(i, k, 5) = -u2i + v2i
        bd(i, kp, 5) = u0id + v0id
        b(i, kp, 5) = u0i + v0i
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=0,p-1
      t1d = ad(i, 2, r2) - ad(i, 4, r2)
      t1 = a(i, 2, r2) - a(i, 4, r2)
      t2d = ad(i, 0, r2) + 0.5d0*t1d
      t2 = a(i, 0, r2) + 0.5d0*t1
      t3d = sin60*(ad(i, 2, r2)+ad(i, 4, r2))
      t3 = sin60*(a(i, 2, r2)+a(i, 4, r2))
      t4d = ad(i, 1, r2) + ad(i, 5, r2)
      t4 = a(i, 1, r2) + a(i, 5, r2)
      t5d = -ad(i, 3, r2) - 0.5d0*t4d
      t5 = -a(i, 3, r2) - 0.5d0*t4
      t6d = sin60*(ad(i, 1, r2)-ad(i, 5, r2))
      t6 = sin60*(a(i, 1, r2)-a(i, 5, r2))
      bd(i, r2, 0) = t2d + t6d
      b(i, r2, 0) = t2 + t6
      bd(i, r2, 1) = ad(i, 0, r2) - t1d
      b(i, r2, 1) = a(i, 0, r2) - t1
      bd(i, r2, 2) = t2d - t6d
      b(i, r2, 2) = t2 - t6
      bd(i, r2, 3) = t5d + t3d
      b(i, r2, 3) = t5 + t3
      bd(i, r2, 4) = ad(i, 3, r2) - t4d
      b(i, r2, 4) = a(i, 3, r2) - t4
      bd(i, r2, 5) = t5d - t3d
      b(i, r2, 5) = t5 - t3
    END DO
  END IF
!
  RETURN
END SUBROUTINE C06FPS_D
