!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpt in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FPT_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-695 (DEC 1989).
!
!     Radix five real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Parameters ..
  DOUBLE PRECISION :: r54, sin72, s36s72
  PARAMETER (r54=0.559016994374947424102293417182819d0, sin72=&
&   0.951056516295153572116439333379382d0, s36s72=&
&   0.618033988749894848204586834365638d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:4, 0:r-1), b(0:p-1, 0:r-1, 0:4), cosine&
& (0:r-1, 4), sine(0:r-1, 4)
  DOUBLE PRECISION :: ad(0:p-1, 0:4, 0:r-1), bd(0:p-1, 0:r-1, 0:4)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, c4k, ck, s2k, s3k, s4k, sk, t1, t10i, &
& t10r, t11i, t11r, t1i, t1r, t2, t2i, t2r, t3, t3i, t3r, t4, t4i, t4r, &
& t5, t5i, t5r, t6, t6i, t6r, t7, t7i, t7r, t8i, t8r, t9i, t9r, x1p, x2p&
& , x3p, x4p, y1p, y2p, y3p, y4p
  DOUBLE PRECISION :: t1d, t10id, t10rd, t11id, t11rd, t1id, t1rd, t2d, &
& t2id, t2rd, t3d, t3id, t3rd, t4d, t4id, t4rd, t5d, t5id, t5rd, t6d, &
& t6id, t6rd, t7d, t7id, t7rd, t8id, t8rd, t9id, t9rd, x1pd, x2pd, x3pd&
& , x4pd, y1pd, y2pd, y3pd, y4pd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    t1d = ad(i, 1, 0) + ad(i, 4, 0)
    t1 = a(i, 1, 0) + a(i, 4, 0)
    t2d = ad(i, 2, 0) + ad(i, 3, 0)
    t2 = a(i, 2, 0) + a(i, 3, 0)
    t3d = sin72*(ad(i, 1, 0)-ad(i, 4, 0))
    t3 = sin72*(a(i, 1, 0)-a(i, 4, 0))
    t4d = sin72*(ad(i, 2, 0)-ad(i, 3, 0))
    t4 = sin72*(a(i, 2, 0)-a(i, 3, 0))
    t5d = t1d + t2d
    t5 = t1 + t2
    t6d = r54*(t1d-t2d)
    t6 = r54*(t1-t2)
    t7d = ad(i, 0, 0) - 0.25d0*t5d
    t7 = a(i, 0, 0) - 0.25d0*t5
    bd(i, 0, 0) = ad(i, 0, 0) + t5d
    b(i, 0, 0) = a(i, 0, 0) + t5
    bd(i, 0, 1) = t7d + t6d
    b(i, 0, 1) = t7 + t6
    bd(i, 0, 2) = t7d - t6d
    b(i, 0, 2) = t7 - t6
    bd(i, 0, 3) = t4d - s36s72*t3d
    b(i, 0, 3) = -(s36s72*t3) + t4
    bd(i, 0, 4) = -t3d - s36s72*t4d
    b(i, 0, 4) = -t3 - s36s72*t4
  END DO
!
!     Code for general K --
!
  IF (p .LE. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        x1pd = cosine(k, 1)*ad(i, 1, k) - sine(k, 1)*ad(i, 1, r-k)
        x1p = cosine(k, 1)*a(i, 1, k) - sine(k, 1)*a(i, 1, r-k)
        y1pd = cosine(k, 1)*ad(i, 1, r-k) + sine(k, 1)*ad(i, 1, k)
        y1p = cosine(k, 1)*a(i, 1, r-k) + sine(k, 1)*a(i, 1, k)
        x2pd = cosine(k, 2)*ad(i, 2, k) - sine(k, 2)*ad(i, 2, r-k)
        x2p = cosine(k, 2)*a(i, 2, k) - sine(k, 2)*a(i, 2, r-k)
        y2pd = cosine(k, 2)*ad(i, 2, r-k) + sine(k, 2)*ad(i, 2, k)
        y2p = cosine(k, 2)*a(i, 2, r-k) + sine(k, 2)*a(i, 2, k)
        x3pd = cosine(k, 3)*ad(i, 3, k) - sine(k, 3)*ad(i, 3, r-k)
        x3p = cosine(k, 3)*a(i, 3, k) - sine(k, 3)*a(i, 3, r-k)
        y3pd = cosine(k, 3)*ad(i, 3, r-k) + sine(k, 3)*ad(i, 3, k)
        y3p = cosine(k, 3)*a(i, 3, r-k) + sine(k, 3)*a(i, 3, k)
        x4pd = cosine(k, 4)*ad(i, 4, k) - sine(k, 4)*ad(i, 4, r-k)
        x4p = cosine(k, 4)*a(i, 4, k) - sine(k, 4)*a(i, 4, r-k)
        y4pd = cosine(k, 4)*ad(i, 4, r-k) + sine(k, 4)*ad(i, 4, k)
        y4p = cosine(k, 4)*a(i, 4, r-k) + sine(k, 4)*a(i, 4, k)
        t1rd = x1pd + x4pd
        t1r = x1p + x4p
        t1id = y1pd + y4pd
        t1i = y1p + y4p
        t2rd = x2pd + x3pd
        t2r = x2p + x3p
        t2id = y2pd + y3pd
        t2i = y2p + y3p
        t3rd = sin72*(x1pd-x4pd)
        t3r = sin72*(x1p-x4p)
        t3id = sin72*(y1pd-y4pd)
        t3i = sin72*(y1p-y4p)
        t4rd = sin72*(x2pd-x3pd)
        t4r = sin72*(x2p-x3p)
        t4id = sin72*(y2pd-y3pd)
        t4i = sin72*(y2p-y3p)
        t5rd = t1rd + t2rd
        t5r = t1r + t2r
        t5id = t1id + t2id
        t5i = t1i + t2i
        t6rd = r54*(t1rd-t2rd)
        t6r = r54*(t1r-t2r)
        t6id = r54*(t1id-t2id)
        t6i = r54*(t1i-t2i)
        t7rd = ad(i, 0, k) - 0.25d0*t5rd
        t7r = a(i, 0, k) - 0.25d0*t5r
        t7id = ad(i, 0, r-k) - 0.25d0*t5id
        t7i = a(i, 0, r-k) - 0.25d0*t5i
        t8rd = t7rd + t6rd
        t8r = t7r + t6r
        t8id = t7id + t6id
        t8i = t7i + t6i
        t9rd = t7rd - t6rd
        t9r = t7r - t6r
        t9id = t7id - t6id
        t9i = t7i - t6i
        t10rd = t3rd + s36s72*t4rd
        t10r = t3r + s36s72*t4r
        t10id = t3id + s36s72*t4id
        t10i = t3i + s36s72*t4i
        t11rd = s36s72*t3rd - t4rd
        t11r = s36s72*t3r - t4r
        t11id = s36s72*t3id - t4id
        t11i = s36s72*t3i - t4i
        bd(i, k, 0) = ad(i, 0, k) + t5rd
        b(i, k, 0) = a(i, 0, k) + t5r
        bd(i, r-k, 0) = t8rd - t10id
        b(i, r-k, 0) = t8r - t10i
        bd(i, k, 1) = t8rd + t10id
        b(i, k, 1) = t8r + t10i
        bd(i, r-k, 1) = t9rd - t11id
        b(i, r-k, 1) = t9r - t11i
        bd(i, k, 2) = t9rd + t11id
        b(i, k, 2) = t9r + t11i
        bd(i, r-k, 2) = t9id - t11rd
        b(i, r-k, 2) = t9i - t11r
        bd(i, k, 3) = -t9id - t11rd
        b(i, k, 3) = -t9i - t11r
        bd(i, r-k, 3) = t8id - t10rd
        b(i, r-k, 3) = t8i - t10r
        bd(i, k, 4) = -t8id - t10rd
        b(i, k, 4) = -t8i - t10r
        bd(i, r-k, 4) = ad(i, 0, r-k) + t5id
        b(i, r-k, 4) = a(i, 0, r-k) + t5i
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k, 1)
      sk = sine(k, 1)
      c2k = cosine(k, 2)
      s2k = sine(k, 2)
      c3k = cosine(k, 3)
      s3k = sine(k, 3)
      c4k = cosine(k, 4)
      s4k = sine(k, 4)
      DO i=0,p-1
        x1pd = ck*ad(i, 1, k) - sk*ad(i, 1, kp)
        x1p = ck*a(i, 1, k) - sk*a(i, 1, kp)
        y1pd = ck*ad(i, 1, kp) + sk*ad(i, 1, k)
        y1p = ck*a(i, 1, kp) + sk*a(i, 1, k)
        x2pd = c2k*ad(i, 2, k) - s2k*ad(i, 2, kp)
        x2p = c2k*a(i, 2, k) - s2k*a(i, 2, kp)
        y2pd = c2k*ad(i, 2, kp) + s2k*ad(i, 2, k)
        y2p = c2k*a(i, 2, kp) + s2k*a(i, 2, k)
        x3pd = c3k*ad(i, 3, k) - s3k*ad(i, 3, kp)
        x3p = c3k*a(i, 3, k) - s3k*a(i, 3, kp)
        y3pd = c3k*ad(i, 3, kp) + s3k*ad(i, 3, k)
        y3p = c3k*a(i, 3, kp) + s3k*a(i, 3, k)
        x4pd = c4k*ad(i, 4, k) - s4k*ad(i, 4, kp)
        x4p = c4k*a(i, 4, k) - s4k*a(i, 4, kp)
        y4pd = c4k*ad(i, 4, kp) + s4k*ad(i, 4, k)
        y4p = c4k*a(i, 4, kp) + s4k*a(i, 4, k)
        t1rd = x1pd + x4pd
        t1r = x1p + x4p
        t1id = y1pd + y4pd
        t1i = y1p + y4p
        t2rd = x2pd + x3pd
        t2r = x2p + x3p
        t2id = y2pd + y3pd
        t2i = y2p + y3p
        t3rd = sin72*(x1pd-x4pd)
        t3r = sin72*(x1p-x4p)
        t3id = sin72*(y1pd-y4pd)
        t3i = sin72*(y1p-y4p)
        t4rd = sin72*(x2pd-x3pd)
        t4r = sin72*(x2p-x3p)
        t4id = sin72*(y2pd-y3pd)
        t4i = sin72*(y2p-y3p)
        t5rd = t1rd + t2rd
        t5r = t1r + t2r
        t5id = t1id + t2id
        t5i = t1i + t2i
        t6rd = r54*(t1rd-t2rd)
        t6r = r54*(t1r-t2r)
        t6id = r54*(t1id-t2id)
        t6i = r54*(t1i-t2i)
        t7rd = ad(i, 0, k) - 0.25d0*t5rd
        t7r = a(i, 0, k) - 0.25d0*t5r
        t7id = ad(i, 0, kp) - 0.25d0*t5id
        t7i = a(i, 0, kp) - 0.25d0*t5i
        t8rd = t7rd + t6rd
        t8r = t7r + t6r
        t8id = t7id + t6id
        t8i = t7i + t6i
        t9rd = t7rd - t6rd
        t9r = t7r - t6r
        t9id = t7id - t6id
        t9i = t7i - t6i
        t10rd = t3rd + s36s72*t4rd
        t10r = t3r + s36s72*t4r
        t10id = t3id + s36s72*t4id
        t10i = t3i + s36s72*t4i
        t11rd = s36s72*t3rd - t4rd
        t11r = s36s72*t3r - t4r
        t11id = s36s72*t3id - t4id
        t11i = s36s72*t3i - t4i
        bd(i, k, 0) = ad(i, 0, k) + t5rd
        b(i, k, 0) = a(i, 0, k) + t5r
        bd(i, kp, 0) = t8rd - t10id
        b(i, kp, 0) = t8r - t10i
        bd(i, k, 1) = t8rd + t10id
        b(i, k, 1) = t8r + t10i
        bd(i, kp, 1) = t9rd - t11id
        b(i, kp, 1) = t9r - t11i
        bd(i, k, 2) = t9rd + t11id
        b(i, k, 2) = t9r + t11i
        bd(i, kp, 2) = t9id - t11rd
        b(i, kp, 2) = t9i - t11r
        bd(i, k, 3) = -t9id - t11rd
        b(i, k, 3) = -t9i - t11r
        bd(i, kp, 3) = t8id - t10rd
        b(i, kp, 3) = t8i - t10r
        bd(i, k, 4) = -t8id - t10rd
        b(i, k, 4) = -t8i - t10r
        bd(i, kp, 4) = ad(i, 0, kp) + t5id
        b(i, kp, 4) = a(i, 0, kp) + t5i
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even not needed
!
!     IF (MOD(R,2).EQ.0) THEN
!        R2 = R/2
!        DO 120 I = 0, P - 1
!           T1 = SIN72*(A(I,1,R2)+A(I,4,R2))
!           T2 = SIN72*(A(I,2,R2)+A(I,3,R2))
!           T3 = A(I,1,R2) - A(I,4,R2)
!           T4 = A(I,2,R2) - A(I,3,R2)
!           T5 = T4 - T3
!           T6 = R54*(T4+T3)
!           T7 = A(I,0,R2) - 0.25D0*T5
!           B(I,R2,0) = T7 + T6
!           B(I,R2,1) = T7 - T6
!           B(I,R2,2) = A(I,0,R2) + T5
!           B(I,R2,3) = -T1 + S36S72*T2
!           B(I,R2,4) = -S36S72*T1 - T2
! 120    CONTINUE
!     END IF
!
  RETURN
END SUBROUTINE C06FPT_D
