!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqw in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FQW_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-703 (DEC 1989).
!
!     Radix two Hermitian to real Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:1), b(0:p-1, 0:1, 0:r-1), cosine&
& (0:r-1), sine(0:r-1)
  DOUBLE PRECISION :: ad(0:p-1, 0:r-1, 0:1), bd(0:p-1, 0:1, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: ck, sk, x1hat, y1hat
  DOUBLE PRECISION :: x1hatd, y1hatd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    bd(i, 0, 0) = ad(i, 0, 0) + ad(i, 0, 1)
    b(i, 0, 0) = a(i, 0, 0) + a(i, 0, 1)
    bd(i, 1, 0) = ad(i, 0, 0) - ad(i, 0, 1)
    b(i, 1, 0) = a(i, 0, 0) - a(i, 0, 1)
  END DO
!
!     Code for general K --
!
  IF (p .LT. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        x1hatd = ad(i, k, 0) - ad(i, r-k, 0)
        x1hat = a(i, k, 0) - a(i, r-k, 0)
        y1hatd = ad(i, r-k, 1) + ad(i, k, 1)
        y1hat = a(i, r-k, 1) + a(i, k, 1)
        bd(i, 0, k) = ad(i, k, 0) + ad(i, r-k, 0)
        b(i, 0, k) = a(i, k, 0) + a(i, r-k, 0)
        bd(i, 0, r-k) = ad(i, r-k, 1) - ad(i, k, 1)
        b(i, 0, r-k) = a(i, r-k, 1) - a(i, k, 1)
        bd(i, 1, k) = cosine(k)*x1hatd - sine(k)*y1hatd
        b(i, 1, k) = cosine(k)*x1hat - sine(k)*y1hat
        bd(i, 1, r-k) = cosine(k)*y1hatd + sine(k)*x1hatd
        b(i, 1, r-k) = cosine(k)*y1hat + sine(k)*x1hat
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k)
      sk = sine(k)
      DO i=0,p-1
        x1hatd = ad(i, k, 0) - ad(i, kp, 0)
        x1hat = a(i, k, 0) - a(i, kp, 0)
        y1hatd = ad(i, kp, 1) + ad(i, k, 1)
        y1hat = a(i, kp, 1) + a(i, k, 1)
        bd(i, 0, k) = ad(i, k, 0) + ad(i, kp, 0)
        b(i, 0, k) = a(i, k, 0) + a(i, kp, 0)
        bd(i, 0, kp) = ad(i, kp, 1) - ad(i, k, 1)
        b(i, 0, kp) = a(i, kp, 1) - a(i, k, 1)
        bd(i, 1, k) = ck*x1hatd - sk*y1hatd
        b(i, 1, k) = ck*x1hat - sk*y1hat
        bd(i, 1, kp) = ck*y1hatd + sk*x1hatd
        b(i, 1, kp) = ck*y1hat + sk*x1hat
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even not needed
!
!     IF (MOD(R,2).EQ.0) THEN
!        R2 = R/2
!        DO 120 I = 0, P - 1
!           B(I,0,R2) = A(I,R2,0)
!           B(I,1,R2) = A(I,R2,1)
! 120    CONTINUE
!     END IF
!
  RETURN
END SUBROUTINE C06FQW_D
