!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fqs in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FQS_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-699 (DEC 1989).
!
!     Radix six Hermitian to real fast Fourier transform kernel
!
!     Self-sorting, decimation in frequency
!
!     .. Parameters ..
  DOUBLE PRECISION :: sin60
  PARAMETER (sin60=0.866025403784438646763723170752936d0)
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:r-1, 0:5), b(0:p-1, 0:5, 0:r-1), cosine&
& (0:r-1, 5), sine(0:r-1, 5)
  DOUBLE PRECISION :: ad(0:p-1, 0:r-1, 0:5), bd(0:p-1, 0:5, 0:r-1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: c2k, c3k, c4k, c5k, ck, s2k, s3k, s4k, s5k, sk, t1&
& , t1i, t1r, t2, t2i, t2r, t3, t3i, t3r, t4, t5, t6, u0, u0i, u0r, u1, &
& u1i, u1r, u2, u2i, u2r, v0, v0i, v0r, v1, v1i, v1r, v2, v2i, v2r, x0p&
& , x1p, x2p, x3p, x4p, x5p, y0p, y1p, y2p, y3p, y4p, y5p
  DOUBLE PRECISION :: t1d, t1id, t1rd, t2d, t2id, t2rd, t3d, t3id, t3rd&
& , t4d, t5d, t6d, u0d, u0id, u0rd, u1d, u1id, u1rd, u2d, u2id, u2rd, &
& v0d, v0id, v0rd, v1d, v1id, v1rd, v2d, v2id, v2rd, x0pd, x1pd, x2pd, &
& x3pd, x4pd, x5pd, y0pd, y1pd, y2pd, y3pd, y4pd, y5pd
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    t1d = ad(i, 0, 2)
    t1 = a(i, 0, 2)
    t2d = ad(i, 0, 0) - 0.5d0*t1d
    t2 = a(i, 0, 0) - 0.5d0*t1
    t3d = sin60*ad(i, 0, 4)
    t3 = sin60*a(i, 0, 4)
    u0d = ad(i, 0, 0) + t1d
    u0 = a(i, 0, 0) + t1
    u1d = t2d + t3d
    u1 = t2 + t3
    u2d = t2d - t3d
    u2 = t2 - t3
    t1d = ad(i, 0, 1)
    t1 = a(i, 0, 1)
    t2d = ad(i, 0, 3) - 0.5d0*t1d
    t2 = a(i, 0, 3) - 0.5d0*t1
    t3d = -(sin60*ad(i, 0, 5))
    t3 = -(sin60*a(i, 0, 5))
    v0d = ad(i, 0, 3) + t1d
    v0 = a(i, 0, 3) + t1
    v1d = t2d + t3d
    v1 = t2 + t3
    v2d = t2d - t3d
    v2 = t2 - t3
    bd(i, 0, 0) = u0d + v0d
    b(i, 0, 0) = u0 + v0
    bd(i, 1, 0) = u1d - v1d
    b(i, 1, 0) = u1 - v1
    bd(i, 2, 0) = u2d + v2d
    b(i, 2, 0) = u2 + v2
    bd(i, 3, 0) = u0d - v0d
    b(i, 3, 0) = u0 - v0
    bd(i, 4, 0) = u1d + v1d
    b(i, 4, 0) = u1 + v1
    bd(i, 5, 0) = u2d - v2d
    b(i, 5, 0) = u2 - v2
  END DO
!
!     Code for general K --
!
  IF (p .LE. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        t1rd = ad(i, k, 2) + ad(i, r-k, 1)
        t1r = a(i, k, 2) + a(i, r-k, 1)
        t1id = ad(i, r-k, 3) - ad(i, k, 4)
        t1i = a(i, r-k, 3) - a(i, k, 4)
        t2rd = ad(i, k, 0) - 0.5d0*t1rd
        t2r = a(i, k, 0) - 0.5d0*t1r
        t2id = ad(i, r-k, 5) - 0.5d0*t1id
        t2i = a(i, r-k, 5) - 0.5d0*t1i
        t3rd = sin60*(ad(i, k, 2)-ad(i, r-k, 1))
        t3r = sin60*(a(i, k, 2)-a(i, r-k, 1))
        t3id = sin60*(ad(i, r-k, 3)+ad(i, k, 4))
        t3i = sin60*(a(i, r-k, 3)+a(i, k, 4))
        u0rd = ad(i, k, 0) + t1rd
        u0r = a(i, k, 0) + t1r
        u0id = ad(i, r-k, 5) + t1id
        u0i = a(i, r-k, 5) + t1i
        u1rd = t2rd + t3id
        u1r = t2r + t3i
        u1id = t2id - t3rd
        u1i = t2i - t3r
        u2rd = t2rd - t3id
        u2r = t2r - t3i
        u2id = t2id + t3rd
        u2i = t2i + t3r
        t1rd = ad(i, r-k, 0) + ad(i, k, 1)
        t1r = a(i, r-k, 0) + a(i, k, 1)
        t1id = ad(i, r-k, 4) - ad(i, k, 5)
        t1i = -a(i, k, 5) + a(i, r-k, 4)
        t2rd = ad(i, r-k, 2) - 0.5d0*t1rd
        t2r = a(i, r-k, 2) - 0.5d0*t1r
        t2id = -ad(i, k, 3) - 0.5d0*t1id
        t2i = -a(i, k, 3) - 0.5d0*t1i
        t3rd = sin60*(ad(i, r-k, 0)-ad(i, k, 1))
        t3r = sin60*(a(i, r-k, 0)-a(i, k, 1))
        t3id = sin60*(-ad(i, k, 5)-ad(i, r-k, 4))
        t3i = sin60*(-a(i, k, 5)-a(i, r-k, 4))
        v0rd = ad(i, r-k, 2) + t1rd
        v0r = a(i, r-k, 2) + t1r
        v0id = t1id - ad(i, k, 3)
        v0i = -a(i, k, 3) + t1i
        v1rd = t2rd + t3id
        v1r = t2r + t3i
        v1id = t2id - t3rd
        v1i = t2i - t3r
        v2rd = t2rd - t3id
        v2r = t2r - t3i
        v2id = t2id + t3rd
        v2i = t2i + t3r
        x0pd = u0rd + v0rd
        x0p = u0r + v0r
        y0pd = u0id + v0id
        y0p = u0i + v0i
        x1pd = u1rd - v1rd
        x1p = u1r - v1r
        y1pd = u1id - v1id
        y1p = u1i - v1i
        x2pd = u2rd + v2rd
        x2p = u2r + v2r
        y2pd = u2id + v2id
        y2p = u2i + v2i
        x3pd = u0rd - v0rd
        x3p = u0r - v0r
        y3pd = u0id - v0id
        y3p = u0i - v0i
        x4pd = u1rd + v1rd
        x4p = u1r + v1r
        y4pd = u1id + v1id
        y4p = u1i + v1i
        x5pd = u2rd - v2rd
        x5p = u2r - v2r
        y5pd = u2id - v2id
        y5p = u2i - v2i
        bd(i, 0, k) = x0pd
        b(i, 0, k) = x0p
        bd(i, 0, r-k) = y0pd
        b(i, 0, r-k) = y0p
        bd(i, 1, k) = cosine(k, 1)*x1pd - sine(k, 1)*y1pd
        b(i, 1, k) = cosine(k, 1)*x1p - sine(k, 1)*y1p
        bd(i, 1, r-k) = cosine(k, 1)*y1pd + sine(k, 1)*x1pd
        b(i, 1, r-k) = cosine(k, 1)*y1p + sine(k, 1)*x1p
        bd(i, 2, k) = cosine(k, 2)*x2pd - sine(k, 2)*y2pd
        b(i, 2, k) = cosine(k, 2)*x2p - sine(k, 2)*y2p
        bd(i, 2, r-k) = cosine(k, 2)*y2pd + sine(k, 2)*x2pd
        b(i, 2, r-k) = cosine(k, 2)*y2p + sine(k, 2)*x2p
        bd(i, 3, k) = cosine(k, 3)*x3pd - sine(k, 3)*y3pd
        b(i, 3, k) = cosine(k, 3)*x3p - sine(k, 3)*y3p
        bd(i, 3, r-k) = cosine(k, 3)*y3pd + sine(k, 3)*x3pd
        b(i, 3, r-k) = cosine(k, 3)*y3p + sine(k, 3)*x3p
        bd(i, 4, k) = cosine(k, 4)*x4pd - sine(k, 4)*y4pd
        b(i, 4, k) = cosine(k, 4)*x4p - sine(k, 4)*y4p
        bd(i, 4, r-k) = cosine(k, 4)*y4pd + sine(k, 4)*x4pd
        b(i, 4, r-k) = cosine(k, 4)*y4p + sine(k, 4)*x4p
        bd(i, 5, k) = cosine(k, 5)*x5pd - sine(k, 5)*y5pd
        b(i, 5, k) = cosine(k, 5)*x5p - sine(k, 5)*y5p
        bd(i, 5, r-k) = cosine(k, 5)*y5pd + sine(k, 5)*x5pd
        b(i, 5, r-k) = cosine(k, 5)*y5p + sine(k, 5)*x5p
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k, 1)
      sk = sine(k, 1)
      c2k = cosine(k, 2)
      s2k = sine(k, 2)
      c3k = cosine(k, 3)
      s3k = sine(k, 3)
      c4k = cosine(k, 4)
      s4k = sine(k, 4)
      c5k = cosine(k, 5)
      s5k = sine(k, 5)
      DO i=0,p-1
        t1rd = ad(i, k, 2) + ad(i, kp, 1)
        t1r = a(i, k, 2) + a(i, kp, 1)
        t1id = ad(i, kp, 3) - ad(i, k, 4)
        t1i = a(i, kp, 3) - a(i, k, 4)
        t2rd = ad(i, k, 0) - 0.5d0*t1rd
        t2r = a(i, k, 0) - 0.5d0*t1r
        t2id = ad(i, kp, 5) - 0.5d0*t1id
        t2i = a(i, kp, 5) - 0.5d0*t1i
        t3rd = sin60*(ad(i, k, 2)-ad(i, kp, 1))
        t3r = sin60*(a(i, k, 2)-a(i, kp, 1))
        t3id = sin60*(ad(i, kp, 3)+ad(i, k, 4))
        t3i = sin60*(a(i, kp, 3)+a(i, k, 4))
        u0rd = ad(i, k, 0) + t1rd
        u0r = a(i, k, 0) + t1r
        u0id = ad(i, kp, 5) + t1id
        u0i = a(i, kp, 5) + t1i
        u1rd = t2rd + t3id
        u1r = t2r + t3i
        u1id = t2id - t3rd
        u1i = t2i - t3r
        u2rd = t2rd - t3id
        u2r = t2r - t3i
        u2id = t2id + t3rd
        u2i = t2i + t3r
        t1rd = ad(i, kp, 0) + ad(i, k, 1)
        t1r = a(i, kp, 0) + a(i, k, 1)
        t1id = ad(i, kp, 4) - ad(i, k, 5)
        t1i = -a(i, k, 5) + a(i, kp, 4)
        t2rd = ad(i, kp, 2) - 0.5d0*t1rd
        t2r = a(i, kp, 2) - 0.5d0*t1r
        t2id = -ad(i, k, 3) - 0.5d0*t1id
        t2i = -a(i, k, 3) - 0.5d0*t1i
        t3rd = sin60*(ad(i, kp, 0)-ad(i, k, 1))
        t3r = sin60*(a(i, kp, 0)-a(i, k, 1))
        t3id = sin60*(-ad(i, k, 5)-ad(i, kp, 4))
        t3i = sin60*(-a(i, k, 5)-a(i, kp, 4))
        v0rd = ad(i, kp, 2) + t1rd
        v0r = a(i, kp, 2) + t1r
        v0id = t1id - ad(i, k, 3)
        v0i = -a(i, k, 3) + t1i
        v1rd = t2rd + t3id
        v1r = t2r + t3i
        v1id = t2id - t3rd
        v1i = t2i - t3r
        v2rd = t2rd - t3id
        v2r = t2r - t3i
        v2id = t2id + t3rd
        v2i = t2i + t3r
        x0pd = u0rd + v0rd
        x0p = u0r + v0r
        y0pd = u0id + v0id
        y0p = u0i + v0i
        x1pd = u1rd - v1rd
        x1p = u1r - v1r
        y1pd = u1id - v1id
        y1p = u1i - v1i
        x2pd = u2rd + v2rd
        x2p = u2r + v2r
        y2pd = u2id + v2id
        y2p = u2i + v2i
        x3pd = u0rd - v0rd
        x3p = u0r - v0r
        y3pd = u0id - v0id
        y3p = u0i - v0i
        x4pd = u1rd + v1rd
        x4p = u1r + v1r
        y4pd = u1id + v1id
        y4p = u1i + v1i
        x5pd = u2rd - v2rd
        x5p = u2r - v2r
        y5pd = u2id - v2id
        y5p = u2i - v2i
        bd(i, 0, k) = x0pd
        b(i, 0, k) = x0p
        bd(i, 0, kp) = y0pd
        b(i, 0, kp) = y0p
        bd(i, 1, k) = ck*x1pd - sk*y1pd
        b(i, 1, k) = ck*x1p - sk*y1p
        bd(i, 1, kp) = ck*y1pd + sk*x1pd
        b(i, 1, kp) = ck*y1p + sk*x1p
        bd(i, 2, k) = c2k*x2pd - s2k*y2pd
        b(i, 2, k) = c2k*x2p - s2k*y2p
        bd(i, 2, kp) = c2k*y2pd + s2k*x2pd
        b(i, 2, kp) = c2k*y2p + s2k*x2p
        bd(i, 3, k) = c3k*x3pd - s3k*y3pd
        b(i, 3, k) = c3k*x3p - s3k*y3p
        bd(i, 3, kp) = c3k*y3pd + s3k*x3pd
        b(i, 3, kp) = c3k*y3p + s3k*x3p
        bd(i, 4, k) = c4k*x4pd - s4k*y4pd
        b(i, 4, k) = c4k*x4p - s4k*y4p
        bd(i, 4, kp) = c4k*y4pd + s4k*x4pd
        b(i, 4, kp) = c4k*y4p + s4k*x4p
        bd(i, 5, k) = c5k*x5pd - s5k*y5pd
        b(i, 5, k) = c5k*x5p - s5k*y5p
        bd(i, 5, kp) = c5k*y5pd + s5k*x5pd
        b(i, 5, kp) = c5k*y5p + s5k*x5p
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even --
!
  IF (MOD(r, 2) .EQ. 0) THEN
    r2 = r/2
    DO i=0,p-1
      t1d = ad(i, r2, 0) + ad(i, r2, 2)
      t1 = a(i, r2, 0) + a(i, r2, 2)
      t2d = ad(i, r2, 5) + ad(i, r2, 3)
      t2 = a(i, r2, 5) + a(i, r2, 3)
      t3d = ad(i, r2, 1) - 0.5d0*t1d
      t3 = a(i, r2, 1) - 0.5d0*t1
      t4d = ad(i, r2, 4) + 0.5d0*t2d
      t4 = a(i, r2, 4) + 0.5d0*t2
      t5d = sin60*(ad(i, r2, 0)-ad(i, r2, 2))
      t5 = sin60*(a(i, r2, 0)-a(i, r2, 2))
      t6d = sin60*(ad(i, r2, 5)-ad(i, r2, 3))
      t6 = sin60*(a(i, r2, 5)-a(i, r2, 3))
      bd(i, 0, r2) = ad(i, r2, 1) + t1d
      b(i, 0, r2) = a(i, r2, 1) + t1
      bd(i, 1, r2) = t4d + t5d
      b(i, 1, r2) = t4 + t5
      bd(i, 2, r2) = t6d - t3d
      b(i, 2, r2) = t6 - t3
      bd(i, 3, r2) = t2d - ad(i, r2, 4)
      b(i, 3, r2) = t2 - a(i, r2, 4)
      bd(i, 4, r2) = t3d + t6d
      b(i, 4, r2) = t3 + t6
      bd(i, 5, r2) = t4d - t5d
      b(i, 5, r2) = t4 - t5
    END DO
  END IF
!
  RETURN
END SUBROUTINE C06FQS_D
