!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of c06fpw in forward (tangent) mode:
!   variations   of useful results: b
!   with respect to varying inputs: a b
SUBROUTINE C06FPW_D(a, ad, b, bd, p, r, cosine, sine)
  IMPLICIT NONE
!VD$R VECTOR
! CVD$R NOLSTVAL
! c CVD$R STRIP
!     MARK 12 RELEASE. NAG COPYRIGHT 1986.
!     MARK 14 REVISED. IER-698 (DEC 1989).
!
!     Radix two Real to Hermitian fast Fourier transform kernel
!
!     Self-sorting, decimation in time
!
!     .. Scalar Arguments ..
  INTEGER :: p, r
!     .. Array Arguments ..
  DOUBLE PRECISION :: a(0:p-1, 0:1, 0:r-1), b(0:p-1, 0:r-1, 0:1), cosine&
& (0:r-1), sine(0:r-1)
  DOUBLE PRECISION :: ad(0:p-1, 0:1, 0:r-1), bd(0:p-1, 0:r-1, 0:1)
!     .. Local Scalars ..
  DOUBLE PRECISION :: ck, sk, x1, y1
  DOUBLE PRECISION :: x1d, y1d
  INTEGER :: i, k, kp, r2
!     .. Intrinsic Functions ..
  INTRINSIC MOD
!     .. Executable Statements ..
  DO i=0,p-1
!
!        Code for K=0 --
!
    bd(i, 0, 0) = ad(i, 0, 0) + ad(i, 1, 0)
    b(i, 0, 0) = a(i, 0, 0) + a(i, 1, 0)
    bd(i, 0, 1) = ad(i, 0, 0) - ad(i, 1, 0)
    b(i, 0, 1) = a(i, 0, 0) - a(i, 1, 0)
  END DO
!
!     Code for general K
!
  IF (p .LT. (r-1)/2) THEN
    DO i=0,p-1
!DIR$ IVDEP
      DO k=1,(r-1)/2
        x1d = cosine(k)*ad(i, 1, k) - sine(k)*ad(i, 1, r-k)
        x1 = cosine(k)*a(i, 1, k) - sine(k)*a(i, 1, r-k)
        y1d = cosine(k)*ad(i, 1, r-k) + sine(k)*ad(i, 1, k)
        y1 = cosine(k)*a(i, 1, r-k) + sine(k)*a(i, 1, k)
        bd(i, k, 0) = ad(i, 0, k) + x1d
        b(i, k, 0) = a(i, 0, k) + x1
        bd(i, r-k, 0) = ad(i, 0, k) - x1d
        b(i, r-k, 0) = a(i, 0, k) - x1
        bd(i, k, 1) = y1d - ad(i, 0, r-k)
        b(i, k, 1) = -a(i, 0, r-k) + y1
        bd(i, r-k, 1) = ad(i, 0, r-k) + y1d
        b(i, r-k, 1) = a(i, 0, r-k) + y1
      END DO
    END DO
  ELSE
    DO k=1,(r-1)/2
      kp = r - k
      ck = cosine(k)
      sk = sine(k)
      DO i=0,p-1
        x1d = ck*ad(i, 1, k) - sk*ad(i, 1, kp)
        x1 = ck*a(i, 1, k) - sk*a(i, 1, kp)
        y1d = ck*ad(i, 1, kp) + sk*ad(i, 1, k)
        y1 = ck*a(i, 1, kp) + sk*a(i, 1, k)
        bd(i, k, 0) = ad(i, 0, k) + x1d
        b(i, k, 0) = a(i, 0, k) + x1
        bd(i, kp, 0) = ad(i, 0, k) - x1d
        b(i, kp, 0) = a(i, 0, k) - x1
        bd(i, k, 1) = y1d - ad(i, 0, kp)
        b(i, k, 1) = -a(i, 0, kp) + y1
        bd(i, kp, 1) = ad(i, 0, kp) + y1d
        b(i, kp, 1) = a(i, 0, kp) + y1
      END DO
    END DO
  END IF
!
!     Code for K=R/2 when R is even not needed
!
!     IF (MOD(R,2).EQ.0) THEN
!        R2 = R/2
!        DO 120 I = 0, P - 1
!           B(I,R2,0) = A(I,0,R2)
!           B(I,R2,1) = -A(I,1,R2)
! 120    CONTINUE
!     END IF
!
  RETURN
END SUBROUTINE C06FPW_D
